### ISSUE TITLE
DB::Exception: Pipeline stuck. Current state: digraph

### ISSUE THREAD

**Issue by Sam--Shan** [ClickHouse/ClickHouse#10113]
Hi all,when i do my query，sometimes i will get this exception.how can i fix it or avoid it.is it related to any settings？
and this is my sql
[abc.txt](https://github.com/ClickHouse/ClickHouse/files/4448936/abc.txt)

**Comment by Sam--Shan** [comment]
aaaCH is a 60 million data

**Comment by Sam--Shan** [comment]
![企业微信截图_20200408154135](https://user-images.githubusercontent.com/10590637/78757667-73f69900-79af-11ea-9cb2-be53be7fda1e.png)

**Comment by Sam--Shan** [comment]
![image](https://user-images.githubusercontent.com/10590637/78760283-81158700-79b3-11ea-871a-a97170217e14.png)
i find the original code

**Comment by KochetovNicolai** [comment]
Hi.
Could you please send me the full exception message? (text, not image)
You can find it in server logs.

**Comment by Sam--Shan** [comment]
[exception.txt](https://github.com/ClickHouse/ClickHouse/files/4449306/exception.txt)
Thanks for your reply,Mr. Kochetov.And this is my exception.

**Comment by Sam--Shan** [comment]
@KochetovNicolai  I tried the lastest testing version  20.4.1.2909. It works, that exception is not displayed again. Looking forward to its release soon. Thanks a lot .

**Comment by KochetovNicolai** [comment]
@Sam--Shan thank you for feedback!
Most likely it was fixed after #10099

**Comment by junneyang** [comment]
still happends, clickhouse version=>20.3.5.21
![image](https://user-images.githubusercontent.com/6802322/97952848-ab101a00-1dd9-11eb-92ce-1554bc311a03.png)

**Comment by Sam--Shan** [comment]
> still happends, clickhouse version=>20.3.5.21
> ![image](https://user-images.githubusercontent.com/6802322/97952848-ab101a00-1dd9-11eb-92ce-1554bc311a03.png)

maybe you can try higher version

**Comment by Sam--Shan** [comment]
@junneyang, 杨先生吗，好巧，前两天刚看过您的一篇博客

**Comment by junneyang** [comment]
> > still happends, clickhouse version=>20.3.5.21
> > ![image](https://user-images.githubusercontent.com/6802322/97952848-ab101a00-1dd9-11eb-92ce-1554bc311a03.png)
> 
> maybe you can try higher version

@Sam--Shan  thanks, after upgrade to version 20.10.3.30, it's ok...

**Comment by junneyang** [comment]
> @junneyang, 杨先生吗，好巧，前两天刚看过您的一篇博客

是的，_ ^^ _
