### ISSUE TITLE
Segmentation fault with max_rows_to_group_by and group_by_overflow_mode = 'any' 

### ISSUE THREAD

**Issue by sfriquet** [ClickHouse/ClickHouse#10288]
**Describe the bug**
Query with `group by` makes server crash if `max_rows_to_group_by` is hit and `group_by_overflow_mode = 'any'`

**How to reproduce**
* ClickHouse server version 20.3.5 revision 54433 on debian-9-stretch-v20200309
* `SET max_rows_to_group_by = 1000, group_by_overflow_mode = 'any' ;`
* Then using the table (not distributed) and the query from the [tutorial](https://clickhouse.tech/docs/en/getting_started/tutorial/):

```
SELECT 
    StartURL AS URL, 
    AVG(Duration) AS AvgDuration
FROM tutorial.visits_v1
WHERE (StartDate >= '2014-03-23') AND (StartDate <= '2014-03-30')
GROUP BY URL
ORDER BY AvgDuration DESC
LIMIT 10

→ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) 
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000

Connecting to localhost:9000 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9000)
```

**Error message and/or stacktrace**
```
2020.04.15 16:14:50.822198 [ 3984 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Debug> executeQuery: (from [::1]:60842) SELECT StartURL AS URL, AVG(Duration) AS AvgDuration FROM tutorial.visits_v1 WHERE (StartDate >= '2014-03-23') AND (StartDate <= '2014-03-30') GROUP BY URL ORDER BY AvgDuration DESC LIMIT 10
2020.04.15 16:14:50.823081 [ 3984 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(StartDate >= '2014-03-23') AND (StartDate <= '2014-03-30')" moved to PREWHERE
2020.04.15 16:14:50.823388 [ 3984 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> AccessRightsContext (default): Access granted: SELECT(StartDate, Duration, StartURL) ON tutorial.visits_v1
2020.04.15 16:14:50.823688 [ 3984 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Debug> tutorial.visits_v1 (SelectExecutor): Key condition: (column 1 in [16152, +inf)), (column 1 in (-inf, 16159]), and
2020.04.15 16:14:50.823705 [ 3984 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Debug> tutorial.visits_v1 (SelectExecutor): MinMax index condition: (column 0 in [16152, +inf)), (column 0 in (-inf, 16159]), and
2020.04.15 16:14:50.823880 [ 3984 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Debug> tutorial.visits_v1 (SelectExecutor): Selected 5 parts by date, 5 parts by key, 223 marks to read from 12 ranges
2020.04.15 16:14:50.824304 [ 3984 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> tutorial.visits_v1 (SelectExecutor): Reading approx. 1505928 rows with 10 streams
2020.04.15 16:14:50.824816 [ 3984 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2020.04.15 16:14:50.825851 [ 3974 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.000 MiB) in 0.001 sec. (0.000 rows/sec., 0.000 MiB/sec.)
2020.04.15 16:14:50.827082 [ 3952 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> AggregatingTransform: Aggregating
2020.04.15 16:14:50.827117 [ 3952 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> Aggregator: Aggregation method: key_string
2020.04.15 16:14:50.828071 [ 3927 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> AggregatingTransform: Aggregating
2020.04.15 16:14:50.828104 [ 3927 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> Aggregator: Aggregation method: key_string
2020.04.15 16:14:50.828225 [ 3980 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> AggregatingTransform: Aggregating
2020.04.15 16:14:50.828267 [ 3980 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> Aggregator: Aggregation method: key_string
2020.04.15 16:14:50.828382 [ 3969 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> AggregatingTransform: Aggregating
2020.04.15 16:14:50.828422 [ 3969 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> Aggregator: Aggregation method: key_string
2020.04.15 16:14:50.828915 [ 3919 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> AggregatingTransform: Aggregating
2020.04.15 16:14:50.828954 [ 3919 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> Aggregator: Aggregation method: key_string
2020.04.15 16:14:50.829033 [ 3931 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> AggregatingTransform: Aggregating
2020.04.15 16:14:50.829079 [ 3931 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> Aggregator: Aggregation method: key_string
2020.04.15 16:14:50.829276 [ 4179 ] {} <Fatal> BaseDaemon: ########################################
2020.04.15 16:14:50.829333 [ 4179 ] {} <Fatal> BaseDaemon: (version 20.3.5.21 (official build)) (from thread 3952) (query_id: efc434da-ed21-48dd-bbbf-c8a5efe2d61c) Received signal Segmentation fault (11).
2020.04.15 16:14:50.829359 [ 4179 ] {} <Fatal> BaseDaemon: Address: 0x10 Access: read. Address not mapped to object.
2020.04.15 16:14:50.829375 [ 4179 ] {} <Fatal> BaseDaemon: Stack trace: 0xd18f99c 0xd210bed 0xd1811d1 0xddd7d33 0xdddbff9 0xdbb2881 0xdbb6b2d 0xdbb7522 0x8f567eb 0x8f54c33 0x7f6d69ad04a4 0x7f6d6a2dad0f
2020.04.15 16:14:50.829448 [ 4179 ] {} <Fatal> BaseDaemon: 3. void DB::Aggregator::executeImplCase<true, DB::AggregationMethodStringNoCache<StringHashMap<char*, Allocator<true, true> > > >(DB::AggregationMethodStringNoCache<StringHashMap<char*, Allocator<true, true> > >&, DB::AggregationMethodStringNoCache<StringHashMap<char*, Allocator<true, true> > >::State&, DB::Arena*, unsigned long, DB::Aggregator::AggregateFunctionInstruction*, char*) const @ 0xd18f99c in /usr/bin/clickhouse
2020.04.15 16:14:50.829500 [ 3960 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> AggregatingTransform: Aggregating
2020.04.15 16:14:50.829504 [ 4179 ] {} <Fatal> BaseDaemon: 4. void DB::Aggregator::executeImpl<DB::AggregationMethodStringNoCache<StringHashMap<char*, Allocator<true, true> > > >(DB::AggregationMethodStringNoCache<StringHashMap<char*, Allocator<true, true> > >&, DB::Arena*, unsigned long, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >&, DB::Aggregator::AggregateFunctionInstruction*, bool, char*) const @ 0xd210bed in /usr/bin/clickhouse
2020.04.15 16:14:50.829544 [ 3960 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> Aggregator: Aggregation method: key_string
2020.04.15 16:14:50.829584 [ 4179 ] {} <Fatal> BaseDaemon: 5. DB::Aggregator::executeOnBlock(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >, unsigned long, DB::AggregatedDataVariants&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >&, std::__1::vector<std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >, std::__1::allocator<std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > > >&, bool&) @ 0xd1811d1 in /usr/bin/clickhouse
2020.04.15 16:14:50.829605 [ 4179 ] {} <Fatal> BaseDaemon: 6. DB::AggregatingTransform::consume(DB::Chunk) @ 0xddd7d33 in /usr/bin/clickhouse
2020.04.15 16:14:50.829621 [ 4179 ] {} <Fatal> BaseDaemon: 7. DB::AggregatingTransform::work() @ 0xdddbff9 in /usr/bin/clickhouse
2020.04.15 16:14:50.829642 [ 4179 ] {} <Fatal> BaseDaemon: 8. ? @ 0xdbb2881 in /usr/bin/clickhouse
2020.04.15 16:14:50.829653 [ 4179 ] {} <Fatal> BaseDaemon: 9. DB::PipelineExecutor::executeSingleThread(unsigned long, unsigned long) @ 0xdbb6b2d in /usr/bin/clickhouse
2020.04.15 16:14:50.829663 [ 4179 ] {} <Fatal> BaseDaemon: 10. ? @ 0xdbb7522 in /usr/bin/clickhouse
2020.04.15 16:14:50.829678 [ 4179 ] {} <Fatal> BaseDaemon: 11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8f567eb in /usr/bin/clickhouse
2020.04.15 16:14:50.829688 [ 4179 ] {} <Fatal> BaseDaemon: 12. ? @ 0x8f54c33 in /usr/bin/clickhouse
2020.04.15 16:14:50.829706 [ 4179 ] {} <Fatal> BaseDaemon: 13. start_thread @ 0x74a4 in /lib/x86_64-linux-gnu/libpthread-2.24.so
2020.04.15 16:14:50.829726 [ 4179 ] {} <Fatal> BaseDaemon: 14. clone @ 0xe8d0f in /lib/x86_64-linux-gnu/libc-2.24.so
2020.04.15 16:14:50.829792 [ 4180 ] {} <Fatal> BaseDaemon: ########################################
2020.04.15 16:14:50.829839 [ 4180 ] {} <Fatal> BaseDaemon: (version 20.3.5.21 (official build)) (from thread 3927) (query_id: efc434da-ed21-48dd-bbbf-c8a5efe2d61c) Received signal Segmentation fault (11).
2020.04.15 16:14:50.829864 [ 4180 ] {} <Fatal> BaseDaemon: Address: 0x10 Access: read. Address not mapped to object.
2020.04.15 16:14:50.829880 [ 4180 ] {} <Fatal> BaseDaemon: Stack trace: 0xd18f99c 0xd210bed 0xd1811d1 0xddd7d33 0xdddbff9 0xdbb2881 0xdbb6b2d 0xdbb7522 0x8f567eb 0x8f54c33 0x7f6d69ad04a4 0x7f6d6a2dad0f
2020.04.15 16:14:50.829943 [ 4180 ] {} <Fatal> BaseDaemon: 3. void DB::Aggregator::executeImplCase<true, DB::AggregationMethodStringNoCache<StringHashMap<char*, Allocator<true, true> > > >(DB::AggregationMethodStringNoCache<StringHashMap<char*, Allocator<true, true> > >&, DB::AggregationMethodStringNoCache<StringHashMap<char*, Allocator<true, true> > >::State&, DB::Arena*, unsigned long, DB::Aggregator::AggregateFunctionInstruction*, char*) const @ 0xd18f99c in /usr/bin/clickhouse
2020.04.15 16:14:50.829966 [ 4180 ] {} <Fatal> BaseDaemon: 4. void DB::Aggregator::executeImpl<DB::AggregationMethodStringNoCache<StringHashMap<char*, Allocator<true, true> > > >(DB::AggregationMethodStringNoCache<StringHashMap<char*, Allocator<true, true> > >&, DB::Arena*, unsigned long, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >&, DB::Aggregator::AggregateFunctionInstruction*, bool, char*) const @ 0xd210bed in /usr/bin/clickhouse
2020.04.15 16:14:50.829986 [ 4180 ] {} <Fatal> BaseDaemon: 5. DB::Aggregator::executeOnBlock(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >, unsigned long, DB::AggregatedDataVariants&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >&, std::__1::vector<std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >, std::__1::allocator<std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > > >&, bool&) @ 0xd1811d1 in /usr/bin/clickhouse
2020.04.15 16:14:50.830002 [ 4180 ] {} <Fatal> BaseDaemon: 6. DB::AggregatingTransform::consume(DB::Chunk) @ 0xddd7d33 in /usr/bin/clickhouse
2020.04.15 16:14:50.830017 [ 4180 ] {} <Fatal> BaseDaemon: 7. DB::AggregatingTransform::work() @ 0xdddbff9 in /usr/bin/clickhouse
2020.04.15 16:14:50.830028 [ 4180 ] {} <Fatal> BaseDaemon: 8. ? @ 0xdbb2881 in /usr/bin/clickhouse
2020.04.15 16:14:50.830039 [ 4180 ] {} <Fatal> BaseDaemon: 9. DB::PipelineExecutor::executeSingleThread(unsigned long, unsigned long) @ 0xdbb6b2d in /usr/bin/clickhouse
2020.04.15 16:14:50.830049 [ 4180 ] {} <Fatal> BaseDaemon: 10. ? @ 0xdbb7522 in /usr/bin/clickhouse
2020.04.15 16:14:50.830061 [ 4180 ] {} <Fatal> BaseDaemon: 11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8f567eb in /usr/bin/clickhouse
2020.04.15 16:14:50.830074 [ 4180 ] {} <Fatal> BaseDaemon: 12. ? @ 0x8f54c33 in /usr/bin/clickhouse
2020.04.15 16:14:50.830093 [ 4180 ] {} <Fatal> BaseDaemon: 13. start_thread @ 0x74a4 in /lib/x86_64-linux-gnu/libpthread-2.24.so
2020.04.15 16:14:50.830120 [ 4180 ] {} <Fatal> BaseDaemon: 14. clone @ 0xe8d0f in /lib/x86_64-linux-gnu/libc-2.24.so
2020.04.15 16:14:50.830197 [ 3932 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> AggregatingTransform: Aggregating
2020.04.15 16:14:50.830224 [ 3932 ] {efc434da-ed21-48dd-bbbf-c8a5efe2d61c} <Trace> Aggregator: Aggregation method: key_string
2020.04.15 16:14:50.830579 [ 4181 ] {} <Fatal> BaseDaemon: ########################################
2020.04.15 16:14:50.830620 [ 4181 ] {} <Fatal> BaseDaemon: (version 20.3.5.21 (official build)) (from thread 3969) (query_id: efc434da-ed21-48dd-bbbf-c8a5efe2d61c) Received signal Segmentation fault (11).
2020.04.15 16:14:50.830650 [ 4181 ] {} <Fatal> BaseDaemon: Address: 0x10 Access: read. Address not mapped to object.
2020.04.15 16:14:50.830667 [ 4181 ] {} <Fatal> BaseDaemon: Stack trace: 0xd18f99c 0xd210bed 0xd1811d1 0xddd7d33 0xdddbff9 0xdbb2881 0xdbb6b2d 0xdbb7522 0x8f567eb 0x8f54c33 0x7f6d69ad04a4 0x7f6d6a2dad0f
2020.04.15 16:14:50.830710 [ 4181 ] {} <Fatal> BaseDaemon: 3. void DB::Aggregator::executeImplCase<true, DB::AggregationMethodStringNoCache<StringHashMap<char*, Allocator<true, true> > > >(DB::AggregationMethodStringNoCache<StringHashMap<char*, Allocator<true, true> > >&, DB::AggregationMethodStringNoCache<StringHashMap<char*, Allocator<true, true> > >::State&, DB::Arena*, unsigned long, DB::Aggregator::AggregateFunctionInstruction*, char*) const @ 0xd18f99c in /usr/bin/clickhouse
```

**Comment by alesapin** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/10025. IPatch will be available in release 20.3.6.

**Comment by sfriquet** [comment]
@alesapin I still see the same issue with version `20.3.7.46`

**Comment by cw9** [comment]
Hi, I saw the same issue in 20.3.5, is this confirmed to be fixed in 20.3.6?
