### ISSUE TITLE
Attaching a table with non-existent ZK path does not increase the ReadonlyReplica metric

### ISSUE THREAD

**Issue by SaltTan** [ClickHouse/ClickHouse#16045]
```
ATTACH TABLE test_no_zk
(
    `i` Int8,
    `d` Date
)
ENGINE = ReplicatedMergeTree('no_zk', 'replica')
ORDER BY tuple()

Ok.

SHOW CREATE TABLE test_no_zk

┌─statement──────────────────────────────────┐
│ CREATE TABLE default.test_no_zk
(
    `i` Int8,
    `d` Date
)
ENGINE = ReplicatedMergeTree('no_zk', 'replica')
ORDER BY tuple()
SETTINGS index_granularity = 8192
└─────────────────────────────────────────────┘

INSERT INTO test_no_zk VALUES (1, today())

Received exception from server (version 20.9.3):
Code: 242. DB::Exception: Received from localhost:9000. DB::Exception: Table is in readonly mode (zookeeper path: /no_zk).

SELECT
    metric,
    value
FROM system.metrics
WHERE metric = 'ReadonlyReplica'

┌─metric──────────┬─value─┐
│ ReadonlyReplica │     0 │
└─────────────────┴───────┘
```

**Comment by SaltTan** [comment]
Related #15598?
```
SELECT *
FROM system.replicas

Row 1:
──────
database:                   default
table:                      test_no_zk
engine:                     ReplicatedMergeTree
is_leader:                  0
can_become_leader:          1
is_readonly:                1
is_session_expired:         1
future_parts:               0
parts_to_check:             0
zookeeper_path:             /no_zk
replica_name:               replica
replica_path:               /no_zk/replicas/replica
columns_version:            -1
queue_size:                 0
inserts_in_queue:           0
merges_in_queue:            0
part_mutations_in_queue:    0
queue_oldest_time:          1970-01-01 00:00:00
inserts_oldest_time:        1970-01-01 00:00:00
merges_oldest_time:         1970-01-01 00:00:00
part_mutations_oldest_time: 1970-01-01 00:00:00
oldest_part_to_get:
oldest_part_to_merge_to:
oldest_part_to_mutate_to:
log_max_index:              0
log_pointer:                0
last_queue_update:          1970-01-01 00:00:00
absolute_delay:             1602799982
total_replicas:             0
active_replicas:            0
zookeeper_exception:
```

**Comment by den-crane** [comment]
I also stumbled on it in.

repro for Atomic DB

```sql
create  table test_zkp( A Int64) engine = ReplicatedMergeTree('/clickhouse/test/tables/test_zkp', 'r1') order by A;
detach table test_zkp;
system drop replica 'r1' FROM ZKPATH '/clickhouse/test/tables/test_zkp';
attach table test_zkp;


  select is_readonly, zookeeper_exception from system.replicas where table = 'test_zkp';
┌─is_readonly─┬─zookeeper_exception────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│           1 │ Code: 999. Coordination::Exception: No node, path: /clickhouse/test/tables/test_zkp/log. (KEEPER_EXCEPTION) (version 22.8.1.2097 (official build)) │
└─────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘


select  metric, value from system.metrics where metric ilike '%ReadonlyReplica%';
┌─metric──────────┬─value─┐
│ ReadonlyReplica │     0 │
└─────────────────┴───────┘
```

**Comment by alexey-milovidov** [comment]
Fixed:

```
milovidov-desktop :) ATTACH TABLE test_no_zk UUID 'a50b7933-59b2-49ce-8db6-59da3c9b4413'
                     (
                         `i` Int8,
                         `d` Date
                     )
                     ENGINE = ReplicatedMergeTree('no_zk', 'replica')
                     ORDER BY tuple()

ATTACH TABLE test_no_zk UUID 'a50b7933-59b2-49ce-8db6-59da3c9b4413'
(
    `i` Int8,
    `d` Date
)
ENGINE = ReplicatedMergeTree('no_zk', 'replica')
ORDER BY tuple()

Query id: 86f11968-c96d-4337-b2d2-8cc4f4f8fe94

Ok.

0 rows in set. Elapsed: 0.022 sec. 

milovidov-desktop :) SELECT * FROM system.replicas \G

SELECT *
FROM system.replicas

Query id: 09df1e25-17a8-4a4d-a480-283bb54d4e95

Row 1:
──────
database:                    default
table:                       test_no_zk
engine:                      ReplicatedMergeTree
is_leader:                   0
can_become_leader:           1
is_readonly:                 1
is_session_expired:          0
future_parts:                0
parts_to_check:              0
zookeeper_path:              /no_zk
replica_name:                replica
replica_path:                /no_zk/replicas/replica
columns_version:             -1
queue_size:                  0
inserts_in_queue:            0
merges_in_queue:             0
part_mutations_in_queue:     0
queue_oldest_time:           1970-01-01 01:00:00
inserts_oldest_time:         1970-01-01 01:00:00
merges_oldest_time:          1970-01-01 01:00:00
part_mutations_oldest_time:  1970-01-01 01:00:00
oldest_part_to_get:          
oldest_part_to_merge_to:     
oldest_part_to_mutate_to:    
log_max_index:               0
log_pointer:                 0
last_queue_update:           1970-01-01 01:00:00
absolute_delay:              1666221848
total_replicas:              0
active_replicas:             0
last_queue_update_exception: 
zookeeper_exception:         Code: 999. Coordination::Exception: No node, path: /no_zk/log. (KEEPER_EXCEPTION) (version 22.10.1.1)
replica_is_active:           {}

1 row in set. Elapsed: 0.002 sec.
```

**Comment by alexey-milovidov** [comment]
#40148

**Comment by SaltTan** [comment]
It is still broken in 21.11.
The problem was not in `system.replicas`, the problem was in `system.metrics`.
Maybe https://github.com/ClickHouse/ClickHouse/pull/44220 fixed it?

**Comment by SaltTan** [comment]
22.12 does not increase the ReadonlyReplica metric either
```
ClickHouse client version 22.12.1.1752 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.12.1 revision 54461.

SELECT count()
FROM system.replicas
WHERE is_readonly

┌─count()─┐
│       1 │
└─────────┘

SELECT value
FROM system.metrics
WHERE metric = 'ReadonlyReplica'

┌─value─┐
│     0 │
└───────┘
```

**Comment by wzb5212** [comment]
@SaltTan
