### ISSUE TITLE
Missed DateTime functions in Documents.

### ISSUE THREAD

**Issue by ucasFL** [ClickHouse/ClickHouse#16049]
Looks like documents doesn't contain some DateTime functions such as `DATE_ADD`, `DATE_SUB`...

**Comment by bharatnc** [comment]
Resolved via #20107.

**Comment by den-crane** [comment]
date_sub -- still not 

select date_sub(YEAR, 3, toDate('2018-01-01'));

**Comment by bharatnc** [comment]
> date_sub -- still not
> 
> select date_sub(YEAR, 3, toDate('2018-01-01'));

Thanks - I got confused between a similar func `date_diff` and eventually missed it. Added via #20163.
