### ISSUE TITLE
Msan failure in GRPC

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#19234]
```
2021.01.18 13:59:24.103746 [ 45 ] {} <Fatal> BaseDaemon: ########################################
2021.01.18 13:59:24.103901 [ 45 ] {} <Fatal> BaseDaemon: (version 21.1.1.5708, build id: 2AE3BAA553CA1C2137EA06A1E0C86896FA280AD1) (from thread 7) (no query) Received signal Unknown signal (-3)
2021.01.18 13:59:24.104011 [ 45 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2021.01.18 13:59:24.104217 [ 45 ] {} <Fatal> BaseDaemon: Stack trace: 0x8dfc049 0x941645c 0x8ceaa16 0x8c81263 0x3e0f0570 0x3e0f9a40 0x3e0f98a2 0x3e0f0301 0x3db4cf62 0x3db4b750 0x3d7413a9 0x3d6d88a6 0x3d755297 0x2fca86cd 0x2fea88dd 0x8d3436f 0x3a3df707 0x8d08280 0x3a43d8f8 0x8d03f8b 0x8cfe974 0x7f46fdcc80b3 0x8c8046e
2021.01.18 13:59:24.104680 [ 45 ] {} <Fatal> BaseDaemon: 0. ./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:293: StackTrace::StackTrace() @ 0x8dfc049 in /usr/bin/clickhouse
2021.01.18 13:59:24.105750 [ 45 ] {} <Fatal> BaseDaemon: 1. ./obj-x86_64-linux-gnu/../src/Common/CurrentThread.h:81: sanitizerDeathCallback() @ 0x941645c in /usr/bin/clickhouse
2021.01.18 13:59:24.111028 [ 45 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0x8ceaa16 in /usr/bin/clickhouse
2021.01.18 13:59:24.115910 [ 45 ] {} <Fatal> BaseDaemon: 3. ? @ 0x8c81263 in /usr/bin/clickhouse
2021.01.18 13:59:24.120357 [ 45 ] {} <Fatal> BaseDaemon: 4. ./obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/gpr/cpu_linux.cc:41: init_num_cpus() @ 0x3e0f0570 in /usr/bin/clickhouse
2021.01.18 13:59:24.124922 [ 45 ] {} <Fatal> BaseDaemon: 5. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:1006: void absl::lts_2020_02_25::base_internal::CallOnceImpl<void (*&)()>(std::__1::atomic<unsigned int>*, absl::lts_2020_02_25::base_internal::SchedulingMode, void (*&)()) @ 0x3e0f9a40 in /usr/bin/clickhouse
2021.01.18 13:59:24.129370 [ 45 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../contrib/abseil-cpp/absl/base/call_once.h:0: gpr_once_init @ 0x3e0f98a2 in /usr/bin/clickhouse
2021.01.18 13:59:24.133740 [ 45 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/gpr/cpu_linux.cc:58: gpr_cpu_num_cores @ 0x3e0f0301 in /usr/bin/clickhouse
2021.01.18 13:59:24.138130 [ 45 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/debug/stats.cc:41: grpc_stats_init() @ 0x3db4cf62 in /usr/bin/clickhouse
2021.01.18 13:59:24.142448 [ 45 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/surface/init.cc:141: grpc_init @ 0x3db4b750 in /usr/bin/clickhouse
2021.01.18 13:59:24.146810 [ 45 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../contrib/grpc/include/grpcpp/impl/grpc_library.h:34: grpc::internal::GrpcLibrary::init() @ 0x3d7413a9 in /usr/bin/clickhouse
2021.01.18 13:59:24.151612 [ 45 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../contrib/grpc/include/grpcpp/impl/codegen/grpc_library.h:46: grpc::CompletionQueue::CompletionQueue(grpc_completion_queue_attributes const&) @ 0x3d6d88a6 in /usr/bin/clickhouse
2021.01.18 13:59:24.155987 [ 45 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../contrib/grpc/include/grpcpp/impl/codegen/completion_queue.h:439: grpc::ServerBuilder::AddCompletionQueue(bool) @ 0x3d755297 in /usr/bin/clickhouse
2021.01.18 13:59:24.159606 [ 45 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../src/Server/GRPCServer.cpp:1645: DB::GRPCServer::start() @ 0x2fca86cd in /usr/bin/clickhouse
2021.01.18 13:59:24.163093 [ 45 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../src/Server/ProtocolServerAdapter.cpp:38: DB::ProtocolServerAdapter::GRPCServerAdapterImpl::start() @ 0x2fea88dd in /usr/bin/clickhouse
2021.01.18 13:59:24.164949 [ 45 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/iterator:1496: DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x8d3436f in /usr/bin/clickhouse
2021.01.18 13:59:24.169809 [ 45 ] {} <Fatal> BaseDaemon: 16. ./obj-x86_64-linux-gnu/../contrib/poco/Util/src/Application.cpp:0: Poco::Util::Application::run() @ 0x3a3df707 in /usr/bin/clickhouse
2021.01.18 13:59:24.170087 [ 45 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../programs/server/Server.cpp:325: DB::Server::run() @ 0x8d08280 in /usr/bin/clickhouse
2021.01.18 13:59:24.174219 [ 45 ] {} <Fatal> BaseDaemon: 18. ./obj-x86_64-linux-gnu/../contrib/poco/Util/src/ServerApplication.cpp:611: Poco::Util::ServerApplication::run(int, char**) @ 0x3a43d8f8 in /usr/bin/clickhouse
2021.01.18 13:59:24.174363 [ 45 ] {} <Fatal> BaseDaemon: 19. ./obj-x86_64-linux-gnu/../programs/server/Server.cpp:0: mainEntryClickHouseServer(int, char**) @ 0x8d03f8b in /usr/bin/clickhouse
2021.01.18 13:59:24.174519 [ 45 ] {} <Fatal> BaseDaemon: 20. ./obj-x86_64-linux-gnu/../programs/main.cpp:0: main @ 0x8cfe974 in /usr/bin/clickhouse
2021.01.18 13:59:24.174609 [ 45 ] {} <Fatal> BaseDaemon: 21. __libc_start_main @ 0x270b3 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.01.18 13:59:24.179494 [ 45 ] {} <Fatal> BaseDaemon: 22. _start @ 0x8c8046e in /usr/bin/clickhouse
2021.01.18 13:59:28.415480 [ 45 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 4CDB9EC68581FEA335FAB55DA36D9C22. There is no information about the reference checksum.
```
Found in https://github.com/ClickHouse/ClickHouse/pull/19215#issuecomment-762184431.

**Comment by alesapin** [comment]
Possibly fixed in https://github.com/ClickHouse/ClickHouse/pull/19214

**Comment by alexey-milovidov** [comment]
Yes, it's duplicate.
Also it's not a "bug" because no observable behaviour of ClickHouse is incorrect.

**Comment by qoega** [comment]
Not fixed:
Built on master bd81f43ecb33dfd160f54b97cebf533156d9565e
```
==7==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x3ec2b46f in init_num_cpus() obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/gpr/cpu_linux.cc:40:7
    #1 0x3ec3493f in decltype(std::declval<void (*&)()>()()) absl::lts_2020_02_25::base_internal::Callable::Invoke<void (*&)()>(void (*&)()) obj-x86_64-linux-gnu/../contrib/abseil-cpp/absl/base/internal/invoke.h:153:12
    #2 0x3ec3493f in decltype(Invoker<void (*&)()>::type::Invoke(std::declval<void (*&)()>())) absl::lts_2020_02_25::base_internal::Invoke<void (*&)()>(void (*&)()) obj-x86_64-linux-gnu/../contrib/abseil-cpp/absl/base/internal/invoke.h:180:10
    #3 0x3ec3493f in void absl::lts_2020_02_25::base_internal::CallOnceImpl<void (*&)()>(std::__1::atomic<unsigned int>*, absl::lts_2020_02_25::base_internal::SchedulingMode, void (*&)()) obj-x86_64-linux-gnu/../contrib/abseil-cpp/absl/base/call_once.h:178:5
    #4 0x3ec347a1 in void absl::lts_2020_02_25::call_once<void (*&)()>(absl::lts_2020_02_25::once_flag&, void (*&)()) obj-x86_64-linux-gnu/../contrib/abseil-cpp/absl/base/call_once.h:217:5
    #5 0x3ec347a1 in gpr_once_init obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/gpr/sync_abseil.cc:113:3
    #6 0x3ec2b200 in gpr_cpu_num_cores obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/gpr/cpu_linux.cc:57:3
    #7 0x3e687e61 in grpc_stats_init() obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/debug/stats.cc:41:17
    #8 0x3e68664f in grpc_init obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/surface/init.cc:140:5
    #9 0x3e27c2a8 in grpc::internal::GrpcLibrary::init() obj-x86_64-linux-gnu/../contrib/grpc/include/grpcpp/impl/grpc_library.h:34:26
    #10 0x3e2137a5 in grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool) obj-x86_64-linux-gnu/../contrib/grpc/include/grpcpp/impl/codegen/grpc_library.h:45:15
    #11 0x3e2137a5 in grpc::CompletionQueue::CompletionQueue(grpc_completion_queue_attributes const&) obj-x86_64-linux-gnu/../contrib/grpc/include/grpcpp/impl/codegen/completion_queue.h:240:3
    #12 0x3e290196 in grpc::ServerCompletionQueue::ServerCompletionQueue(grpc_cq_completion_type, grpc_cq_polling_type, grpc_experimental_completion_queue_functor*) obj-x86_64-linux-gnu/../contrib/grpc/include/grpcpp/impl/codegen/completion_queue.h:436:9
    #13 0x3e290196 in grpc::ServerBuilder::AddCompletionQueue(bool) obj-x86_64-linux-gnu/../contrib/grpc/src/cpp/server/server_builder.cc:73:41
    #14 0x306d297a in DB::GRPCServer::start() obj-x86_64-linux-gnu/../src/Server/GRPCServer.cpp:1645:21
    #15 0x308d333c in DB::ProtocolServerAdapter::GRPCServerAdapterImpl::start() obj-x86_64-linux-gnu/../src/Server/ProtocolServerAdapter.cpp:38:42
    #16 0x8eefaae in DB::ProtocolServerAdapter::start() obj-x86_64-linux-gnu/../src/Server/ProtocolServerAdapter.h:31:26
    #17 0x8eefaae in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) obj-x86_64-linux-gnu/../programs/server/Server.cpp:1240:20
    #18 0x3af1b346 in Poco::Util::Application::run() obj-x86_64-linux-gnu/../contrib/poco/Util/src/Application.cpp:334:8
    #19 0x8ec5e3f in DB::Server::run() obj-x86_64-linux-gnu/../programs/server/Server.cpp:337:25
    #20 0x3af78447 in Poco::Util::ServerApplication::run(int, char**) obj-x86_64-linux-gnu/../contrib/poco/Util/src/ServerApplication.cpp:611:9
    #21 0x8ec1af9 in mainEntryClickHouseServer(int, char**) obj-x86_64-linux-gnu/../programs/server/Server.cpp:129:20
    #22 0x8ebc3d3 in main obj-x86_64-linux-gnu/../programs/main.cpp:368:12
    #23 0x7fc9028aa0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #24 0x8e3decd in _start (/usr/bin/clickhouse+0x8e3decd)

  Uninitialized value was created by an allocation of 'cpu' in the stack frame of function 'sched_getcpu'
    #0 0x4282f660 in sched_getcpu obj-x86_64-linux-gnu/../base/glibc-compatibility/musl/sched_getcpu.c:32

SUMMARY: MemorySanitizer: use-of-uninitialized-value obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/gpr/cpu_linux.cc:40:7 in init_num_cpus()
```

**Comment by qoega** [comment]
Another one in GRPC. 
```
ESC[36mnode_1  |ESC[0m ==7==WARNING: MemorySanitizer: use-of-uninitialized-value
ESC[36mnode_1  |ESC[0m     #0 0x3e618d61 in pollable_process_events(grpc_pollset*, pollable*, bool) obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/iomgr/ev_epollex_linux.cc:880:9
ESC[36mnode_1  |ESC[0m     #1 0x3e61005f in pollset_work(grpc_pollset*, grpc_pollset_worker**, long) obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/iomgr/ev_epollex_linux.cc:1135:11
ESC[36mnode_1  |ESC[0m     #2 0x3e5f4546 in pollset_work(grpc_pollset*, grpc_pollset_worker**, long) obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/iomgr/ev_posix.cc:323:21
ESC[36mnode_1  |ESC[0m     #3 0x3e623bd6 in grpc_pollset_work(grpc_pollset*, grpc_pollset_worker**, long) obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/iomgr/pollset.cc:48:10
ESC[36mnode_1  |ESC[0m     #4 0x3e722161 in cq_next(grpc_completion_queue*, gpr_timespec, void*) obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/surface/completion_queue.cc:1054:23
ESC[36mnode_1  |ESC[0m     #5 0x3e71ec57 in grpc_completion_queue_next obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/surface/completion_queue.cc:1130:10
ESC[36mnode_1  |ESC[0m     #6 0x3e3217cd in grpc::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) obj-x86_64-linux-gnu/../contrib/grpc/src/cpp/common/completion_queue_cc.cc:54:15
ESC[36mnode_1  |ESC[0m     #7 0x3079b258 in grpc::CompletionQueue::Next(void**, bool*) obj-x86_64-linux-gnu/../contrib/grpc/include/grpcpp/impl/codegen/completion_queue.h:172:13
ESC[36mnode_1  |ESC[0m     #8 0x3079b258 in DB::GRPCServer::Runner::run() obj-x86_64-linux-gnu/../src/Server/GRPCServer.cpp:1594:31
ESC[36mnode_1  |ESC[0m     #9 0x3079ac86 in DB::GRPCServer::Runner::start()::'lambda'()::operator()() const obj-x86_64-linux-gnu/../src/Server/GRPCServer.cpp:1501:17
ESC[36mnode_1  |ESC[0m     #10 0x3079a92b in decltype(std::__1::forward<DB::GRPCServer::Runner::start()::'lambda'()&>(fp)()) std::__1::__invoke_constexpr<DB::GRPCServer::Runner::start()::'lambda'()&>(DB::GRPCServer::Runner::start()::'lambda'()&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3682:1
ESC[36mnode_1  |ESC[0m     #11 0x3079a92b in decltype(auto) std::__1::__apply_tuple_impl<DB::GRPCServer::Runner::start()::'lambda'()&, std::__1::tuple<>&>(DB::GRPCServer::Runner::start()::'lambda'()&, std::__1::tuple<>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1415:1
ESC[36mnode_1  |ESC[0m     #12 0x3079a92b in decltype(auto) std::__1::apply<DB::GRPCServer::Runner::start()::'lambda'()&, std::__1::tuple<>&>(DB::GRPCServer::Runner::start()::'lambda'()&, std::__1::tuple<>&) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1424:1
ESC[36mnode_1  |ESC[0m     #13 0x3079a92b in ThreadFromGlobalPool::ThreadFromGlobalPool<DB::GRPCServer::Runner::start()::'lambda'()&>(DB::GRPCServer::Runner::start()::'lambda'()&)::'lambda'()::operator()() obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:178:13
ESC[36mnode_1  |ESC[0m     #14 0x3079a788 in decltype(std::__1::forward<DB::GRPCServer::Runner::start()::'lambda'()&>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::GRPCServer::Runner::start()::'lambda'()&>(DB::GRPCServer::Runner::start()::'lambda'()&)::'lambda'()&>(DB::GRPCServer::Runner::start()::'lambda'()&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
ESC[36mnode_1  |ESC[0m     #15 0x3079a788 in void std::__1::__invoke_void_return_wrapper<void>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::GRPCServer::Runner::start()::'lambda'()&>(DB::GRPCServer::Runner::start()::'lambda'()&)::'lambda'()&>(DB::GRPCServer::Runner::start()::'lambda'()&...) obj-x86_64-linux-gnu/../contrib/libcxx/include/__functional_base:348:9
ESC[36mnode_1  |ESC[0m     #16 0x3079a788 in std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::GRPCServer::Runner::start()::'lambda'()&>(DB::GRPCServer::Runner::start()::'lambda'()&)::'lambda'(), void ()>::operator()() obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1608:12
ESC[36mnode_1  |ESC[0m     #17 0x3079a788 in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::GRPCServer::Runner::start()::'lambda'()&>(DB::GRPCServer::Runner::start()::'lambda'()&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2089:16
ESC[36mnode_1  |ESC[0m     #18 0x902f216 in std::__1::__function::__policy_func<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221:16
ESC[36mnode_1  |ESC[0m     #19 0x902f216 in std::__1::function<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560:12
ESC[36mnode_1  |ESC[0m     #20 0x902f216 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:247:17
ESC[36mnode_1  |ESC[0m     #21 0x903d897 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()::operator()() const obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:124:73
ESC[36mnode_1  |ESC[0m     #22 0x903d897 in decltype(std::__1::forward<void>(fp)(std::__1::forward<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(fp0)...)) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
ESC[36mnode_1  |ESC[0m     #23 0x903d897 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:280:5
ESC[36mnode_1  |ESC[0m     #24 0x903d897 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:291:5
ESC[36mnode_1  |ESC[0m     #25 0x7f0ea650d608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x9608)
ESC[36mnode_1  |ESC[0m     #26 0x7f0ea6434292 in clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)
ESC[36mnode_1  |ESC[0m
ESC[36mnode_1  |ESC[0m   Uninitialized value was created by a heap allocation
ESC[36mnode_1  |ESC[0m     #0 0x8e6b94d in malloc (/usr/bin/clickhouse+0x8e6b94d)
ESC[36mnode_1  |ESC[0m     #1 0x3ecd0be2 in gpr_malloc obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/gpr/alloc.cc:32:7
ESC[36mnode_1  |ESC[0m     #2 0x3e60c9ec in pollable_create(pollable_type, pollable**) obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/iomgr/ev_epollex_linux.cc:567:31
ESC[36mnode_1  |ESC[0m     #3 0x3e619166 in get_fd_pollable(grpc_fd*, pollable**) obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/iomgr/ev_epollex_linux.cc:829:30
ESC[36mnode_1  |ESC[0m     #4 0x3e619166 in pollset_transition_pollable_from_empty_to_fd_locked(grpc_pollset*, grpc_fd*) obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/iomgr/ev_epollex_linux.cc:1161:24
ESC[36mnode_1  |ESC[0m     #5 0x3e6118c2 in pollset_add_fd_locked(grpc_pollset*, grpc_fd*) obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/iomgr/ev_epollex_linux.cc:1202:15
ESC[36mnode_1  |ESC[0m     #6 0x3e6118c2 in pollset_add_fd(grpc_pollset*, grpc_fd*) obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/iomgr/ev_epollex_linux.cc:1292:23
ESC[36mnode_1  |ESC[0m     #7 0x3e5f431e in grpc_pollset_add_fd(grpc_pollset*, grpc_fd*) obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/iomgr/ev_posix.cc:338:3
ESC[36mnode_1  |ESC[0m     #8 0x3e65ede0 in tcp_server_start(grpc_tcp_server*, std::__1::vector<grpc_pollset*, std::__1::allocator<grpc_pollset*> > const*, void (*)(void*, grpc_endpoint*, grpc_pollset*, grpc_tcp_server_acceptor*), void*) obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/iomgr/tcp_server_posix.cc:519:9
ESC[36mnode_1  |ESC[0m     #9 0x3e65d677 in grpc_tcp_server_start(grpc_tcp_server*, std::__1::vector<grpc_pollset*, std::__1::allocator<grpc_pollset*> > const*, void (*)(void*, grpc_endpoint*, grpc_pollset*, grpc_tcp_server_acceptor*), void*) obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/iomgr/tcp_server.cc:34:3
ESC[36mnode_1  |ESC[0m     #10 0x3e4c36a4 in grpc_core::(anonymous namespace)::Chttp2ServerListener::Start(grpc_core::Server*, std::__1::vector<grpc_pollset*, std::__1::allocator<grpc_pollset*> > const*) obj-x86_64-linux-gnu/../contrib/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc:387:3
ESC[36mnode_1  |ESC[0m     #11 0x3e751987 in grpc_core::Server::Start() obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/surface/server.cc:574:24
ESC[36mnode_1  |ESC[0m     #12 0x3e7662bf in grpc_server_start obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/surface/server.cc:1489:24
ESC[36mnode_1  |ESC[0m     #13 0x3e367e82 in grpc::Server::Start(grpc::ServerCompletionQueue**, unsigned long) obj-x86_64-linux-gnu/../contrib/grpc/src/cpp/server/server_cc.cc:1168:3
ESC[36mnode_1  |ESC[0m     #14 0x3e33d9b1 in grpc::ServerBuilder::BuildAndStart() obj-x86_64-linux-gnu/../contrib/grpc/src/cpp/server/server_builder.cc:411:11
ESC[36mnode_1  |ESC[0m     #15 0x30716b15 in DB::GRPCServer::start() obj-x86_64-linux-gnu/../src/Server/GRPCServer.cpp:1646:27
ESC[36mnode_1  |ESC[0m     #16 0x309172fc in DB::ProtocolServerAdapter::GRPCServerAdapterImpl::start() obj-x86_64-linux-gnu/../src/Server/ProtocolServerAdapter.cpp:38:42
ESC[36mnode_1  |ESC[0m     #17 0x8f110ee in DB::ProtocolServerAdapter::start() obj-x86_64-linux-gnu/../src/Server/ProtocolServerAdapter.h:31:26
ESC[36mnode_1  |ESC[0m     #18 0x8f110ee in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) obj-x86_64-linux-gnu/../programs/server/Server.cpp:1240:20
ESC[36mnode_1  |ESC[0m     #19 0x3afc1446 in Poco::Util::Application::run() obj-x86_64-linux-gnu/../contrib/poco/Util/src/Application.cpp:334:8
ESC[36mnode_1  |ESC[0m     #20 0x8ee747f in DB::Server::run() obj-x86_64-linux-gnu/../programs/server/Server.cpp:337:25
ESC[36mnode_1  |ESC[0m     #21 0x3b01e547 in Poco::Util::ServerApplication::run(int, char**) obj-x86_64-linux-gnu/../contrib/poco/Util/src/ServerApplication.cpp:611:9
ESC[36mnode_1  |ESC[0m     #22 0x8ee3139 in mainEntryClickHouseServer(int, char**) obj-x86_64-linux-gnu/../programs/server/Server.cpp:129:20
ESC[36mnode_1  |ESC[0m
ESC[36mnode_1  |ESC[0m SUMMARY: MemorySanitizer: use-of-uninitialized-value obj-x86_64-linux-gnu/../contrib/grpc/src/core/lib/iomgr/ev_epollex_linux.cc:880:9 in pollable_process_events(grpc_pollset*, pollable*, bool)
```
