### ISSUE TITLE
Kafka Issue : Can't get assignment. It can be caused by some issue with consumer group (not enough partitions?). Will keep trying.

### ISSUE THREAD

**Issue by DipalPrajapati** [ClickHouse/ClickHouse#21740]
I have one topic my_topic with 4 partitions. 

```
$ /opt/kafka/bin/kafka-topics.sh --bootstrap-server host1:9092,host2:9092,host3:9092 --describe --topic my_topic
Topic: my_topic       PartitionCount: 4       ReplicationFactor: 2    Configs: compression.type=producer,segment.bytes=1073741824
        Topic: my_topic       Partition: 0    Leader: 1002    Replicas: 1002,1001     Isr: 1002,1001
        Topic: my_topic       Partition: 1    Leader: 1001    Replicas: 1001,1003     Isr: 1001,1003
        Topic: my_topic       Partition: 2    Leader: 1003    Replicas: 1003,1002     Isr: 1003,1002
        Topic: my_topic       Partition: 3    Leader: 1002    Replicas: 1002,1003     Isr: 1002,1003
```

It has 3 consumer groups. 

```
my_topic_raw_group
my_topic_1_group
my_topic_2_group
```

Which dumps to 3 different tables. 

Here is the create script. 

SHOW CREATE TABLE testKafkaRaw
Query id: bd494ea5-6303-4a3e-8ef3-61dd93be662b
┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE dma.testKafkaRaw
(
     ----definition
)
ENGINE = Kafka()
SETTINGS kafka_broker_list = 'my brokers', kafka_topic_list = 'my_topic', kafka_group_name = 'my_topic_raw_group', kafka_num_consumers = '1', kafka_format = 'CSV', kafka_row_delimiter = ',' │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
1 rows in set. Elapsed: 0.008 sec. 
show create table testKafkatable1;
SHOW CREATE TABLE testKafkatable1
Query id: c7485709-8df5-4f67-a3d0-32ce95e9b5b9
┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE dma.testKafkatable1
(
    ----definition
)
ENGINE = Kafka()
SETTINGS kafka_broker_list = 'my brokers', kafka_topic_list = 'my_topic', kafka_group_name = 'my_topic_1_group', kafka_num_consumers = '1', kafka_format = 'CSV', kafka_row_delimiter = ',' │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
1 rows in set. Elapsed: 0.009 sec. 
 show create table testKafkatable2;
SHOW CREATE TABLE testKafkatable2
Query id: b6f19cc1-9395-4f3e-a68b-8e3d1346b5ab
┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE dma.testKafkatable2
(
      ----definition

)
ENGINE = Kafka()
SETTINGS kafka_broker_list = 'my brokers', kafka_topic_list = 'my_topic', kafka_group_name = 'my_topic_2_group', kafka_num_consumers = '1', kafka_format = 'CSV', kafka_row_delimiter = ',' │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

It is giving below error in clickhouse log. 
```
2021.03.15 12:24:20.205372 [ 20718 ] {} <Trace> StorageKafka (testKafkaRaw): Nothing to commit.
2021.03.15 12:24:20.206022 [ 20718 ] {} <Trace> StorageKafka (testKafkaRaw): Stream(s) stalled. Reschedule.
2021.03.15 12:24:20.274580 [ 20711 ] {} <Debug> StorageKafka (testKafkatable2): Started streaming to 1 attached views
2021.03.15 12:24:20.276009 [ 20711 ] {} <Trace> StorageKafka (testKafkatable2): Already subscribed to topics: [my_topic]
2021.03.15 12:24:20.276115 [ 20711 ] {} <Trace> StorageKafka (testKafkatable2): Already assigned to: [  ]
2021.03.15 12:24:20.321613 [ 20700 ] {} <Debug> StorageKafka (testKafkatable1): Started streaming to 1 attached views
2021.03.15 12:24:20.326611 [ 20711 ] {} <Warning> StorageKafka (testKafkatable2): Can't get assignment. It can be caused by some issue with consumer group (not enough partitions?). Will keep trying.
2021.03.15 12:24:20.330550 [ 20711 ] {} <Trace> StorageKafka (testKafkatable2): Nothing to commit.
2021.03.15 12:24:20.331374 [ 20711 ] {} <Trace> StorageKafka (testKafkatable2): Stream(s) stalled. Reschedule.
2021.03.15 12:24:20.333877 [ 20700 ] {} <Trace> StorageKafka (testKafkatable1): Already subscribed to topics: [my_topic]
2021.03.15 12:24:20.333970 [ 20700 ] {} <Trace> StorageKafka (testKafkatable1): Already assigned to: [  ]
2021.03.15 12:24:20.384443 [ 20700 ] {} <Warning> StorageKafka (testKafkatable1): Can't get assignment. It can be caused by some issue with consumer group (not enough partitions?). Will keep trying.
2021.03.15 12:24:20.384823 [ 20700 ] {} <Trace> StorageKafka (testKafkatable1): Nothing to commit.
2021.03.15 12:24:20.385039 [ 20700 ] {} <Trace> StorageKafka (testKafkatable1): Stream(s) stalled. Reschedule.
```

Data is not coming into the tables.

**Comment by DipalPrajapati** [comment]
Actually the issue was in data (hence in parsing) but it must not give such generic error related to kafka, which is misguiding .

**Comment by DipalPrajapati** [comment]
@filimonov I am facing this issue again somehow clickhouse is not able to assign the partition.

**Comment by filimonov** [comment]
Most probably fixed in #21267

**Comment by hiepxanh** [comment]
I already find any possible posts about Clickhouse and Kafka and I still cannot understand this error or find a way to fix it, I'm really desperated, can someone help me to resolve this error? 
I have the same config above, I insert to CH and other kafka application get it but once I insert data from other source, the row select return 0 rows and have this error

**Comment by filimonov** [comment]
Can you update to 21.7 and check if you still have some issues there?
