### ISSUE TITLE
SQL execution error in playground

### ISSUE THREAD

**Issue by JonasBollack** [ClickHouse/ClickHouse#23353]
brief description of my scene
in https://play.clickhouse.tech/?file=welcome
to run sql:

select "t1"."__fcol_9" "__fcol_9"
from (
  (
    select null "__fcol_9"
    from `hits_100m_obfuscated` "T_1BC6A9"
  )
  union all (
    select "t0"."__fcol_9" "__fcol_9"
    from (select "T_C6A5C5"."Title" "__fcol_9"
    from `hits_100m_obfuscated` "T_C6A5C5") "t0"
  )
) "t1"
where "t1"."__fcol_9" in ('aaa')
limit 5000

get error: Code: 48, e.displayText() = DB::Exception: Serialization is not implemented for data type Nothing: while converting 'aaa' to Nothing (version 20.8.14.4 (official build))

**Comment by JonasBollack** [comment]
19.14 LTS get success
20.3 and 20.8 get error

**Comment by tavplubix** [comment]
Minimized query:

```
:) select null as c from system.one where c in ('aaa')

Received exception from server (version 21.3.1):
Code: 48. DB::Exception: Received from localhost:9000. DB::Exception: Serialization is not implemented for data type Nothing: while converting 'aaa' to Nothing: While processing (NULL AS c) IN ('aaa').
```

However, I cannot reproduce it using build from master, so looks like it was fixed recently

**Comment by tavplubix** [comment]
Fixed in #22063, let's backport it

**Comment by alexey-milovidov** [comment]
Ok.

I've uploaded the `hits_100m_obfuscated` table to new Playground:
https://gh-api.clickhouse.tech/play?user=play#c2VsZWN0ICJ0MSIuIl9fZmNvbF85IiAiX19mY29sXzkiCmZyb20gKAooCnNlbGVjdCBudWxsICJfX2Zjb2xfOSIKZnJvbSBoaXRzXzEwMG1fb2JmdXNjYXRlZCAiVF8xQkM2QTkiCikKdW5pb24gYWxsICgKc2VsZWN0ICJ0MCIuIl9fZmNvbF85IiAiX19mY29sXzkiCmZyb20gKHNlbGVjdCAiVF9DNkE1QzUiLiJUaXRsZSIgIl9fZmNvbF85Igpmcm9tIGhpdHNfMTAwbV9vYmZ1c2NhdGVkICJUX0M2QTVDNSIpICJ0MCIKKQopICJ0MSIKd2hlcmUgInQxIi4iX19mY29sXzkiIGluICgnYWFhJykKbGltaXQgNTAwMA==

The query is executing successfully. Though the result is empty (but it's ok).

**Comment by syco** [comment]
Hi,
I see this was backported to 20.8, but I still have this issue on 21.8.4.51 on debian 10.
Installed today following these instructions: https://clickhouse.tech/docs/en/getting-started/install/

Can you please advice?
Thanks
