### ISSUE TITLE
Race condition when doing various ALTERs in a system under a heavy load

### ISSUE THREAD

**Issue by vzakaznikov** [ClickHouse/ClickHouse#24134]
**Describe the bug**
New stress 01900_alter_race_condition_stress that can be found in https://github.com/ClickHouse/ClickHouse/pull/24132 fails when server is run with thread fuzzer enabled. This test was created based on the fails seen in RBAC TestFlows module (https://github.com/ClickHouse/ClickHouse/blob/master/tests/testflows/rbac/tests/privileges/alter/alter_column.py).

**Does it reproduce on recent release?**
Yes.

**How to reproduce**
Enable thread fuzzer in current environment
```
export THREAD_FUZZER_CPU_TIME_PERIOD_US=1000
export THREAD_FUZZER_SLEEP_PROBABILITY=0.1
export THREAD_FUZZER_SLEEP_TIME_US=100000

export THREAD_FUZZER_pthread_mutex_lock_BEFORE_MIGRATE_PROBABILITY=1
export THREAD_FUZZER_pthread_mutex_lock_AFTER_MIGRATE_PROBABILITY=1
export THREAD_FUZZER_pthread_mutex_unlock_BEFORE_MIGRATE_PROBABILITY=1
export THREAD_FUZZER_pthread_mutex_unlock_AFTER_MIGRATE_PROBABILITY=1

export THREAD_FUZZER_pthread_mutex_lock_BEFORE_SLEEP_PROBABILITY=0.001
export THREAD_FUZZER_pthread_mutex_lock_AFTER_SLEEP_PROBABILITY=0.001
export THREAD_FUZZER_pthread_mutex_unlock_BEFORE_SLEEP_PROBABILITY=0.001
export THREAD_FUZZER_pthread_mutex_unlock_AFTER_SLEEP_PROBABILITY=0.001
export THREAD_FUZZER_pthread_mutex_lock_BEFORE_SLEEP_TIME_US=10000
export THREAD_FUZZER_pthread_mutex_lock_AFTER_SLEEP_TIME_US=10000
export THREAD_FUZZER_pthread_mutex_unlock_BEFORE_SLEEP_TIME_US=10000
export THREAD_FUZZER_pthread_mutex_unlock_AFTER_SLEEP_TIME_US=10000
```

start server so that it gets all the environment variables
 
```
sudo -E -u clickhouse ./build/programs/clickhouse-server --config-file=/etc/clickhouse-server/config.xml
```

repeatedly run new tests until fail

```
tests/clickhouse-test -b build/programs/clickhouse  -c build/programs/clickhouse-client --queries tests/queries/ 01900_alter_race_condition
```

**Expected behavior**
Test should not fail with thread fuzzer enabled.

**Comment by alesapin** [comment]
Seems like it's not related to alters:
```
[10:52:57]alesap@click:~/debugtoo/biglog$ zgrep -a 'Fatal' clickhouse-server.log.gz 
2021.05.15 00:03:50.761519 [ 14704 ] {} <Fatal> BaseDaemon: ########################################
2021.05.15 00:03:50.777665 [ 14704 ] {} <Fatal> BaseDaemon: (version 21.6.1.6840, build id: 9F9A4DB2FC589DAE864D33415BEDCEB59002847D) (from thread 5270) (no query) Received signal Segmentation fault (11)
2021.05.15 00:03:50.812759 [ 14704 ] {} <Fatal> BaseDaemon: Address: 0x68 Access: read. Address not mapped to object.
2021.05.15 00:03:50.827957 [ 14704 ] {} <Fatal> BaseDaemon: Stack trace: 0x7eff66c8ffc4 0xb0b99b6 0x2d04a44b 0x1f1ae8d9 0x1f0bb606 0x1f0b8859 0x1f041e64 0x1f03f9cd 0x1fc0b3c0 0x1fc187c1 0x22413e48 0x2243c15d 0x2868d72f 0x2868e2f3 0x28969e95 0x289641b7 0x7eff66c8d609 0x7eff66bb4293
2021.05.15 00:03:50.841389 [ 14704 ] {} <Fatal> BaseDaemon: 3. pthread_mutex_lock @ 0xbfc4 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.05.15 00:03:50.889732 [ 14704 ] {} <Fatal> BaseDaemon: 4. ./obj-x86_64-linux-gnu/../src/Common/ThreadFuzzer.cpp:0: pthread_mutex_lock @ 0xb0b99b6 in /usr/bin/clickhouse
2021.05.15 00:03:50.902680 [ 14704 ] {} <Fatal> BaseDaemon: 5. ./obj-x86_64-linux-gnu/../contrib/libcxx/src/mutex.cpp:34: std::__1::mutex::lock() @ 0x2d04a44b in /usr/bin/clickhouse
2021.05.15 00:03:50.930087 [ 14704 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3097: shared_ptr
2021.05.15 00:03:50.932243 [ 14704 ] {} <Fatal> BaseDaemon: 6. ../src/Access/EnabledRoles.cpp:19: DB::EnabledRoles::getRolesInfo() const @ 0x1f1ae8d9 in /usr/bin/clickhouse
2021.05.15 00:03:51.502183 [ 14704 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../src/Access/ContextAccess.cpp:0: DB::ContextAccess::setUser(std::__1::shared_ptr<DB::User const> const&) const @ 0x1f0bb606 in /usr/bin/clickhouse
2021.05.15 00:03:52.270075 [ 14704 ] {} <Fatal> BaseDaemon: 8.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3211: ~shared_ptr
2021.05.15 00:03:52.270463 [ 14704 ] {} <Fatal> BaseDaemon: 8. ../src/Access/ContextAccess.cpp:154: DB::ContextAccess::ContextAccess(DB::AccessControlManager const&, DB::ContextAccessParams const&) @ 0x1f0b8859 in /usr/bin/clickhouse
2021.05.15 00:03:53.276345 [ 14704 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../src/Access/AccessControlManager.cpp:0: DB::AccessControlManager::ContextAccessCache::getContextAccess(DB::ContextAccessParams const&) @ 0x1f041e64 in /usr/bin/clickhouse
2021.05.15 00:03:54.149178 [ 14704 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../src/Access/AccessControlManager.cpp:0: DB::AccessControlManager::getContextAccess(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, std::__1::vector<StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>, std::__1::allocator<StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> > > const&, bool, DB::Settings const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ClientInfo const&) const @ 0x1f03f9cd in /usr/bin/clickhouse
2021.05.15 00:03:56.144147 [ 14704 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../src/Interpreters/Context.cpp:849: DB::Context::calculateAccessRights() @ 0x1fc0b3c0 in /usr/bin/clickhouse
2021.05.15 00:03:58.805882 [ 14704 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__mutex_base:141: ~unique_lock
2021.05.15 00:03:58.806949 [ 14704 ] {} <Fatal> BaseDaemon: 12. ../src/Interpreters/Context.cpp:1231: DB::Context::setCurrentDatabase(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1fc187c1 in /usr/bin/clickhouse
2021.05.15 00:04:00.424705 [ 14704 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x22413e48 in /usr/bin/clickhouse
2021.05.15 00:04:02.006144 [ 14704 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1623: DB::TCPHandler::run() @ 0x2243c15d in /usr/bin/clickhouse
2021.05.15 00:04:02.010240 [ 14704 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x2868d72f in /usr/bin/clickhouse
2021.05.15 00:04:02.065707 [ 14704 ] {} <Fatal> BaseDaemon: 16. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:114: Poco::Net::TCPServerDispatcher::run() @ 0x2868e2f3 in /usr/bin/clickhouse
2021.05.15 00:04:02.104057 [ 14704 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x28969e95 in /usr/bin/clickhouse
2021.05.15 00:04:02.137482 [ 14704 ] {} <Fatal> BaseDaemon: 18. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:0: Poco::ThreadImpl::runnableEntry(void*) @ 0x289641b7 in /usr/bin/clickhouse
2021.05.15 00:04:02.139925 [ 14704 ] {} <Fatal> BaseDaemon: 19. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.05.15 00:04:02.140953 [ 14704 ] {} <Fatal> BaseDaemon: 20. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.05.15 00:04:03.727499 [ 14704 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: A54853BF3924CE7B1063BDBB34C45968. There is no information about the reference checksum.
2021.05.15 00:04:11.800986 [ 141 ] {} <Fatal> Application: Child process was terminated by signal 11.
```

**Comment by vzakaznikov** [comment]
That fatal error is not what we were looking for but good that we caught it.

**Comment by alesapin** [comment]
The fix is merged, I'll close.

**Comment by vzakaznikov** [comment]
@alesapin, let's reopen. On master the stress test still fails. 

```

**Comment by vzakaznikov** [comment]
Actually, no need to re-open. After updates to the original test it does not fail. The fail above was due to hitting the maximum concurrent queries limit.
