### ISSUE TITLE
crash with prefer_column_name_to_alias on 21.8.5

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#28963]
**Describe what's wrong**

Query crashes if you map multiple columns to single alias on different levels of subquery.

**Does it reproduce on recent release?**

Yes, ClickHouse version 21.8.5

**How to reproduce**
ClickHouse version 21.8.5

```
SELECT
    0 AS test,
    test
FROM
(
    SELECT toNullable('a') AS test
)
SETTINGS prefer_column_name_to_alias = 1

Query id: 2c0ba3b6-0a2a-47c8-a849-1ab429b7a499

┌─test─┬─test─┐
│    0 │ ᴺᵁᴸᴸ │
└──────┴──────┘
Aborted

2021.09.13 07:55:28.174220 [ 227 ] {} <Fatal> BaseDaemon: ########################################
2021.09.13 07:55:28.174366 [ 227 ] {} <Fatal> BaseDaemon: (version 21.8.5.7 (official build), build id: 002660CFDF969F9EBCB93D09D84DC76B0B469329) (from thread 57) (query_id: 38cc2d5f-430d-4b6e-a5be-2dc7ea30ac8a) Received signal Segmentation fault (11)
2021.09.13 07:55:28.174435 [ 227 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2021.09.13 07:55:28.174506 [ 227 ] {} <Fatal> BaseDaemon: Stack trace: 0x10826bb2 0xfe7476a 0x1057e935 0x10fe3cca 0x10fe1b7a 0x10fdadea 0x10fecb99 0x13b63c6f 0x13b656fa 0x13c98579 0x13c9480a 0x7fdb5716f609 0x7fdb57085293
2021.09.13 07:55:28.175447 [ 227 ] {} <Fatal> BaseDaemon: 1. DB::ColumnNullable::checkConsistency() const @ 0x10826bb2 in /usr/bin/clickhouse
2021.09.13 07:55:28.175564 [ 227 ] {} <Fatal> BaseDaemon: 2. DB::SerializationNullable::serializeBinaryBulkWithMultipleStreams(DB::IColumn const&, unsigned long, unsigned long, DB::ISerialization::SerializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::SerializeBinaryBulkState>&) const @ 0xfe7476a in /usr/bin/clickhouse
2021.09.13 07:55:28.176577 [ 227 ] {} <Fatal> BaseDaemon: 3. DB::NativeBlockOutputStream::write(DB::Block const&) @ 0x1057e935 in /usr/bin/clickhouse
2021.09.13 07:55:28.177667 [ 227 ] {} <Fatal> BaseDaemon: 4. DB::TCPHandler::sendData(DB::Block const&) @ 0x10fe3cca in /usr/bin/clickhouse
2021.09.13 07:55:28.177866 [ 227 ] {} <Fatal> BaseDaemon: 5. DB::TCPHandler::processOrdinaryQueryWithProcessors() @ 0x10fe1b7a in /usr/bin/clickhouse
2021.09.13 07:55:28.177960 [ 227 ] {} <Fatal> BaseDaemon: 6. DB::TCPHandler::runImpl() @ 0x10fdadea in /usr/bin/clickhouse
2021.09.13 07:55:28.178054 [ 227 ] {} <Fatal> BaseDaemon: 7. DB::TCPHandler::run() @ 0x10fecb99 in /usr/bin/clickhouse
2021.09.13 07:55:28.178132 [ 227 ] {} <Fatal> BaseDaemon: 8. Poco::Net::TCPServerConnection::start() @ 0x13b63c6f in /usr/bin/clickhouse
2021.09.13 07:55:28.178200 [ 227 ] {} <Fatal> BaseDaemon: 9. Poco::Net::TCPServerDispatcher::run() @ 0x13b656fa in /usr/bin/clickhouse
2021.09.13 07:55:28.178276 [ 227 ] {} <Fatal> BaseDaemon: 10. Poco::PooledThread::run() @ 0x13c98579 in /usr/bin/clickhouse
2021.09.13 07:55:28.178351 [ 227 ] {} <Fatal> BaseDaemon: 11. Poco::ThreadImpl::runnableEntry(void*) @ 0x13c9480a in /usr/bin/clickhouse
2021.09.13 07:55:28.178435 [ 227 ] {} <Fatal> BaseDaemon: 12. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.09.13 07:55:28.178491 [ 227 ] {} <Fatal> BaseDaemon: 13. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.09.13 07:55:28.464365 [ 227 ] {} <Fatal> BaseDaemon: Checksum of the binary: C815004D2EAD6F8A74A53F5B6A027A55, integrity check passed.
2021.09.13 07:55:44.543996 [ 230 ] {} <Fatal> BaseDaemon: 


SELECT
    test,
    0 AS test
FROM
(
    SELECT toNullable('a') AS test
)
SETTINGS prefer_column_name_to_alias = 1

Query id: 4ef190c7-9880-4c46-b07a-b9fdf8c37886

┌─test─┬─test─┐
│ a    │    0 │
└──────┴──────┘

1 rows in set. Elapsed: 0.006 sec.
```

**Expected behavior**

Query works.

**Error message and/or stacktrace**

```
2021.09.13 07:55:28.174220 [ 227 ] {} <Fatal> BaseDaemon: ########################################
2021.09.13 07:55:28.174366 [ 227 ] {} <Fatal> BaseDaemon: (version 21.8.5.7 (official build), build id: 002660CFDF969F9EBCB93D09D84DC76B0B469329) (from thread 57) (query_id: 38cc2d5f-430d-4b6e-a5be-2dc7ea30ac8a) Received signal Segmentation fault (11)
2021.09.13 07:55:28.174435 [ 227 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2021.09.13 07:55:28.174506 [ 227 ] {} <Fatal> BaseDaemon: Stack trace: 0x10826bb2 0xfe7476a 0x1057e935 0x10fe3cca 0x10fe1b7a 0x10fdadea 0x10fecb99 0x13b63c6f 0x13b656fa 0x13c98579 0x13c9480a 0x7fdb5716f609 0x7fdb57085293
2021.09.13 07:55:28.175447 [ 227 ] {} <Fatal> BaseDaemon: 1. DB::ColumnNullable::checkConsistency() const @ 0x10826bb2 in /usr/bin/clickhouse
2021.09.13 07:55:28.175564 [ 227 ] {} <Fatal> BaseDaemon: 2. DB::SerializationNullable::serializeBinaryBulkWithMultipleStreams(DB::IColumn const&, unsigned long, unsigned long, DB::ISerialization::SerializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::SerializeBinaryBulkState>&) const @ 0xfe7476a in /usr/bin/clickhouse
2021.09.13 07:55:28.176577 [ 227 ] {} <Fatal> BaseDaemon: 3. DB::NativeBlockOutputStream::write(DB::Block const&) @ 0x1057e935 in /usr/bin/clickhouse
2021.09.13 07:55:28.177667 [ 227 ] {} <Fatal> BaseDaemon: 4. DB::TCPHandler::sendData(DB::Block const&) @ 0x10fe3cca in /usr/bin/clickhouse
2021.09.13 07:55:28.177866 [ 227 ] {} <Fatal> BaseDaemon: 5. DB::TCPHandler::processOrdinaryQueryWithProcessors() @ 0x10fe1b7a in /usr/bin/clickhouse
2021.09.13 07:55:28.177960 [ 227 ] {} <Fatal> BaseDaemon: 6. DB::TCPHandler::runImpl() @ 0x10fdadea in /usr/bin/clickhouse
2021.09.13 07:55:28.178054 [ 227 ] {} <Fatal> BaseDaemon: 7. DB::TCPHandler::run() @ 0x10fecb99 in /usr/bin/clickhouse
2021.09.13 07:55:28.178132 [ 227 ] {} <Fatal> BaseDaemon: 8. Poco::Net::TCPServerConnection::start() @ 0x13b63c6f in /usr/bin/clickhouse
2021.09.13 07:55:28.178200 [ 227 ] {} <Fatal> BaseDaemon: 9. Poco::Net::TCPServerDispatcher::run() @ 0x13b656fa in /usr/bin/clickhouse
2021.09.13 07:55:28.178276 [ 227 ] {} <Fatal> BaseDaemon: 10. Poco::PooledThread::run() @ 0x13c98579 in /usr/bin/clickhouse
2021.09.13 07:55:28.178351 [ 227 ] {} <Fatal> BaseDaemon: 11. Poco::ThreadImpl::runnableEntry(void*) @ 0x13c9480a in /usr/bin/clickhouse
2021.09.13 07:55:28.178435 [ 227 ] {} <Fatal> BaseDaemon: 12. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.09.13 07:55:28.178491 [ 227 ] {} <Fatal> BaseDaemon: 13. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.09.13 07:55:28.464365 [ 227 ] {} <Fatal> BaseDaemon: Checksum of the binary: C815004D2EAD6F8A74A53F5B6A027A55, integrity check passed.
2021.09.13 07:55:44.543996 [ 230 ] {} <Fatal> BaseDaemon: 
```

**Additional context**

Issue do not reproduces in 21.10 or 21.9.2.7

**Comment by alexey-milovidov** [comment]
CC @amosbird

**Comment by alexey-milovidov** [comment]
I've fixed it :) #26639
But the fix cannot be backported to older versions.

Maybe someone will come up with less intrusive fix for older versions.
For those who affected by this issue: simply disable `prefer_column_name_to_alias` and not allow users to enable this setting.

**Comment by UnamedRus** [comment]
But it still exist in latest lts (21.8), can we mark this issue as crash then? As this setting doesn't have experimental status.

So people will be aware about it.

**Comment by alexey-milovidov** [comment]
Ok. We can also commit the removal of this setting from 21.8 (if you like).

**Comment by UnamedRus** [comment]
This setting is pretty useful and helps for some bi tools. (before we will have ansi sql behavior for aliases)
It's one of the reasons why the did upgrad to 21.8, just to have this setting.

**Comment by alexey-milovidov** [comment]
Ok.

**Comment by amosbird** [comment]
Is it a bug of `prefer_column_name_to_alias` itself or a bug that can be unveiled by this setting?

**Comment by janantos** [comment]
Speaking the devil, we have found that is does exhibits only when it is NULL or nullable column in inner query.
```
select 1 as test, * from (
             SELECT NULL AS test
                )
settings prefer_column_name_to_alias=1;
```
 but not 
```
select 1 as test, * from (
             SELECT toInt8(1) AS test
                )
settings prefer_column_name_to_alias=1;
```
