### ISSUE TITLE
Flaky 02010_lc_native

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#31653]
From CI report:
```


5 | 3 | 2021-11-23 04:49:45 | Stateless tests (debug, actions) | 02010_lc_native | <a href="https://s3.amazonaws.com/clickhouse-test-reports/0/dc34ac111e4b6441771183ed5406b4005d0bb2f8/stateless_tests__debug__actions_.html">FLAKY</a>
-- | -- | -- | -- | -- | --

```

Build: https://s3.amazonaws.com/clickhouse-test-reports/0/dc34ac111e4b6441771183ed5406b4005d0bb2f8/stateless_tests__debug__actions_.html

Some of the errors:

```
2021-11-23 04:52:42 02010_lc_native:                                                        [ FAIL ] 5.65 sec. - having stderror: 
2021-11-23 04:52:42 Traceback (most recent call last):
2021-11-23 04:52:42   File "/usr/share/clickhouse-test/queries/0_stateless/02010_lc_native.python", line 312, in <module>
2021-11-23 04:52:42     main()
2021-11-23 04:52:42   File "/usr/share/clickhouse-test/queries/0_stateless/02010_lc_native.python", line 308, in main
2021-11-23 04:52:42     insertLowCardinalityRowWithIndexOverflow()
2021-11-23 04:52:42   File "/usr/share/clickhouse-test/queries/0_stateless/02010_lc_native.python", line 248, in insertLowCardinalityRowWithIndexOverflow
2021-11-23 04:52:42     readHeader(s)
2021-11-23 04:52:42   File "/usr/share/clickhouse-test/queries/0_stateless/02010_lc_native.python", line 174, in readHeader
2021-11-23 04:52:42     raise RuntimeError(readException(s))
2021-11-23 04:52:42 RuntimeError: code 216:  Query with id = 7b37201a034646bbae1643311c785de6 is already running.
2021-11-23 04:52:42 
2021-11-23 04:52:42 stdout:
2021-11-23 04:52:42 Rows 0 Columns 1
2021-11-23 04:52:42 Column x type LowCardinality(String)
2021-11-23 04:52:42 
2021-11-23 04:52:42 
```

```
$ grep 7b37201a034646bbae1643311c785de6 clickhouse-server\ \(1\).log
^[[3~2021.11.23 04:52:40.003276 [ 5885 ] {7b37201a034646bbae1643311c785de6} <Debug> executeQuery: (from [::ffff:127.0.0.1]:50828) insert into test_vcizpq.tab format TSV settings input_format_defaults_for_omitted_fields=0
2021.11.23 04:52:40.003619 [ 5885 ] {7b37201a034646bbae1643311c785de6} <Trace> ContextAccess (default): Access granted: INSERT(x) ON test_vcizpq.tab
2021.11.23 04:52:40.006740 [ 5885 ] {7b37201a034646bbae1643311c785de6} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 102.57 GiB.
2021.11.23 04:52:40.009928 [ 5885 ] {7b37201a034646bbae1643311c785de6} <Trace> test_vcizpq.tab (3377b834-ae9c-4700-b377-b834ae9c3700): Renaming temporary part tmp_insert_all_1_1_0 to all_1_1_0.
2021.11.23 04:52:40.011079 [ 5885 ] {7b37201a034646bbae1643311c785de6} <Debug> MemoryTracker: Peak memory usage (for query): 4.07 MiB.
2021.11.23 04:52:40.014737 [ 3368 ] {7b37201a034646bbae1643311c785de6} <Debug> executeQuery: (from [::ffff:127.0.0.1]:50834) insert into test_vcizpq.tab format TSV settings input_format_defaults_for_omitted_fields=0
2021.11.23 04:52:41.868906 [ 3368 ] {7b37201a034646bbae1643311c785de6} <Error> executeQuery: Code: 216. DB::Exception: Query with id = 7b37201a034646bbae1643311c785de6 is already running. (QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING) (version 21.12.1.0) (from [::ffff:127.0.0.1]:50834) (in query: insert into test_vcizpq.tab format TSV settings input_format_defaults_for_omitted_fields=0), Stack trace (when copying this message, always include the lines below):
2021.11.23 04:52:41.869635 [ 3368 ] {7b37201a034646bbae1643311c785de6} <Error> TCPHandler: Code: 216. DB::Exception: Query with id = 7b37201a034646bbae1643311c785de6 is already running. (QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING), Stack trace (when copying this message, always include the lines below):
2021.11.23 04:52:41.878218 [ 3368 ] {7b37201a034646bbae1643311c785de6} <Debug> MemoryTracker: Peak memory usage (for query): 2.02 MiB.
```

https://github.com/ClickHouse/ClickHouse/pull/31556 tried to fix it, but it's still happening

It's likely that the issue isn't on the randomness of the query_id but on it being reused for multiple queries inside the test.

**Comment by azat** [comment]
Can be closed (Had been fixed in #31556)

**Comment by Algunenano** [comment]
I don't think it's fixed. You can see that in the logs the query_id `7b37201a034646bbae1643311c785de6` is an uuid (change introduced in #31556) but it still failed

**Comment by azat** [comment]
Sorry, missed the description, you are right!
