### ISSUE TITLE
HTTP Interface - unexpected Content-Type when send_progress_in_http_headers is enabled

### ISSUE THREAD

**Issue by anselmodadams** [ClickHouse/ClickHouse#33308]
**Describe the unexpected behavior**
Using HTTP Interface for queries using option send_progress_in_http_headers=(true|1) sometimes gives wrong Content-Type header - for example, expected a content-type header of text/tab-separated-values for TSV, application/json for JSON or text/csv for CSV but get a text/plain in the response when the query runs longer than http_headers_progress_interval_ms (200ms) to get the first block for result. 

**How to reproduce**
Versions used in the tests: 21.8.6.15, 21.11.6.7, 21.12.2.17, 21.12.3.32

For CSV (expecting `text/csv`):

```
    (seq 1 1000| xargs -n1 -P0 -Ixxx curl -v "http://localhost:8123/?http_headers_progress_interval_ms=1&send_progress_in_http_headers=true&query=select+sleepEachRow(0.01)from+numbers(10)+FORMAT+CSV" 2>&1|grep -Eo " Content-Type:.*$")|sort | uniq -c
```

    Results would be like:

```
    728  Content-Type: text/csv; charset=UTF-8; header=absent
    190  Content-Type: text/plain; charset=UTF-8
```

For TSV (expecting `text/tab-separated-values`):

```
    (seq 1 1000| xargs -n1 -P0 -Ixxx curl -v "http://localhost:8123/?http_headers_progress_interval_ms=1&send_progress_in_http_headers=true&query=select+sleepEachRow(0.01)from+numbers(10)" 2>&1|grep -Eo " Content-Type:.*$")|sort | uniq -c
```

    or 

```
(seq 1 1000| xargs -n1 -P0 -Ixxx curl -v "http://localhost:8123/?http_headers_progress_interval_ms=1&send_progress_in_http_headers=true&query=select+sleepEachRow(0.01)from+numbers(10)+FORMAT+TSV" 2>&1|grep -Eo " Content-Type:.*$")|sort | uniq -c
```

    Results would be like:

```
    218  Content-Type: text/plain; charset=UTF-8
    706  Content-Type: text/tab-separated-values; charset=UTF-8
```

For JSON Format (expecting `application/json`): 
 ```
    (seq 1 1000| xargs -n1 -P0 -Ixxx curl -v "http://localhost:8123/?http_headers_progress_interval_ms=1&send_progress_in_http_headers=true&query=select+sleepEachRow(0.01)from+numbers(10)+FORMAT+JSON" 2>&1|grep -Eo " Content-Type:.*$")|sort | uniq -c
```

    Results would be like: 

```
    659  Content-Type: application/json; charset=UTF-8
    243  Content-Type: text/plain; charset=UTF-8
```

**Expected behavior**
Expected to receive a Content-Type header consistent with the format chosen for the query - `text/csv` for CSV, `text/tab-separated-values` for TSV, `application/json` for JSON.

**Comment by den-crane** [comment]
Also I suspect that in this case CH returns HTTP 200 instead of HTTP 500 even for completely incorrect query.

**Comment by kaspergrubbe** [comment]
Is this still an issue?

**Comment by czlee** [comment]
> Is this still an issue?

We're on 22.9.7.34 now, and the MREs that @anselmodadams provided above no longer reproduce. We had a workaround monkey-patch in our Ruby on Rails project (that disabled the option) so we wouldn't have noticed. But we'll see if we can try removing it to see what happens for us.

**Comment by czlee** [comment]
Update:
- still reproducible using steps in OP above on 22.3.3, 22.5.4.19 (ARM images)
- not reproducible on 22.6.9.11, 22.8.13.20 (ARM images)

However, on production we're running Altinity's image (`altinity/clickhouse-server:22.8.13.21.altinitystable`, AMD) and it's still reproducible there. This could be an AMD vs ARM thing or something else—will follow up with Altinity. In the meantime I'm of course leaving our monkey-patch in.

Note: My images don't have `curl` on them, I think because I'm using the alpine ones (e.g. `clickhouse/clickhouse-server:22.6.9.11-alpine`), but they do have `wget`, so I was using this command (based on the one in the OP):
```
(seq 1 1000 | xargs -n1 -P0 -Ixxx wget -S -O /tmp/ch-http-test "http://localhost:8123/?http_headers_progress_interval_ms=1&send_progress_in_http_headers=true&query=select+sleepEachRow(0.01)from+numbers(10)+FORMAT+CSV" 2>&1 | grep -Eo " Content-Type:.*$") | sort | uniq -c
```
(note this writes a file `/tmp/ch-http-test`)

**Comment by den-crane** [comment]
still reproducible issue

```
ClickHouse client version 23.7.1.2470 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 23.7.1 revision 54464.


(seq 1 1000| xargs -n1 -P0 -Ixxx curl -v "http://localhost:8123/?http_headers_progress_interval_ms=1&send_progress_in_http_headers=true&query=select+sleepEachRow(0.01)from+numbers(10)+FORMAT+CSV" 2>&1|grep -Eo " Content-Type:.*$")|sort | uniq -c
    396  Content-Type: text/csv; charset=UTF-8; header=absent
    279  Content-Type: text/plain; charset=UTF-8

 (seq 1 1000| xargs -n1 -P0 -Ixxx curl -v "http://localhost:8123/?http_headers_progress_interval_ms=1&send_progress_in_http_headers=true&query=select+sleepEachRow(0.01)from+numbers(10)" 2>&1|grep -Eo " Content-Type:.*$")|sort | uniq -c
    270  Content-Type: text/plain; charset=UTF-8
    468  Content-Type: text/tab-separated-values; charset=UTF-8

(seq 1 1000| xargs -n1 -P0 -Ixxx curl -v "http://localhost:8123/?http_headers_progress_interval_ms=1&send_progress_in_http_headers=true&query=select+sleepEachRow(0.01)from+numbers(10)+FORMAT+TSV" 2>&1|grep -Eo " Content-Type:.*$")|sort | uniq -c

    369  Content-Type: text/plain; charset=UTF-8
    391  Content-Type: text/tab-separated-values; charset=UTF-8

(seq 1 1000| xargs -n1 -P0 -Ixxx curl -v "http://localhost:8123/?http_headers_progress_interval_ms=1&send_progress_in_http_headers=true&query=select+sleepEachRow(0.01)from+numbers(10)+FORMAT+JSON" 2>&1|grep -Eo " Content-Type:.*$")|sort | uniq -c
    438  Content-Type: application/json; charset=UTF-8
    281  Content-Type: text/plain; charset=UTF-8
```

**Comment by alexey-milovidov** [comment]
> However, on production we're running Altinity's image

But we don't support Altinity builds: https://clickhouse.com/docs/knowledgebase/difference_between_official_builds_and_3rd_party

When you install a third-party build, you are on your own.

**Comment by den-crane** [comment]
Somehow it has been fixed in 23.8

```
23.8.5.16

(seq 1 1000| xargs -n1 -P0 -Ixxx curl -v "http://localhost:8123/?http_headers_progress_interval_ms=1&send_progress_in_http_headers=true&query=select+sleepEachRow(0.01)from+numbers(10)+FORMAT+CSV" 2>&1|grep -Eo " Content-Type:.*$")|sort | uniq -c
    896  Content-Type: text/csv; charset=UTF-8; header=absent

(seq 1 1000| xargs -n1 -P0 -Ixxx curl -v "http://localhost:8123/?http_headers_progress_interval_ms=1&send_progress_in_http_headers=true&query=select+sleepEachRow(0.01)from+numbers(10)+FORMAT+JSON" 2>&1|grep -Eo " Content-Type:.*$")|sort | uniq -c
    732  Content-Type: application/json; charset=UTF-8
```

**Comment by hidr0** [comment]
I still have this issue. The issue is that the ruby library click_house cannot handle parsing this 'JSON' and breaks.
This is the issue on their side https://github.com/shlima/click_house/issues/17

We are using click_house to return the raw data for an object which we will then load.
Sometimes this raw_data is long and CH tries to send it with progress.
At that point CH returns `Content-Type: text/plain; charset=UTF-8`

The `curl` manages to save the output as a JSON and everything is ok, but https://github.com/shlima/click_house cannot do that as the underlying Faraday library which makes the request does not understand that this is a JSON and needs to parse it.

I have a script which executes a request 100 times, saves the output to files and logs.

I cannot get it to reproduce all the time, but our users encounter it so it happens around 0.5% of the time. I managed to reproduce it 1 time out of 1000, but what I found out is that It rarely happens after CH has loaded the query.

In this example it happened on the 4th attempt and never in the next 300.


```
Execution #4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host XXXXXXXXX.clickhouse.cloud:443 was resolved.
* IPv6: (none)
* IPv4: 35.82.252.60, 44.226.232.172, 35.85.205.122
*   Trying 35.82.252.60:443...
* Connected to XXXXXXXXX.clickhouse.cloud (35.82.252.60) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
} [346 bytes data]
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* (304) (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* (304) (IN), TLS handshake, Unknown (8):
{ [21 bytes data]
* (304) (IN), TLS handshake, Certificate (11):
{ [2677 bytes data]
* (304) (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* (304) (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* (304) (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256 / [blank] / UNDEF
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=us-west-2.aws.clickhouse.cloud
*  start date: Nov 27 16:04:09 2024 GMT
*  expire date: Feb 25 16:04:08 2025 GMT
*  subjectAltName: host "XXXXXXXXX.clickhouse.cloud" matched cert's "*.us-west-2.aws.clickhouse.cloud"
*  issuer: C=US; O=Let's Encrypt; CN=R11
*  SSL certificate verify ok.
* using HTTP/1.x
> GET /?password=not_my_password&database=default&default_format=JSON&send_progress_in_http_headers=1 HTTP/1.1
> Host: XXXXXXXXX.clickhouse.cloud
> Accept: */*
> User-Agent: Faraday v1.10.3
> Content-Length: 456
> Content-Type: application/x-www-form-urlencoded
>
} [456 bytes data]
* upload completely sent off: 456 bytes
< HTTP/1.1 200 OK
< Date: Tue, 14 Jan 2025 12:49:54 GMT
< Connection: Keep-Alive
< Content-Type: text/plain; charset=UTF-8
< X-ClickHouse-Server-Display-Name: clickhouse-cloud
< Transfer-Encoding: chunked
< Keep-Alive: timeout=10, max=9999
< X-ClickHouse-Progress: {"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"49544","result_rows":"0","result_bytes":"0","elapsed_ns":"161235289"}
< X-ClickHouse-Progress: {"read_rows":"49544","read_bytes":"858240","written_rows":"0","written_bytes":"0","total_rows_to_read":"49544","result_rows":"0","result_bytes":"0","elapsed_ns":"333529913"}
< X-ClickHouse-Progress: {"read_rows":"120187","read_bytes":"1776599","written_rows":"0","written_bytes":"0","total_rows_to_read":"503671","result_rows":"0","result_bytes":"0","elapsed_ns":"529677768"}
100   456    0     0  100   456      0    439  0:00:01  0:00:01 --:--:--   439< X-ClickHouse-Progress: {"read_rows":"146027","read_bytes":"2112519","written_rows":"0","written_bytes":"0","total_rows_to_read":"503671","result_rows":"0","result_bytes":"0","elapsed_ns":"753026351"}
< X-ClickHouse-Progress: {"read_rows":"486007","read_bytes":"16677017","written_rows":"0","written_bytes":"0","total_rows_to_read":"503671","result_rows":"0","result_bytes":"0","elapsed_ns":"963246772"}
< X-ClickHouse-Summary: {"read_rows":"486007","read_bytes":"16677017","written_rows":"0","written_bytes":"0","total_rows_to_read":"503671","result_rows":"0","result_bytes":"0","elapsed_ns":"963570059"}
<
{ [94 bytes data]
100 20550    0 20094  100   456  12286    278  0:00:01  0:00:01 --:--:-- 12561
* Connection #0 to host XXXXXXXXX.clickhouse.cloud left intact
```

**Comment by azat** [comment]
CI also catch this - https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91992&sha=32b7e4be77cbff3470ea4230656e77c97bb91ade&name_0=PR&name_1=Stateless%20tests%20%28amd_binary%2C%20old%20analyzer%2C%20s3%20storage%2C%20DatabaseReplicated%2C%20parallel%29

**Comment by azat** [comment]
The test failure is unrelated, will be fixed in https://github.com/ClickHouse/ClickHouse/pull/92117

And I don't see any problems in the code, @hidr0 I'm going to close it, but please, if you will find a way to reproduce it stabily, feel free to reopen
