### ISSUE TITLE
TCPHandler: Code: 432. DB::Exception: Unknown codec family code

### ISSUE THREAD

**Issue by pva** [ClickHouse/ClickHouse#39324]
After upgrade 19.5.3.8 to 21.8.15.7 (here we are not sure if we had problems) and then to 22.3.6.5 (we noticed problem with this version) we see the following traces in logs:

```
2022.07.18 12:53:01.101891 [ 549313 ] {540d8d64-9b10-4859-8125-b2ba5b535438} <Error> TCPHandler: Code: 432. DB::Exception: Unknown codec family code: 51: (while reading column event_date_time): (while reading from part /var/lib/clickhouse/data/kt_client_events/playback_events/20210620_20210630_2930997_3017132_75/ from mark 4332 with max_rows_to_read = 8192): While executing MergeTreeThread. (UNKNOWN_CODEC), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb37467a in /usr/bin/clickhouse
1. DB::CompressionCodecFactory::get(unsigned char) const @ 0x15039132 in /usr/bin/clickhouse
2. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0x1502a3c3 in /usr/bin/clickhouse
3. DB::CompressedReadBufferFromFile::readBig(char*, unsigned long) @ 0x1502cba6 in /usr/bin/clickhouse
4. DB::SerializationNumber<unsigned int>::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0xb1c1dd3 in /usr/bin/clickhouse
5. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x15213675 in /usr/bin/clickhouse
6. DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >&, bool) @ 0x1642c92f in /usr/bin/clickhouse
7. DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x1642b86b in /usr/bin/clickhouse
8. DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x16bf60ce in /usr/bin/clickhouse
9. DB::MergeTreeRangeReader::startReadingChain(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x16bfac20 in /usr/bin/clickhouse
10. DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x16bf9415 in /usr/bin/clickhouse
11. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0x16beec28 in /usr/bin/clickhouse
12. DB::MergeTreeBaseSelectProcessor::readFromPart() @ 0x16befd2d in /usr/bin/clickhouse
13. DB::MergeTreeBaseSelectProcessor::generate() @ 0x16bee4a0 in /usr/bin/clickhouse
14. DB::ISource::tryGenerate() @ 0x16907995 in /usr/bin/clickhouse
15. DB::ISource::work() @ 0x1690755a in /usr/bin/clickhouse
16. DB::SourceWithProgress::work() @ 0x16b5ee82 in /usr/bin/clickhouse
17. DB::ExecutionThreadContext::executeTask() @ 0x16927ce3 in /usr/bin/clickhouse
18. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x1691b73e in /usr/bin/clickhouse
19. ? @ 0x1691d0a4 in /usr/bin/clickhouse
20. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb41bad7 in /usr/bin/clickhouse
21. ? @ 0xb41f65d in /usr/bin/clickhouse
22. ? @ 0x87887 in /lib64/libc.so.6
23. ? @ 0x10993c in /lib64/libc.so.6

```

We've tried to upgrade to a recent release, 22.3.8.39, but it didn't help.

**How to reproduce**

Currently, we don't know.

**Additional context**

Is it safe to downgrade on 19.5.3.8 or even 18.12.17 to check if problem persists on old versions?

**Comment by nickitat** [comment]
@pva do you use disk encryption?

**Comment by pva** [comment]
> @pva do you use disk encryption?

We don't use clickhouse's disk encryption. But our standard configuration assumes cryptsetup disk encryption, but I don't see how this could be related.

**Comment by pva** [comment]
@nickitat any suggestions?

**Comment by qoega** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/e01bf1318a027a688cf6451f70250a4f09393063/stateless_tests__release__databaseordinary_.html

```
2022-07-25 06:03:23 [ca42c0da7ab7] 2022.07.25 06:03:23.783994 [ 1839 ] {15df89c4-27cd-4dd5-9588-28d5c26973a9}  executeQuery: Code: 432. DB::Exception: Unknown codec family code: 0: while reading column number at /var/lib/clickhouse/data/test_o09cvz/local_01099_b/: While executing Log. (UNKNOWN_CODEC) (version 22.8.1.219 (official build)) (from [::1]:45730) (comment: 02221_parallel_replicas_bug.sh) (in query: SELECT number, count(number) FROM local_01099_b group by number order by number;), Stack trace (when copying this message, always include the lines below):
2022-07-25 06:03:23 
2022-07-25 06:03:23 0. DB::Exception::Exception(std::__1::basic_string, std::__1::allocator > const&, int, bool) @ 0xba3361a in /usr/bin/clickhouse
2022-07-25 06:03:23 1. DB::CompressionCodecFactory::get(unsigned char) const @ 0x15f68693 in /usr/bin/clickhouse
2022-07-25 06:03:23 2. ? @ 0x15f59575 in /usr/bin/clickhouse
2022-07-25 06:03:23 3. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0x15f592fc in /usr/bin/clickhouse
2022-07-25 06:03:23 4. DB::CompressedReadBuffer::readBig(char*, unsigned long) @ 0x15f58c84 in /usr/bin/clickhouse
2022-07-25 06:03:23 5. DB::SerializationNumber::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0xb85cd92 in /usr/bin/clickhouse
2022-07-25 06:03:23 6. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW::immutable_ptr&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr&, std::__1::unordered_map, std::__1::allocator >, COW::immutable_ptr, std::__1::hash, std::__1::allocator > >, std::__1::equal_to, std::__1::allocator > >, std::__1::allocator, std::__1::allocator > const, COW::immutable_ptr > > >*) const @ 0x16114996 in /usr/bin/clickhouse
2022-07-25 06:03:23 7. DB::LogSource::readData(DB::NameAndTypePair const&, COW::immutable_ptr&, unsigned long, std::__1::unordered_map, std::__1::allocator >, COW::immutable_ptr, std::__1::hash, std::__1::allocator > >, std::__1::equal_to, std::__1::allocator > >, std::__1::allocator, std::__1::allocator > const, COW::immutable_ptr > > >&) @ 0x173acd38 in /usr/bin/clickhouse
2022-07-25 06:03:23 8. DB::LogSource::generate() @ 0x173abc87 in /usr/bin/clickhouse
2022-07-25 06:03:23 9. DB::ISource::tryGenerate() @ 0x17b7fbf5 in /usr/bin/clickhouse
2022-07-25 06:03:23 10. DB::ISource::work() @ 0x17b7f746 in /usr/bin/clickhouse
2022-07-25 06:03:23 11. DB::ExecutionThreadContext::executeTask() @ 0x17b9bf6a in /usr/bin/clickhouse
2022-07-25 06:03:23 12. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic*) @ 0x17b90e50 in /usr/bin/clickhouse
2022-07-25 06:03:23 13. ? @ 0x17b92621 in /usr/bin/clickhouse
2022-07-25 06:03:23 14. ThreadPoolImpl::worker(std::__1::__list_iterator) @ 0xbaffee8 in /usr/bin/clickhouse
2022-07-25 06:03:23 15. ? @ 0xbb0327d in /usr/bin/clickhouse
2022-07-25 06:03:23 16. ? @ 0x7f14c2978609 in ?
2022-07-25 06:03:23 17. clone @ 0x7f14c289d133 in ?
2022-07-25 06:03:23 
2022-07-25 06:03:23 Received exception from server (version 22.8.1):
2022-07-25 06:03:23 Code: 432. DB::Exception: Received from localhost:9000. DB::Exception: Unknown codec family code: 0: while reading column number at /var/lib/clickhouse/data/test_o09cvz/local_01099_b/: While executing Log. (UNKNOWN_CODEC)
2022-07-25 06:03:23 (query: SELECT number, count(number) FROM local_01099_b group by number order by number;)
2022-07-25 06:03:23 , result:
2022-07-25 06:03:23 
2022-07-25 06:03:23 
2022-07-25 06:03:23 
2022-07-25 06:03:23 stdout:
2022-07-25 06:03:23 
2022-07-25 06:03:23 
2022-07-25 06:03:23 Settings used in the test: --max_insert_threads=0 --group_by_two_level_threshold=100000 --group_by_two_level_threshold_bytes=50000000 --distributed_aggregation_memory_efficient=0 --fsync_metadata=1 --output_format_parallel_formatting=0 --input_format_parallel_parsing=1 --min_chunk_bytes_for_parallel_parsing=976397 --max_read_buffer_size=523856 --prefer_localhost_replica=0 --max_block_size=40307 --max_threads=26 --optimize_or_like_chain=0 --optimize_read_in_order=1 --read_in_order_two_level_merge_threshold=52 --optimize_aggregation_in_order=0 --aggregation_in_order_max_block_bytes=49023966 --use_uncompressed_cache=0 --min_bytes_to_use_direct_io=1 --min_bytes_to_use_mmap_io=1 --local_filesystem_read_method=mmap --remote_filesystem_read_method=threadpool --local_filesystem_read_prefetch=1 --remote_filesystem_read_prefetch=0 --compile_expressions=1 --compile_aggregate_expressions=0 --compile_sort_description=1 --merge_tree_coarse_index_granularity=25
2022-07-25 06:03:23 
2022-07-25 06:03:23 Database: test_o09cvz
```

**Comment by pva** [comment]
Hi, could you suggest any workaround for this issue? This affects not critical service but still, we would like to fix that in our infrastructure.

**Comment by nickitat** [comment]
@pva I think it is fixed in #39114 and soon we will have a release for 22.3 with this fix
in the meantime you can try the latest build from master

**Comment by nickitat** [comment]
@pva pls, check v22.3.10.22-stable

**Comment by pva** [comment]
So, I've installed 22.3.10.22 but I still have this problem:

```
2022.08.17 12:08:01.136912 [ 845353 ] {d01d3d6c-4d19-4661-a242-25d07a7023f3} <Error> TCPHandler: Code: 432. DB::Exception: Unknown codec family code: 51: (while reading column event_date_time): (while reading from part /var/lib/clickhouse/data/kt_client_events/playback_events/20210620_20210630_2930997_3017132_75/ from mark 4332 with max_rows_to_read = 8192): While executing MergeTreeThread. (UNKNOWN_CODEC), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb37453a in /usr/bin/clickhouse
1. DB::CompressionCodecFactory::get(unsigned char) const @ 0x15036812 in /usr/bin/clickhouse
2. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0x15027aa3 in /usr/bin/clickhouse
3. DB::CompressedReadBufferFromFile::readBig(char*, unsigned long) @ 0x1502a286 in /usr/bin/clickhouse
4. DB::SerializationNumber<unsigned int>::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0xb1c1c93 in /usr/bin/clickhouse
5. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x15210d55 in /usr/bin/clickhouse
6. DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >&, bool) @ 0x1642a06f in /usr/bin/clickhouse
7. DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x16428fab in /usr/bin/clickhouse
8. DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x16bf390e in /usr/bin/clickhouse
9. DB::MergeTreeRangeReader::startReadingChain(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x16bf8460 in /usr/bin/clickhouse
10. DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x16bf6c55 in /usr/bin/clickhouse
11. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0x16bec468 in /usr/bin/clickhouse
12. DB::MergeTreeBaseSelectProcessor::readFromPart() @ 0x16bed56d in /usr/bin/clickhouse
13. DB::MergeTreeBaseSelectProcessor::generate() @ 0x16bebce0 in /usr/bin/clickhouse
14. DB::ISource::tryGenerate() @ 0x16905175 in /usr/bin/clickhouse
15. DB::ISource::work() @ 0x16904d3a in /usr/bin/clickhouse
16. DB::SourceWithProgress::work() @ 0x16b5c6c2 in /usr/bin/clickhouse
17. DB::ExecutionThreadContext::executeTask() @ 0x169254c3 in /usr/bin/clickhouse
18. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x16918f1e in /usr/bin/clickhouse
19. ? @ 0x1691a884 in /usr/bin/clickhouse
20. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb419317 in /usr/bin/clickhouse
21. ? @ 0xb41ce9d in /usr/bin/clickhouse
22. ? @ 0x87887 in /lib64/libc.so.6
23. ? @ 0x10993c in /lib64/libc.so.6
```

@nickitat Is there anything I can do to help to debug this issue?

**Comment by pva** [comment]
@nickitat any suggestions?

**Comment by nickitat** [comment]
could you pls share the broken part?

**Comment by pva** [comment]
@nickitat It's large but here it is:

https://drive.google.com/file/d/1so-HNjs55HBr9hOgKoBy4HIRJfgFflWt/view?usp=sharing

That's tar.xz for that folder.

**Comment by nickitat** [comment]
> @nickitat It's large but here it is:
> 
> https://drive.google.com/file/d/1so-HNjs55HBr9hOgKoBy4HIRJfgFflWt/view?usp=sharing
> 
> That's tar.xz for that folder.

could you pls share also the table definition.

**Comment by nickitat** [comment]
@pva thank you for your patience. I checked your data locally on a recent as well as an old CH version and everything looks like the part is indeed corrupted.
to protect yourself from such problems pls use either backups or replicated tables (if you are not doing this already).

**Comment by pva** [comment]
@nickitat can't imagine how this happened, but ok. Could you tell me if is it possible to remove this partition and lose some data while keeping everything else? These are not critical data, but I'd like to keep most recent updates for this table.

**Comment by nickitat** [comment]
> @nickitat can't imagine how this happened, but ok. Could you tell me if is it possible to remove this partition and lose some data while keeping everything else? These are not critical data, but I'd like to keep most recent updates for this table.

yes, it is totally possible. you can either [detach](https://clickhouse.com/docs/en/sql-reference/statements/alter/partition/#detach-partitionpart) it or completely [drop](https://clickhouse.com/docs/en/sql-reference/statements/alter/partition/#drop-partitionpart) it.
