### ISSUE TITLE
Window view not writing data when there is a materialized view connected to it

### ISSUE THREAD

**Issue by jrdi** [ClickHouse/ClickHouse#41400]
**Describe what's wrong**

When you connect a materialized view to the output table of a window view, inserts get processed but are silently failing.

**Does it reproduce on recent release?**

It's happening in master and 22.8

**How to reproduce**

* Restart CH server
* Create a file `window-view.sql` with the following content:

```sql
set allow_experimental_window_view = 1;

DROP DATABASE IF EXISTS wv;
CREATE DATABASE wv;

CREATE TABLE wv.landing ( `timestamp` DateTime, `qty` UInt64) ENGINE = Memory;
CREATE TABLE wv.ds_winview ( `snapshot_id` DateTime, `c` UInt64) ENGINE = MergeTree ORDER BY tuple();
CREATE TABLE wv.ds_matview ( `snapshot_id` DateTime) ENGINE = MergeTree ORDER BY tuple();

CREATE WINDOW VIEW wv.winview TO wv.ds_winview as
select tumbleStart(w_id) as snapshot_id, count() c
from wv.landing group by tumble(timestamp, INTERVAL '10' SECOND) as w_id;

CREATE MATERIALIZED VIEW wv.matview TO wv.ds_matview as
select snapshot_id
from wv.ds_winview;

SELECT '-- Ingest first snapshot';
INSERT INTO wv.landing VALUES(now(),15);
INSERT INTO wv.landing VALUES(now(),15);
INSERT INTO wv.landing VALUES(now(),15);
INSERT INTO wv.landing VALUES(now(),15);

SELECT sleepEachRow(3) FROM numbers(5) FORMAT Null;

SELECT '-- Ingest second snapshot';
INSERT INTO wv.landing VALUES(now(),15);
INSERT INTO wv.landing VALUES(now(),15);
INSERT INTO wv.landing VALUES(now(),15);

SELECT sleepEachRow(3) FROM numbers(5) FORMAT Null;

SELECT '-- Window view data';
SELECT * FROM wv.ds_winview
ORDER BY snapshot_id
FORMAT PrettyCompact;

SELECT '-- Mat view data';
SELECT * FROM wv.ds_matview
ORDER BY snapshot_id
FORMAT PrettyCompact;

SELECT '-- Check errors log';
select * from system.errors
FORMAT PrettyCompact;
```

* Run it with `cat window-view.sql | ./master/clickhouse client -mn`

The output will be something like:

```bash
-- Ingest first snapshot
-- Ingest second snapshot
-- Window view data
-- Mat view data
-- Check errors log
┌─name──────────────┬─code─┬─value─┬─────last_error_time─┬─last_error_message─────────────────────────────┬─last_error_trace─┬─remote─┐
│ THERE_IS_NO_QUERY │  393 │     2 │ 2022-09-15 19:15:10 │ There is no query or query context has expired │ []               │      0 │
└───────────────────┴──────┴───────┴─────────────────────┴────────────────────────────────────────────────┴──────────────────┴────────┘
```

There are no errors in `query_log` or `query_views_log`, everything seems fine and properly processed but data doesn't get stored in `ds_winview` nor `ds_matview`.

If you run the same sql but skipping the creation of the materialized view, everything works as expected:

```sql
❯ cat window-view.sql | ./master/clickhouse client -h clickhouse-01 -mn
-- Ingest first snapshot
-- Ingest second snapshot
-- Window view data
┌─────────snapshot_id─┬─c─┐
│ 2022-09-16 07:29:40 │ 4 │
└─────────────────────┴───┘
┌─────────snapshot_id─┬─c─┐
│ 2022-09-16 07:29:50 │ 3 │
└─────────────────────┴───┘
-- Mat view data. <--- Expected to be empty since materialized view is not created
-- Check errors log
```

**Expected behavior**

I'd expect either the full process to work as expected and data being propagated through both window view and materialized view. Or to not be able to attach a materialized view to a window view, hence an error is triggered on insert time.

**Error message and/or stacktrace**

The only error message I've managed to find is:

```
2022.09.15 19:15:10.018351 [ 6025903 ] {} <Error> void DB::StorageWindowView::threadFuncFireProc(): Code: 393. DB::Exception: There is no query or query context has expired. (THERE_IS_NO_QUERY), Stack trace (when copying this message, always include the lines below):

<Empty trace>
 (version 22.9.1.1)
```
**Additional context**

**Comment by Palooz** [comment]
Just want to confirm that I'm also experiencing this.
In my case I have two well formed window views, and "chaining" then leads to this same outcome.
Some logs:
```
2023.03.13 15:18:37.402799 [ 2908462 ] {} <Error> void DB::StorageWindowView::threadFuncFireEvent(): Code: 393. DB::Exception: There is no query or query context has expired. (THERE_IS_NO_QUERY), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe0c86b5 in /usr/bin/clickhouse
1. ? @ 0x89659d6 in /usr/bin/clickhouse
2. DB::Context::getQueryContext() const @ 0x12bc8695 in /usr/bin/clickhouse
3. DB::buildPushingToViewsChain(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::shared_ptr<DB::ThreadStatusesHolder>, std::__1::atomic<unsigned long>*, DB::Block const&) @ 0x149d9f88 in /usr/bin/clickhouse
4. DB::InterpreterInsertQuery::buildChainImpl(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::Block const&, std::__1::shared_ptr<DB::ThreadStatusesHolder>, std::__1::atomic<unsigned long>*) @ 0x135a45b7 in /usr/bin/clickhouse
5. DB::InterpreterInsertQuery::execute() @ 0x135a9086 in /usr/bin/clickhouse
6. ? @ 0x145e0c36 in /usr/bin/clickhouse
7. DB::StorageWindowView::threadFuncFireEvent() @ 0x145e283a in /usr/bin/clickhouse
8. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x126693a6 in /usr/bin/clickhouse
9. DB::BackgroundSchedulePool::threadFunction() @ 0x1266c3aa in /usr/bin/clickhouse
10. ? @ 0x1266d1ec in /usr/bin/clickhouse
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe196e6a in /usr/bin/clickhouse
12. ? @ 0xe19c521 in /usr/bin/clickhouse
13. ? @ 0x7f3c6362a802 in ?
14. ? @ 0x7f3c635ca450 in ?
 (version 23.2.4.12 (official build))
```

**Comment by jrdi** [comment]
Fixed in PR https://github.com/ClickHouse/ClickHouse/pull/40807

**Comment by jrdi** [comment]
@Palooz this is fixed in master. Release 23.2.4.12 (and any minor release) only gets the backported changes, so the fix will be released this month on release 23.3

**Comment by Palooz** [comment]
Oh sweet, thanks for the clarification!

**Comment by VitaliiBorodii** [comment]
I can still reproduce this issue by following steps in the description.
Though the error is different this time:
```
2024.01.11 13:50:00.005545 [ 61 ] {} <Error> void DB::StorageWindowView::threadFuncFireProc(): Code: 49. DB::Exception: Global context cannot have query factories info. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000bf01a64 in /usr/bin/clickhouse
1. ? @ 0x0000000007fac928 in /usr/bin/clickhouse
2. DB::Context::addQueryFactoriesInfo(DB::Context::QueryLogFactories, String const&) const @ 0x00000000101b88fc in /usr/bin/clickhouse
3. DB::FunctionFactory::tryGetImpl(String const&, std::shared_ptr<DB::Context const>) const @ 0x000000000fa2ca70 in /usr/bin/clickhouse
4. DB::FunctionFactory::getImpl(String const&, std::shared_ptr<DB::Context const>) const @ 0x000000000fa2c5dc in /usr/bin/clickhouse
5. DB::addMissingDefaults(DB::Block const&, DB::NamesAndTypesList const&, DB::ColumnsDescription const&, std::shared_ptr<DB::Context const>, bool) @ 0x0000000010d1fe4c in /usr/bin/clickhouse
6. DB::InterpreterInsertQuery::buildPreSinkChain(DB::Block const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::Block const&, std::shared_ptr<DB::ThreadStatusesHolder>) @ 0x00000000109dfb70 in /usr/bin/clickhouse
7. DB::InterpreterInsertQuery::buildChain(std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::ThreadStatusesHolder>, std::atomic<unsigned long>*) @ 0x00000000109dec80 in /usr/bin/clickhouse
8. DB::buildPushingToViewsChain(std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, std::shared_ptr<DB::IAST> const&, bool, std::shared_ptr<DB::ThreadStatusesHolder>, std::shared_ptr<DB::ThreadGroup>, std::atomic<unsigned long>*, bool, DB::Block const&) @ 0x0000000011baed0c in /usr/bin/clickhouse
9. DB::InterpreterInsertQuery::buildSink(std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::ThreadStatusesHolder>, std::shared_ptr<DB::ThreadGroup>, std::atomic<unsigned long>*) @ 0x00000000109df4c8 in /usr/bin/clickhouse
10. DB::InterpreterInsertQuery::execute() @ 0x00000000109e260c in /usr/bin/clickhouse
11. ? @ 0x000000001181d354 in /usr/bin/clickhouse
12. DB::StorageWindowView::threadFuncFireProc() @ 0x000000001181bf68 in /usr/bin/clickhouse
13. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x000000000fc6485c in /usr/bin/clickhouse
14. DB::BackgroundSchedulePool::threadFunction() @ 0x000000000fc67a5c in /usr/bin/clickhouse
15. ? @ 0x000000000fc687d8 in /usr/bin/clickhouse
16. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000bfbe424 in /usr/bin/clickhouse
17. ? @ 0x000000000bfc3568 in /usr/bin/clickhouse
18. start_thread @ 0x0000000000007624 in /lib/libpthread.so.0
19. ? @ 0x00000000000d149c in /lib/libc.so.6
 (version 23.5.5.92 (official build))
```

Error disappears when remove _wv.matview_.
But once MATERIALIZED VIEW is added on top of WINDOW VIEW output table - both _wv.winview_ and _wv.matview_ stop writing any data to their respective output tables.

I would appreciate if someone check this issue once more.
