### ISSUE TITLE
Keeper startup behaviour.

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#41421]
(tested on 22.9)

Apache Zookeeper service starts and waits for peers (quorum). It waits forever and does not serve clients requests.

Clickhouse-keeper has another behaviour. It creates a lot of hustle, you need to start all keeper nodes around the same time over wise  the first node shuts down while you start the second node. 

Another problem with embedded keeper. 

Imagine you have TWO nodes of Clickhouse with embedded keeper (both). It works fine despite only two nodes.
And if one node is missing another node became read-only and this is expected and this node continues to serve SELECT queries without issues indefinitely. 
BUT if try to restart this node -- it's impossible because Clickhouse does not start because of embedded keeper and after the timeout embedded keeper shuts down the instance. 
If the keeper is not embedded then this single Clickhouse will start and will continue to serve selects.

It's inconsistent behaviour -- Clickhouse serves select requests normally but restart breaks it.

It would be nice to implement into zookeeper behaviour, Clickhouse-keeper process starts and waits for RAFT quorum indefinitely and does not server client's requests if no quorum.

**Comment by alexey-milovidov** [comment]
Isn't it fixed by #40991?

**Comment by Slach** [comment]
> It waits forever and does not serve clients requests until get the quorum.

`ruok` and `mntr` commands can be handled before ZK quorum achieved

**Comment by den-crane** [comment]
> Isn't it fixed by #40991?

AFAIK it's not. Keeper will crash CH instance after the timeout.

**Comment by alexey-milovidov** [comment]
This is sad. Keeper should not make ClickHouse inaccessible.

**Comment by antonio2368** [comment]
#40991 should fix it, it's not merged because ReplicatedAccessStorage cannot start without an active ZK connection.
Other things using ZK will correctly start and try to reconnect in the background.
This wait was added for embedded Keeper probably to avoid race. Before ReplicatedMergeTree didn't start also without active ZK (changed by https://github.com/ClickHouse/ClickHouse/pull/40148) so if an RMT table was trying to start before embedded Keeper managed to get quorum the CH would crash either way.

ReplicatedAccessStorage should handle this case correctly with https://github.com/ClickHouse/ClickHouse/pull/39977 changes after which I can change the Keeper start to async.

Also, standalone Keeper should have the wanted behaviour already.

**Comment by den-crane** [comment]
I downloaded master https://s3.amazonaws.com/clickhouse-builds/40991/6798b500e9e05cdfbc22ac86830833248890e8df/clickhouse_build_check/report.html

The issue still not solved. Clickhouse with embedded keeper is unable to start without RAFT

https://pastila.nl/?001c5a5c/b24afccc4ff3d073ea957391916dfe9e

There is a chance though that I downloaded the wrong build.

**Comment by den-crane** [comment]
Ah, I see, need to wait longer. 

```
2022.09.27 13:30:48.691129 [ 24771 ] {} <Information> Application: Will watch for the process with pid 24772

2022.09.27 13:30:48.937791 [ 24772 ] {} <Debug> KeeperDispatcher: Server initialized, waiting for quorum
2022.09.27 13:33:48.937896 [ 24772 ] {} <Debug> KeeperDispatcher: Quorum initialized
2022.09.27 13:33:48.938048 [ 24881 ] {} <Information> KeeperDispatcher: Server still not initialized, will not apply configuration until initialization finished
2022.09.27 13:33:48.938222 [ 24772 ] {} <Debug> KeeperDispatcher: Dispatcher initialized
2022.09.27 13:33:48.938323 [ 24772 ] {} <Information> Application: Listening for Keeper (tcp): [::]:2181
2022.09.27 13:33:48.939810 [ 24772 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/users.xml'
2022.09.27 13:33:48.941431 [ 24772 ] {} <Debug> ConfigReloader: Loaded config '/etc/clickhouse-server/users.xml', performing update on configuration
2022.09.27 13:33:48.941851 [ 24772 ] {} <Debug> ConfigReloader: Loaded config '/etc/clickhouse-server/users.xml', performed update on configuration

```

**Comment by antonio2368** [comment]
You can control it with `startup_timeout` in `keeper_server. coordination_settings` (default is 3 minutes)

It is added to give some time to the Keeper to get quorum so that ZK dependant parts can use it instantly.
