### ISSUE TITLE
Block structure mismatch in (columns with identical name must have identical structure) stream: different columns  after upgrade to Vesion 22.8

### ISSUE THREAD

**Issue by bigdata-spec** [ClickHouse/ClickHouse#42553]
Hello，My Clickhouse Version is **22.8.1.2097**
```
CREATE VIEW analysis_ads.ads_api_pub_rds_vin_fail
(
    `brand_name` String,
    `vehicle_model_name` String,
    `vin` String,
    `event_date` UInt32,
    `model_device_name` String,
    `fail_level` String,
    `fail_desc` String,
    `fail_cnt` Int64,
    `vi_type` String
) AS
SELECT
    '小汽车' AS brand_name,
    'Es-00' AS vehicle_model_name,
    vin,
    event_date,
   fail_level,
    fail_desc,
    fail_cnt,
    '员工车' AS vi_type
FROM analysis_ads.ads_rpt_pub_rds_vin_fail_stat_new_h；
```

then query   select * from zone_analysis_ads.ads_api_pub_rds_vin_fail  is ok
but
select * from zone_analysis_ads.ads_api_pub_rds_vin_fail  where brand_name=‘小汽车’ is error
**DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different columns:
brand_name String String(size = 0)
brand_name String Const(size = 0, String(size = 1)). (AMBIGUOUS_COLUMN_NAME)**
is this a bug？

**Comment by melvynator** [comment]
Hello @jiangbiao910 what was the ClickHouse version you upgraded from?

**Comment by jiangbiao910** [comment]
@melvynator From 21.8

**Comment by nickitat** [comment]
should be fixed by https://github.com/ClickHouse/ClickHouse/pull/48303
if not pls reopen

**Comment by Jack1007** [comment]
The bug is still exist in 22.8.21.38，hope to be fix at next minor vertion of 22.8 lts.
Reproductive sql:
CREATE VIEW a AS
SELECT 'a' AS id;

CREATE VIEW b AS
SELECT
    'a' AS id,
    'b' as other
;

SELECT *
FROM b
WHERE id IN (SELECT id FROM a);

**Comment by den-crane** [comment]
22.8 is end of life.

query works with 23.8 LTS https://fiddle.clickhouse.com/71972f8d-9804-46f4-b99e-93c71a5bd667
but not with 23.3 LTS https://fiddle.clickhouse.com/77cde032-8e7d-43bc-9454-e1acebdca5c5

**Comment by Jack1007** [comment]
> 22.8 is end of life.
> 
> query works with 23.8 LTS https://fiddle.clickhouse.com/71972f8d-9804-46f4-b99e-93c71a5bd667 but not with 23.3 LTS https://fiddle.clickhouse.com/77cde032-8e7d-43bc-9454-e1acebdca5c5

Thank you for your reply. If 22.8 is not longer be supported, do you have plan to fixed it at next version of 23.3 lts?
