### ISSUE TITLE
Deadlock in ReplicatedMergeTreeQueue/MergeTreeBackgroundExecutor when waiting for concurrently executing entry

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#43816]
**Describe what's wrong**

ClickHouse start part merge, but never finish it.

```
SELECT
    database,
    table,
    elapsed,
    progress,
    thread_id
FROM system.merges

Query id: 6da25629-949b-4db4-ba12-0f629b6af437

┌─database──┬─table───────┬────────elapsed─┬───────────progress─┬─thread_id─┐
│ tableeeee │ tble        │ 1984.107271537 │ 0.1439376716042042 │        23 │
│ system    │ part_log    │ 1982.920540095 │                  1 │        19 │
│ tableeeee │ tble        │ 1971.388698535 │                  0 │        24 │
│ tableeeee │ tble        │ 1960.049650104 │                  0 │        30 │
│ tableeeee │ tble        │ 1952.297588147 │                  0 │        23 │
│ tableeeee │ tble        │ 1921.063860018 │                  0 │        25 │
└───────────┴─────────────┴────────────────┴────────────────────┴───────────┘

SELECT
    arrayStringConcat(arrayMap(x -> demangle(addressToSymbol(x)), trace), '\n') AS trace_functions,
    count()
FROM system.stack_trace
WHERE thread_name LIKE '%Merge%'
GROUP BY trace_functions

Query id: 42a3c732-a820-41bb-9fd3-f43ce40b6bb7

┌─trace_functions────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─count()─┐
│ pthread_cond_wait
DB::ReplicatedMergeTreeQueue::CurrentlyExecuting::setActualPartName(DB::ReplicatedMergeTreeLogEntry&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ReplicatedMergeTreeQueue&, std::__1::unique_lock<std::__1::mutex>&, std::__1::vector<std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>, std::__1::allocator<std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry> > >&)
DB::ReplicatedMergeTreeQueue::addFuturePartIfNotCoveredByThem(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ReplicatedMergeTreeLogEntry&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)
DB::StorageReplicatedMergeTree::findReplicaHavingCoveringPart(DB::ReplicatedMergeTreeLogEntry&, bool)
DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&, bool)
DB::ReplicatedMergeMutateTaskBase::executeImpl()
DB::ReplicatedMergeMutateTaskBase::executeStep()
DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>)
DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction()
ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>)
void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*)
ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)


__clone │      16 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────┘
```

**Does it reproduce on recent release?**

Yes, 22.8

**Error message and/or stacktrace**

```
pthread_cond_wait
DB::ReplicatedMergeTreeQueue::CurrentlyExecuting::setActualPartName(DB::ReplicatedMergeTreeLogEntry&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ReplicatedMergeTreeQueue&, std::__1::unique_lock<std::__1::mutex>&, std::__1::vector<std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>, std::__1::allocator<std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry> > >&)
DB::ReplicatedMergeTreeQueue::addFuturePartIfNotCoveredByThem(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ReplicatedMergeTreeLogEntry&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)
DB::StorageReplicatedMergeTree::findReplicaHavingCoveringPart(DB::ReplicatedMergeTreeLogEntry&, bool)
DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&, bool)
DB::ReplicatedMergeMutateTaskBase::executeImpl()
DB::ReplicatedMergeMutateTaskBase::executeStep()
DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>)
DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction()
ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>)
void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*)
ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)


__clone
```

**Additional context**

Servers have pretty high load, and frequently hit fetch pool size limit, so merges wait for part fetches

```
Not executing log entry queue-0056313716 for part 202248_1103896_1103913_4 because it is not disjoint with part 202248_1103896_1103908_3 that is currently executing.
```

But part `202248_1103896_1103908_3` fetch was completed over hour ago.

Probably related change in 22.7  https://github.com/ClickHouse/ClickHouse/commit/6ddfec47d2a71bc4d33c6a128f5dc254f972f95a

**Comment by alexey-milovidov** [comment]
Do you use the official build or an alternative build?
What is the full version name (with patch number)?

**Comment by chbota** [comment]
We've seen this on the official 22.8.9.24 build

**Comment by tavplubix** [comment]
Please share stacktraces of **all** threads and `select * from system.replication_queue format Vertical`

**Comment by chbota** [comment]
We saw this again this morning.

Here are the stack traces: https://gist.github.com/chbota/2baa17b3c9f7918fea69b403af6a4d48

There are 41k entries in system.replication_queue - is there something more specific we can send?

**Comment by tavplubix** [comment]
`select * from system.replication_queue where is_currently_executing format Vertical`

**Comment by UnamedRus** [comment]
```
SELECT *

FROM system.replication_queue
WHERE is_currently_executing

Query id: ea942925-7c8c-4f40-9ebf-fc3bc8cbc503

┌─database──┬─table────────────┬─replica_name──────────────────────────┬─position─┬─node_name────────┬─type────────┬─────────create_time─┬─required_quorum─┬─source_replica────────────────────────┬─new_part_name─────────────┬─parts_to_merge─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─is_detach─┬─is_currently_executing─┬─num_tries─┬─last_exception─┬───last_attempt_time─┬─num_postponed─┬─postpone_reason──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──last_postpone_time─┬─merge_type─┐
│ databasee │ tbl1             │ chi-databasee-prod-databasee-prod-1-1 │       26 │ queue-0056313560 │ MERGE_PARTS │ 2022-11-29 18:54:19 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ 202248_1103749_1103784_4  │ ['202248_1103749_1103778_3','202248_1103779_1103779_0','202248_1103780_1103780_0','202248_1103781_1103781_0','202248_1103782_1103782_0','202248_1103783_1103783_0','202248_1103784_1103784_0']                                                             │         0 │                      1 │         1 │                │ 2022-11-29 18:54:23 │            43 │ Not executing log entry queue-0056313560 for part 202248_1103749_1103784_4 because it is not disjoint with part 202248_1103749_1103778_3 that is currently executing.                │ 2022-11-29 18:54:23 │ Regular    │
│ databasee │ tbl1             │ chi-databasee-prod-databasee-prod-1-1 │       29 │ queue-0056313568 │ MERGE_PARTS │ 2022-11-29 18:54:21 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ 202248_1103785_1103793_2  │ ['202248_1103785_1103789_1','202248_1103790_1103790_0','202248_1103791_1103791_0','202248_1103792_1103792_0','202248_1103793_1103793_0']                                                                                                                   │         0 │                      1 │         1 │                │ 2022-11-29 18:54:25 │           102 │ Not executing log entry queue-0056313568 for part 202248_1103785_1103793_2 because it is not disjoint with part 202248_1103792_1103792_0 that is currently executing.                │ 2022-11-29 18:54:25 │ Regular    │
│ databasee │ tbl1             │ chi-databasee-prod-databasee-prod-1-1 │       31 │ queue-0056313620 │ MERGE_PARTS │ 2022-11-29 18:54:30 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ 202248_1103817_1103835_3  │ ['202248_1103817_1103826_2','202248_1103827_1103832_1','202248_1103833_1103833_0','202248_1103834_1103834_0','202248_1103835_1103835_0']                                                                                                                   │         0 │                      1 │         1 │                │ 2022-11-29 18:54:31 │            33 │ Not executing log entry queue-0056313620 for part 202248_1103817_1103835_3 because it is not disjoint with part 202248_1103817_1103826_2 that is currently executing.                │ 2022-11-29 18:54:31 │ Regular    │
│ databasee │ tbl1             │ chi-databasee-prod-databasee-prod-1-1 │       34 │ queue-0056313633 │ GET_PART    │ 2022-11-29 18:54:33 │               2 │ chi-databasee-prod-databasee-prod-1-0 │ 202248_1103847_1103847_0  │ []                                                                                                                                                                                                                                                         │         0 │                      1 │         1 │                │ 2022-11-29 18:54:34 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │            │
│ databasee │ tbl1             │ chi-databasee-prod-databasee-prod-1-1 │       36 │ queue-0056313645 │ MERGE_PARTS │ 2022-11-29 18:54:35 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ 202248_1103848_1103855_1  │ ['202248_1103848_1103848_0','202248_1103849_1103849_0','202248_1103850_1103850_0','202248_1103851_1103851_0','202248_1103852_1103852_0','202248_1103853_1103853_0','202248_1103854_1103854_0','202248_1103855_1103855_0']                                  │         0 │                      1 │         1 │                │ 2022-11-29 18:54:37 │            49 │ Not executing log entry queue-0056313645 for part 202248_1103848_1103855_1 because it is not disjoint with part 202248_1103853_1103853_0 that is currently executing.                │ 2022-11-29 18:54:37 │ Regular    │
│ databasee │ tbl1             │ chi-databasee-prod-databasee-prod-1-1 │       38 │ queue-0056313656 │ GET_PART    │ 2022-11-29 18:54:37 │               2 │ chi-databasee-prod-databasee-prod-1-0 │ 202248_1103866_1103866_0  │ []                                                                                                                                                                                                                                                         │         0 │                      1 │         1 │                │ 2022-11-29 18:54:38 │             5 │ Not executing fetch of part 202248_1103866_1103866_0 because 16 fetches already executing, max 16.                                                                                   │ 2022-11-29 18:54:38 │            │
│ databasee │ tbl1             │ chi-databasee-prod-databasee-prod-1-1 │       62 │ queue-0056313716 │ MERGE_PARTS │ 2022-11-29 18:54:45 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ 202248_1103896_1103913_4  │ ['202248_1103896_1103908_3','202248_1103909_1103909_0','202248_1103910_1103910_0','202248_1103911_1103911_0','202248_1103912_1103912_0','202248_1103913_1103913_0']                                                                                        │         0 │                      1 │         1 │                │ 2022-11-29 18:54:49 │           111 │ Not executing log entry queue-0056313716 for part 202248_1103896_1103913_4 because it is not disjoint with part 202248_1103896_1103908_3 that is currently executing.                │ 2022-11-29 18:54:49 │ Regular    │
│ databasee │ tbl1             │ chi-databasee-prod-databasee-prod-1-1 │       63 │ queue-0056313725 │ GET_PART    │ 2022-11-29 18:54:46 │               2 │ chi-databasee-prod-databasee-prod-1-2 │ 202248_1103925_1103925_0  │ []                                                                                                                                                                                                                                                         │         0 │                      1 │         1 │                │ 2022-11-29 18:54:50 │            67 │ Not executing fetch of part 202248_1103925_1103925_0 because 16 fetches already executing, max 16.                                                                                   │ 2022-11-29 18:54:50 │            │
│ databasee │ tbl1             │ chi-databasee-prod-databasee-prod-1-1 │       67 │ queue-0056241176 │ MERGE_PARTS │ 2022-11-26 13:55:28 │               0 │ chi-databasee-prod-databasee-prod-1-0 │ 202247_2836950_2837111_15 │ ['202247_2836950_2837100_14','202247_2837101_2837106_1','202247_2837107_2837107_0','202247_2837108_2837108_0','202247_2837109_2837109_0','202247_2837110_2837110_0','202247_2837111_2837111_0']                                                            │         0 │                      1 │     10564 │                │ 2022-11-29 18:55:36 │        145067 │ Not executing log entry queue-0056241176 of type MERGE_PARTS for part 202247_2836950_2837111_15 because source parts size (2.59 MiB) is greater than the current maximum (1.00 MiB). │ 2022-11-29 18:55:36 │ Regular    │
│ databasee │ tbl____________4 │ chi-databasee-prod-databasee-prod-1-1 │        0 │ queue-0001026232 │ MERGE_PARTS │ 2022-11-29 18:54:12 │               0 │ chi-databasee-prod-databasee-prod-3-2 │ all_646272_670975_12198   │ ['all_646272_670970_12197','all_670971_670975_1']                                                                                                                                                                                                          │         0 │                      1 │         1 │                │ 2022-11-29 18:54:14 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
│ databasee │ tbl_____2        │ chi-databasee-prod-databasee-prod-1-1 │       44 │ queue-0054570040 │ GET_PART    │ 2022-11-29 18:54:30 │               2 │ chi-databasee-prod-databasee-prod-1-2 │ all_40564280_40564280_0   │ []                                                                                                                                                                                                                                                         │         0 │                      1 │         1 │                │ 2022-11-29 18:54:31 │             3 │ Not executing fetch of part all_40564280_40564280_0 because 16 fetches already executing, max 16.                                                                                    │ 2022-11-29 18:54:31 │            │
│ databasee │ tbl_____2        │ chi-databasee-prod-databasee-prod-1-1 │       46 │ queue-0054570020 │ MERGE_PARTS │ 2022-11-29 18:54:27 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_40564204_40564261_10  │ ['all_40564204_40564257_9','all_40564258_40564258_0','all_40564259_40564259_0','all_40564260_40564260_0','all_40564261_40564261_0']                                                                                                                        │         0 │                      1 │         1 │                │ 2022-11-29 18:54:31 │           120 │ Not executing log entry queue-0054570020 for part all_40564204_40564261_10 because it is not disjoint with part all_40564204_40564257_9 that is currently executing.                 │ 2022-11-29 18:54:31 │ Regular    │
│ databasee │ tbl_____2        │ chi-databasee-prod-databasee-prod-1-1 │       49 │ queue-0054570053 │ GET_PART    │ 2022-11-29 18:54:34 │               2 │ chi-databasee-prod-databasee-prod-1-2 │ all_40564291_40564291_0   │ []                                                                                                                                                                                                                                                         │         0 │                      1 │         1 │                │ 2022-11-29 18:54:34 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │            │
│ databasee │ tbl_____2        │ chi-databasee-prod-databasee-prod-1-1 │       50 │ queue-0054570059 │ GET_PART    │ 2022-11-29 18:54:34 │               2 │ chi-databasee-prod-databasee-prod-1-0 │ all_40564296_40564296_0   │ []                                                                                                                                                                                                                                                         │         0 │                      1 │         1 │                │ 2022-11-29 18:54:35 │             3 │ Not executing fetch of part all_40564296_40564296_0 because 16 fetches already executing, max 16.                                                                                    │ 2022-11-29 18:54:35 │            │
│ databasee │ tbl_____2        │ chi-databasee-prod-databasee-prod-1-1 │       57 │ queue-0054570062 │ GET_PART    │ 2022-11-29 18:54:34 │               2 │ chi-databasee-prod-databasee-prod-1-2 │ all_40564300_40564300_0   │ []                                                                                                                                                                                                                                                         │         0 │                      1 │         1 │                │ 2022-11-29 18:54:36 │            10 │ Not executing fetch of part all_40564300_40564300_0 because 16 fetches already executing, max 16.                                                                                    │ 2022-11-29 18:54:36 │            │
│ databasee │ tbl_____2        │ chi-databasee-prod-databasee-prod-1-1 │       69 │ queue-0054570073 │ GET_PART    │ 2022-11-29 18:54:36 │               2 │ chi-databasee-prod-databasee-prod-1-2 │ all_40564308_40564308_0   │ []                                                                                                                                                                                                                                                         │         0 │                      1 │         1 │                │ 2022-11-29 18:54:39 │            38 │ Not executing fetch of part all_40564308_40564308_0 because 16 fetches already executing, max 16.                                                                                    │ 2022-11-29 18:54:39 │            │
│ databasee │ tbl_____2        │ chi-databasee-prod-databasee-prod-1-1 │      119 │ queue-0054570123 │ MERGE_PARTS │ 2022-11-29 18:54:44 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_40564345_40564349_1   │ ['all_40564345_40564345_0','all_40564346_40564346_0','all_40564347_40564347_0','all_40564348_40564348_0','all_40564349_40564349_0']                                                                                                                        │         0 │                      1 │         3 │                │ 2022-11-29 18:54:46 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
│ databasee │ tbl_____2        │ chi-databasee-prod-databasee-prod-1-1 │      121 │ queue-0054570138 │ MERGE_PARTS │ 2022-11-29 18:54:45 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_40564352_40564361_1   │ ['all_40564352_40564352_0','all_40564353_40564353_0','all_40564354_40564354_0','all_40564355_40564355_0','all_40564356_40564356_0','all_40564357_40564357_0','all_40564358_40564358_0','all_40564359_40564359_0','all_40564360_40564360_0','all_40564361_40564361_0'] │         0 │                      1 │        10 │                │ 2022-11-29 18:54:54 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │       31 │ queue-0050182157 │ MERGE_PARTS │ 2022-11-29 18:54:08 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_35674299_35675179_192 │ ['all_35674299_35675173_191','all_35675174_35675179_1']                                                                                                                                                                                                    │         0 │                      1 │         1 │                │ 2022-11-29 18:54:14 │            61 │ Not executing log entry queue-0050182157 for part all_35674299_35675179_192 because it is not disjoint with part all_35674299_35675173_191 that is currently executing.              │ 2022-11-29 18:54:13 │ Regular    │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │       50 │ queue-0050182230 │ MERGE_PARTS │ 2022-11-29 18:54:14 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675227_35675235_1   │ ['all_35675227_35675227_0','all_35675228_35675228_0','all_35675229_35675229_0','all_35675230_35675230_0','all_35675231_35675231_0','all_35675232_35675232_0','all_35675233_35675233_0','all_35675234_35675234_0','all_35675235_35675235_0']                │         0 │                      1 │         1 │                │ 2022-11-29 18:54:15 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │       78 │ queue-0050182252 │ MERGE_PARTS │ 2022-11-29 18:54:16 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675257_35675263_1   │ ['all_35675257_35675257_0','all_35675258_35675258_0','all_35675259_35675259_0','all_35675260_35675260_0','all_35675261_35675261_0','all_35675262_35675262_0','all_35675263_35675263_0']                                                                    │         0 │                      1 │         2 │                │ 2022-11-29 18:54:18 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │       82 │ queue-0050182257 │ GET_PART    │ 2022-11-29 18:54:17 │               2 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675269_35675269_0   │ []                                                                                                                                                                                                                                                         │         0 │                      1 │         1 │                │ 2022-11-29 18:54:20 │            29 │ Not executing fetch of part all_35675269_35675269_0 because 16 fetches already executing, max 16.                                                                                    │ 2022-11-29 18:54:20 │            │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │       88 │ queue-0050182280 │ MERGE_PARTS │ 2022-11-29 18:54:20 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675280_35675285_1   │ ['all_35675280_35675280_0','all_35675281_35675281_0','all_35675282_35675282_0','all_35675283_35675283_0','all_35675284_35675284_0','all_35675285_35675285_0']                                                                                              │         0 │                      1 │         3 │                │ 2022-11-29 18:54:21 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      109 │ queue-0050182352 │ GET_PART    │ 2022-11-29 18:54:32 │               2 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675335_35675335_0   │ []                                                                                                                                                                                                                                                         │         0 │                      1 │         1 │                │ 2022-11-29 18:54:33 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │            │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      123 │ queue-0050182369 │ GET_PART    │ 2022-11-29 18:54:34 │               2 │ chi-databasee-prod-databasee-prod-1-0 │ all_35675347_35675347_0   │ []                                                                                                                                                                                                                                                         │         0 │                      1 │         1 │                │ 2022-11-29 18:54:36 │             8 │ Not executing fetch of part all_35675347_35675347_0 because 16 fetches already executing, max 16.                                                                                    │ 2022-11-29 18:54:36 │            │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      125 │ queue-0050182377 │ GET_PART    │ 2022-11-29 18:54:35 │               2 │ chi-databasee-prod-databasee-prod-1-0 │ all_35675353_35675353_0   │ []                                                                                                                                                                                                                                                         │         0 │                      1 │         1 │                │ 2022-11-29 18:54:36 │            10 │ Not executing fetch of part all_35675353_35675353_0 because 16 fetches already executing, max 16.                                                                                    │ 2022-11-29 18:54:36 │            │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      155 │ queue-0050182398 │ GET_PART    │ 2022-11-29 18:54:38 │               2 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675366_35675366_0   │ []                                                                                                                                                                                                                                                         │         0 │                      1 │         1 │                │ 2022-11-29 18:54:41 │            37 │ Not executing fetch of part all_35675366_35675366_0 because 16 fetches already executing, max 16.                                                                                    │ 2022-11-29 18:54:41 │            │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      161 │ queue-0050182423 │ MERGE_PARTS │ 2022-11-29 18:54:40 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675376_35675382_1   │ ['all_35675376_35675376_0','all_35675377_35675377_0','all_35675378_35675378_0','all_35675379_35675379_0','all_35675380_35675380_0','all_35675381_35675381_0','all_35675382_35675382_0']                                                                    │         0 │                      1 │        14 │                │ 2022-11-29 18:54:42 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      197 │ queue-0050182448 │ MERGE_PARTS │ 2022-11-29 18:54:44 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675397_35675402_1   │ ['all_35675397_35675397_0','all_35675398_35675398_0','all_35675399_35675399_0','all_35675400_35675400_0','all_35675401_35675401_0','all_35675402_35675402_0']                                                                                              │         0 │                      1 │         8 │                │ 2022-11-29 18:54:47 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      264 │ queue-0050182497 │ MERGE_PARTS │ 2022-11-29 18:54:48 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675430_35675439_1   │ ['all_35675430_35675430_0','all_35675431_35675431_0','all_35675432_35675432_0','all_35675433_35675433_0','all_35675434_35675434_0','all_35675435_35675435_0','all_35675436_35675436_0','all_35675437_35675437_0','all_35675438_35675438_0','all_35675439_35675439_0'] │         0 │                      1 │        11 │                │ 2022-11-29 18:54:54 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      269 │ queue-0050182540 │ MERGE_PARTS │ 2022-11-29 18:54:53 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675472_35675476_1   │ ['all_35675472_35675472_0','all_35675473_35675473_0','all_35675474_35675474_0','all_35675475_35675475_0','all_35675476_35675476_0']                                                                                                                        │         0 │                      1 │         1 │                │ 2022-11-29 18:54:54 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      301 │ queue-0050182555 │ MERGE_PARTS │ 2022-11-29 18:54:55 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675483_35675490_1   │ ['all_35675483_35675483_0','all_35675484_35675484_0','all_35675485_35675485_0','all_35675486_35675486_0','all_35675487_35675487_0','all_35675488_35675488_0','all_35675489_35675489_0','all_35675490_35675490_0']                                          │         0 │                      1 │         4 │                │ 2022-11-29 18:54:59 │            12 │ Not executing log entry queue-0050182555 for part all_35675483_35675490_1 because it is not disjoint with part all_35675484_35675484_0 that is currently executing.                  │ 2022-11-29 18:54:58 │ Regular    │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      358 │ queue-0050182631 │ MERGE_PARTS │ 2022-11-29 18:55:04 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675538_35675544_1   │ ['all_35675538_35675538_0','all_35675539_35675539_0','all_35675540_35675540_0','all_35675541_35675541_0','all_35675542_35675542_0','all_35675543_35675543_0','all_35675544_35675544_0']                                                                    │         0 │                      1 │         1 │                │ 2022-11-29 18:55:06 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      380 │ queue-0050182649 │ MERGE_PARTS │ 2022-11-29 18:55:08 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675554_35675558_1   │ ['all_35675554_35675554_0','all_35675555_35675555_0','all_35675556_35675556_0','all_35675557_35675557_0','all_35675558_35675558_0']                                                                                                                        │         0 │                      1 │         3 │                │ 2022-11-29 18:55:10 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      441 │ queue-0050182721 │ MERGE_PARTS │ 2022-11-29 18:55:18 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675596_35675606_1   │ ['all_35675596_35675596_0','all_35675597_35675597_0','all_35675598_35675598_0','all_35675599_35675599_0','all_35675600_35675600_0','all_35675601_35675601_0','all_35675602_35675602_0','all_35675603_35675603_0','all_35675604_35675604_0','all_35675605_35675605_0','all_35675606_35675606_0'] │         0 │                      1 │         6 │                │ 2022-11-29 18:55:20 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      442 │ queue-0050182665 │ GET_PART    │ 2022-11-29 18:55:11 │               2 │ chi-databasee-prod-databasee-prod-1-0 │ all_35675570_35675570_0   │ []                                                                                                                                                                                                                                                         │         0 │                      1 │         1 │                │ 2022-11-29 18:55:20 │            45 │ Not executing fetch of part all_35675570_35675570_0 because 16 fetches already executing, max 16.                                                                                    │ 2022-11-29 18:55:20 │            │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      506 │ queue-0050182785 │ MERGE_PARTS │ 2022-11-29 18:55:23 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675644_35675652_1   │ ['all_35675644_35675644_0','all_35675645_35675645_0','all_35675646_35675646_0','all_35675647_35675647_0','all_35675648_35675648_0','all_35675649_35675649_0','all_35675650_35675650_0','all_35675651_35675651_0','all_35675652_35675652_0']                │         0 │                      1 │         1 │                │ 2022-11-29 18:55:26 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      560 │ queue-0050182829 │ MERGE_PARTS │ 2022-11-29 18:55:27 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675692_35675699_1   │ ['all_35675692_35675692_0','all_35675693_35675693_0','all_35675694_35675694_0','all_35675695_35675695_0','all_35675696_35675696_0','all_35675697_35675697_0','all_35675698_35675698_0','all_35675699_35675699_0']                                          │         0 │                      1 │         5 │                │ 2022-11-29 18:55:32 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      583 │ queue-0050182876 │ MERGE_PARTS │ 2022-11-29 18:55:34 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675729_35675733_1   │ ['all_35675729_35675729_0','all_35675730_35675730_0','all_35675731_35675731_0','all_35675732_35675732_0','all_35675733_35675733_0']                                                                                                                        │         0 │                      1 │         2 │                │ 2022-11-29 18:55:36 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      617 │ queue-0050182881 │ GET_PART    │ 2022-11-29 18:55:35 │               2 │ chi-databasee-prod-databasee-prod-1-2 │ all_35675737_35675737_0   │ []                                                                                                                                                                                                                                                         │         0 │                      1 │         1 │                │ 2022-11-29 18:55:42 │            16 │ Not executing fetch of part all_35675737_35675737_0 because 16 fetches already executing, max 16.                                                                                    │ 2022-11-29 18:55:41 │            │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │      757 │ queue-0050182999 │ GET_PART    │ 2022-11-29 18:55:48 │               2 │ chi-databasee-prod-databasee-prod-1-0 │ all_35675830_35675830_0   │ []                                                                                                                                                                                                                                                         │         0 │                      1 │         1 │                │ 2022-11-29 18:55:56 │            10 │ Not executing fetch of part all_35675830_35675830_0 because 16 fetches already executing, max 16.                                                                                    │ 2022-11-29 18:55:55 │            │
│ databasee │ tbl_______3      │ chi-databasee-prod-databasee-prod-1-1 │    24812 │ queue-0050200607 │ MERGE_PARTS │ 2022-11-29 19:29:45 │               0 │ chi-databasee-prod-databasee-prod-1-2 │ all_35690732_35690745_2   │ ['all_35690732_35690741_1','all_35690742_35690742_0','all_35690743_35690743_0','all_35690744_35690744_0','all_35690745_35690745_0']                                                                                                                        │         0 │                      1 │         1 │                │ 2022-11-29 19:41:46 │             0 │                                                                                                                                                                                      │ 1970-01-01 00:00:00 │ Regular    │
└───────────┴──────────────────┴───────────────────────────────────────┴──────────┴──────────────────┴─────────────┴─────────────────────┴─────────────────┴───────────────────────────────────────┴───────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────┴────────────────────────┴───────────┴────────────────┴─────────────────────┴───────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴────────────┘

```

**Comment by tavplubix** [comment]
I have an idea about what's going on. Looks like the root cause is that after https://github.com/ClickHouse/ClickHouse/pull/25165 we set `currently_executing` before we actually started to execute an entry. We set the flag in `selectQueueEntry` and then schedule the task through `BackgroundJobsAssignee`. But if the corresponding `MergeTreeBackgroundExecutor` pool is full, then this task will just wait for a free thread in the pool without making any progress. The problem is that tasks that are actually executing in the pull may wait (in `removePartProducingOpsInRange` or `setActualPartName`) for the task that is waiting for a free thread... @nikitamikhaylov, does it sound reasonable?

And it could get worse after https://github.com/ClickHouse/ClickHouse/pull/37822 and https://github.com/ClickHouse/ClickHouse/pull/39737

Workaround:  increase the pool size.

**Comment by AntonFriberg** [comment]
We are having a similar issue #44865 and we have tried to increase the pool size but it has not resolved the issue. We are running 22.12.1.1752 version. Do you have any other recommendation that could fix it or do we need to downgrade before 22.8 ?

**Comment by alexey-milovidov** [comment]
Fixed in #46309.

**Comment by tavplubix** [comment]
> Fixed in https://github.com/ClickHouse/ClickHouse/pull/46309.

Actually it's not.

**Comment by lxswbr** [comment]
> We are having a similar issue #44865 and we have tried to increase the pool size but it has not resolved the issue. We are running 22.12.1.1752 version. Do you have any other recommendation that could fix it or do we need to downgrade before 22.8 ?

Hello, will this problem exist in version 22.12.1.1752? The version 22.3.2.1 we use still exists

**Comment by alexey-milovidov** [comment]
Could you please proof it with a test case?

**Comment by puduan** [comment]
We hit the same issue w/ version 22.8.4.7 in our stress test. We changed  background_fetches_pool_size from 8 to 64, and it is stable for 24 hours, but hit the merge stuck issue again.

**Comment by batmanwjw** [comment]
@tavplubix hi, is there any new progress on this issue? We also encountered this problem in version 23.8.16.1.
We increased background_fetches_pool_size to 256，then fetch part start working, but only worked for a while, the speed was getting slower and slower, and merge is still stuck, with the same stack_trace as above.
```
2025.03.21 11:01:06.874768 [ 122602 ] {} <Debug> qubyte_poc.local_book_risk_scenario_update (8eff0e36-fbe2-48d8-9844-bcdcdf01bb7e): Fetched part 20250321_24427_27982_1147 from default:/clickhouse/tables/qubyte_poc/local_book_risk_scenario_update/s0/replicas/r0
2025.03.21 11:04:08.559683 [ 121241 ] {} <Debug> qubyte_poc.local_inst_risk_data (7829278f-015d-4157-aee1-8259b3ba8f5d): Fetched part 20250321_117471_129784_30 from default:/clickhouse/tables/qubyte_poc/local_inst_risk_data/s0/replicas/r0
2025.03.21 11:05:34.268920 [ 120974 ] {} <Debug> qubyte_poc.local_strike_view (248c76cf-5cbe-4607-80db-1a1fb2c16022): Fetched part 20250321_23636_25211_28 from default:/clickhouse/tables/qubyte_poc/local_strike_view/s0/replicas/r0
2025.03.21 11:07:29.762574 [ 122691 ] {} <Debug> qubyte_poc.local_base_offset_params (a664f7c4-1cf2-476e-acab-1833fe53a1ed): Fetched part 20250321_52958_103195_944 from default:/clickhouse/tables/qubyte_poc/local_base_offset_params/s0/replicas/r0
2025.03.21 11:08:10.430937 [ 122017 ] {} <Debug> qubyte_poc.local_fitting_output_theo (68274ea8-266a-4abc-ae0e-dccf816a640e): Fetched part 20250321_7315_8205_68 from default:/clickhouse/tables/qubyte_poc/local_fitting_output_theo/s0/replicas/r0
2025.03.21 11:13:50.454671 [ 123227 ] {} <Debug> qubyte_poc.local_posn_risk (84ffc8a0-fc60-4966-be74-e9aa2f98676e): Fetched part 20250321_27170_28166_23 from default:/clickhouse/tables/qubyte_poc/local_posn_risk/s0/replicas/r0
2025.03.21 11:18:58.508964 [ 123090 ] {} <Debug> qubyte_poc.local_position_update (2708c21e-da5e-41c6-b5d1-de5ad7da9409): Fetched part 20250321_101652_110544_136 from default:/clickhouse/tables/qubyte_poc/local_position_update/s0/replicas/r0
2025.03.21 11:25:42.148685 [ 122436 ] {} <Debug> qubyte_poc.local_exch_acct_update (0ac073f1-18f4-406a-a70a-41f52cf97981): Fetched part 20250321_42273_62039_901 from default:/clickhouse/tables/qubyte_poc/local_exch_acct_update/s0/replicas/r0
2025.03.21 11:29:20.060664 [ 123841 ] {} <Debug> qubyte_poc.ok_book_tbt_local (8152f202-8ab9-43ab-b815-5ef6d4948201): Fetched part 20250321_16441_16944_5 from default:/clickhouse/tables/qubyte_poc/ok_book_tbt_local/s0/replicas/r0
2025.03.21 11:31:02.449119 [ 123838 ] {} <Debug> qubyte_poc.local_fitting_output_theo (68274ea8-266a-4abc-ae0e-dccf816a640e): Fetched part 20250321_6108_8793_74 from default:/clickhouse/tables/qubyte_poc/local_fitting_output_theo/s0/replicas/r0
2025.03.21 11:32:45.663692 [ 110398 ] {} <Debug> qubyte_poc.local_fit_params (307ee0dd-a053-4ffa-a896-c7863f5fb787): Fetched part 20250321_20836_42197_1327 from default:/clickhouse/tables/qubyte_poc/local_fit_params/s0/replicas/r0
2025.03.21 11:33:29.910493 [ 121331 ] {} <Debug> qubyte_poc.ok_book_tbt_local (8152f202-8ab9-43ab-b815-5ef6d4948201): Fetched part 20250321_16945_18087_5 from default:/clickhouse/tables/qubyte_poc/ok_book_tbt_local/s0/replicas/r0
2025.03.21 11:33:48.191342 [ 123149 ] {} <Debug> qubyte_poc.local_signal_update (18439dc8-c7aa-4572-bdf7-9752b1f9f92a): Fetched part 20250321_239689_289940_551 from default:/clickhouse/tables/qubyte_poc/local_signal_update/s0/replicas/r0
2025.03.21 11:39:18.027436 [ 123094 ] {} <Debug> qubyte_poc.local_strike_view (248c76cf-5cbe-4607-80db-1a1fb2c16022): Fetched part 20250321_22116_26121_29 from default:/clickhouse/tables/qubyte_poc/local_strike_view/s0/replicas/r0
``` 
And a lot of 'Not executing log entry xxx is being processed.'
```
2025.03.21 10:03:36.442638 [ 90 ] {} <Trace> qubyte_poc.local_inst_risk_data (ReplicatedMergeTreeQueue): Insert entry queue-0024990394 to queue with type GET_PART with virtual parts [20250321_131486_131486_0]
2025.03.21 10:03:36.442660 [ 90 ] {} <Debug> qubyte_poc.local_inst_risk_data (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2025.03.21 10:03:36.443935 [ 90 ] {} <Information> qubyte_poc.local_inst_risk_data (ReplicatedMergeTreeQueue): Not executing log entry queue-0024655569 of type MERGE_PARTS for part 20250320_1921544_1922717_90 because another log entry queue-0024655552 of type MERGE_PARTS for the same part (20250320_1922703_1922713_2) is being processed.
2025.03.21 10:03:36.455686 [ 90 ] {} <Information> qubyte_poc.local_inst_risk_data (ReplicatedMergeTreeQueue): Not executing log entry queue-0024665188 of type MERGE_PARTS for part 20250320_1763269_1930291_142 because another log entry queue-0024662202 of type GET_PART for the same part (20250320_1928136_1928136_0) is being processed.
2025.03.21 10:03:37.496984 [ 169 ] {} <Information> qubyte_poc.local_inst_risk_data (ReplicatedMergeTreeQueue): Not executing log entry queue-0024655569 of type MERGE_PARTS for part 20250320_1921544_1922717_90 because another log entry queue-0024655552 of type MERGE_PARTS for the same part (20250320_1922703_1922713_2) is being processed.
2025.03.21 10:03:37.508743 [ 169 ] {} <Information> qubyte_poc.local_inst_risk_data (ReplicatedMergeTreeQueue): Not executing log entry queue-0024665188 of type MERGE_PARTS for part 20250320_1763269_1930291_142 because another log entry queue-0024662202 of type GET_PART for the same part (20250320_1928136_1928136_0) is being processed.
2025.03.21 10:03:37.512956 [ 169 ] {} <Information> qubyte_poc.local_inst_risk_data (ReplicatedMergeTreeQueue): Not executing log entry queue-0024655569 of type MERGE_PARTS for part 20250320_1921544_1922717_90 because another log entry queue-0024655552 of type MERGE_PARTS for the same part (20250320_1922703_1922713_2) is being processed.
2025.03.21 10:03:37.512972 [ 123155 ] {} <Debug> qubyte_poc.local_inst_risk_data (7829278f-015d-4157-aee1-8259b3ba8f5d): Skipping action for part 20250321_109299_109299_0 because part 20250321_103444_117470_28 already exists.
2025.03.21 10:03:37.524022 [ 169 ] {} <Information> qubyte_poc.local_inst_risk_data (ReplicatedMergeTreeQueue): Not executing log entry queue-0024665188 of type MERGE_PARTS for part 20250320_1763269_1930291_142 because another log entry queue-0024662202 of type GET_PART for the same part (20250320_1928136_1928136_0) is being processed.
2025.03.21 10:03:37.531645 [ 164 ] {} <Information> qubyte_poc.local_inst_risk_data (ReplicatedMergeTreeQueue): Not executing log entry queue-0024655569 of type MERGE_PARTS for part 20250320_1921544_1922717_90 because another log entry queue-0024655552 of type MERGE_PARTS for the same part (20250320_1922703_1922713_2) is being processed.
2025.03.21 10:03:37.541800 [ 164 ] {} <Information> qubyte_poc.local_inst_risk_data (ReplicatedMergeTreeQueue): Not executing log entry queue-0024665188 of type MERGE_PARTS for part 20250320_1763269_1930291_142 because another log entry queue-0024662202 of type GET_PART for the same part (20250320_1928136_1928136_0) is being processed.
2025.03.21 10:03:37.545463 [ 164 ] {} <Information> qubyte_poc.local_inst_risk_data (ReplicatedMergeTreeQueue): Not executing log entry queue-0024655569 of type MERGE_PARTS for part 20250320_1921544_1922717_90 because another log entry queue-0024655552 of type MERGE_PARTS for the same part (20250320_1922703_1922713_2) is being processed.
2025.03.21 10:03:37.545578 [ 123188 ] {} <Debug> qubyte_poc.local_inst_risk_data (7829278f-015d-4157-aee1-8259b3ba8f5d): Skipping action for part 20250321_109300_109300_0 because part 20250321_103444_117470_28 already exists.
2025.03.21 10:03:37.555498 [ 164 ] {} <Information> qubyte_poc.local_inst_risk_data (ReplicatedMergeTreeQueue): Not executing log entry queue-0024665188 of type MERGE_PARTS for part 20250320_1763269_1930291_142 because another log entry queue-0024662202 of type GET_PART for the same part (20250320_1928136_1928136_0) is being processed.
2025.03.21 10:03:37.565599 [ 89 ] {} <Information> qubyte_poc.local_inst_risk_data (ReplicatedMergeTreeQueue): Not executing log entry queue-0024655569 of type MERGE_PARTS for part 20250320_1921544_1922717_90 because another log entry queue-0024655552 of type MERGE_PARTS for the same part (20250320_1922703_1922713_2) is being processed.
2025.03.21 10:03:37.575593 [ 89 ] {} <Information> qubyte_poc.local_inst_risk_data (ReplicatedMergeTreeQueue): Not executing log entry queue-0024665188 of type MERGE_PARTS for part 20250320_1763269_1930291_142 because another log entry queue-0024662202 of type GET_PART for the same part (20250320_1928136_1928136_0) is being processed.
```

**Comment by alexey-milovidov** [comment]
23.8 is an old version.
