### ISSUE TITLE
test 00992_system_parts_race_condition_zookeeper_long hangs

### ISSUE THREAD

**Issue by hanfei1991** [ClickHouse/ClickHouse#43946]
(you don't have to strictly follow this form)

**Describe the bug**

test `00992_system_parts_race_condition_zookeeper_long` hangs, a mutation will stuck in the middle of test util test finishes and executes drop table.
It appears in CI tests recently.

CI failed link https://s3.amazonaws.com/clickhouse-test-reports/0/b29335199d4371534e97b47ff35f45b10c640045/stateless_tests__release__databaseordinary_.html

**Comment by tavplubix** [comment]
Probably fixed in https://github.com/ClickHouse/ClickHouse/pull/46946

**Comment by alesapin** [comment]
Still not fixed: https://s3.amazonaws.com/clickhouse-test-reports/0/6f76c27bb117bc061b3698ecace012b61b67c0d5/stateless_tests__release__databaseordinary_.html
