### ISSUE TITLE
Part doesn't exist

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#44562]
```
2022.12.23 19:52:43.991320 [ 333008 ] {} <Fatal> BaseDaemon: (version 22.12.1.1752 (official build), build id: 280BC383A6843A693B67BC1293582649A1FA8DAF) (from thread 333092) Terminate called for uncaught exception:
2022.12.23 19:52:43.991353 [ 333008 ] {} <Fatal> BaseDaemon: Code: 49. DB::Exception: Part all_81_81_0 doesn't exist. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):
2022.12.23 19:52:43.991362 [ 333008 ] {} <Fatal> BaseDaemon: 
2022.12.23 19:52:43.991376 [ 333008 ] {} <Fatal> BaseDaemon: 0. ./build_docker/../src/Common/Exception.cpp:77: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0xe74c47a in /usr/lib/debug/usr/bin/clickhouse.debug
2022.12.23 19:52:43.991385 [ 333008 ] {} <Fatal> BaseDaemon: 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool) @ 0x7eb1f2d in /usr/lib/debug/usr/bin/clickhouse.debug
2022.12.23 19:52:43.991392 [ 333008 ] {} <Fatal> BaseDaemon: 2. ./build_docker/../src/Storages/MergeTree/MergeTreeData.h:0: DB::MergeTreeData::modifyPartState(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreeDataPartState) @ 0x14e0f570 in /usr/lib/debug/usr/bin/clickhouse.debug
2022.12.23 19:52:43.991410 [ 333008 ] {} <Fatal> BaseDaemon: 3. ./build_docker/../src/Storages/MergeTree/MergeTreeData.cpp:5380: DB::MergeTreeData::Transaction::commit(std::__1::unique_lock<std::__1::mutex>*) @ 0x14e572f1 in /usr/lib/debug/usr/bin/clickhouse.debug
2022.12.23 19:52:43.991417 [ 333008 ] {} <Fatal> BaseDaemon: 4. ./build_docker/../src/Storages/StorageReplicatedMergeTree.cpp:0: DB::StorageReplicatedMergeTree::checkPartChecksumsAndCommit(DB::MergeTreeData::Transaction&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::optional<DB::MergeTreeData::HardlinkedFiles>) @ 0x14a59b91 in /usr/lib/debug/usr/bin/clickhouse.debug
2022.12.23 19:52:43.991431 [ 333008 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../contrib/llvm-project/libcxx/include/vector:951: DB::StorageReplicatedMergeTree::fetchPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, unsigned long, std::__1::shared_ptr<zkutil::ZooKeeper>, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) @ 0x14a7e8b8 in /usr/lib/debug/usr/bin/clickhouse.debug
2022.12.23 19:52:43.991439 [ 333008 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Storages/StorageReplicatedMergeTree.cpp:0: DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&, bool) @ 0x14a6fdce in /usr/lib/debug/usr/bin/clickhouse.debug
2022.12.23 19:52:43.991446 [ 333008 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeMutateTaskBase.cpp:149: DB::ReplicatedMergeMutateTaskBase::executeImpl() @ 0x150d5943 in /usr/lib/debug/usr/bin/clickhouse.debug
2022.12.23 19:52:43.991452 [ 333008 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeMutateTaskBase.cpp:0: DB::ReplicatedMergeMutateTaskBase::executeStep() @ 0x150d4ac2 in /usr/lib/debug/usr/bin/clickhouse.debug
2022.12.23 19:52:43.991458 [ 333008 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:157: DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0x7e975cb in /usr/lib/debug/usr/bin/clickhouse.debug
2022.12.23 19:52:43.991472 [ 333008 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:0: DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0x7e9700c in /usr/lib/debug/usr/bin/clickhouse.debug
2022.12.23 19:52:43.991516 [ 333008 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../base/base/wide_integer_impl.h:786: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xe809096 in /usr/lib/debug/usr/bin/clickhouse.debug
2022.12.23 19:52:43.991529 [ 333008 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../src/Common/ThreadPool.cpp:0: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0xe80b8b5 in /usr/lib/debug/usr/bin/clickhouse.debug
2022.12.23 19:52:43.991538 [ 333008 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../base/base/wide_integer_impl.h:786: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe8056b6 in /usr/lib/debug/usr/bin/clickhouse.debug
2022.12.23 19:52:43.991546 [ 333008 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__t
```
Report: https://s3.amazonaws.com/clickhouse-test-reports/44530/5030c92373e42c5c5e6aeeb529f0a0715d619541/stress_test__ubsan_.html

**Comment by alesapin** [comment]
Should be fixed by this https://github.com/ClickHouse/ClickHouse/pull/44628 but I'm not sure.

**Comment by qoega** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/cdff9439f70ae2a559cff1f2c203c6eaac6cf5c5/stress_test__msan_/fatal_messages.txt

**Comment by alexey-milovidov** [comment]
Not fixed: https://s3.amazonaws.com/clickhouse-test-reports/0/d22f25b72fd8a749dd2d1ddc3ef1bf17bab72386/stress_test__debug_.html

**Comment by qoega** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/ff493c439c0c14dc258fa4953b6b8d6a87a11de4/stress_test__debug_.html

**Comment by qoega** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/911bb8e6abddf7d8b1891fadb764835205605af5/stress_test__msan_/fatal_messages.txt
https://s3.amazonaws.com/clickhouse-test-reports/0/3007507a8b991ae0b8f3712b58e8670b3a136c9a/stress_test__msan_/fatal_messages.txt

And slightly different
 https://s3.amazonaws.com/clickhouse-test-reports/0/f16328aa8baec7132d0901c0deafcdf8c50482a5/stress_test__msan_/fatal_messages.txt

```
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.19 14:03:40.762784 [ 1829 ] {} <Fatal> : Logical error: 'Deleting data part all_2_2_0 doesn't exist'.
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.19 14:04:32.066128 [ 34513 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.19 14:04:32.066515 [ 34513 ] {} <Fatal> BaseDaemon: (version 22.13.1.1 (official build), build id: AAA090C6E03B2394F84854A615CC427AF2861E72) (from thread 1829) (no query) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.19 14:04:32.070202 [ 34513 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.19 14:04:32.074193 [ 34513 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f521a29e00b 0x7f521a27d859 0x2985a3e9 0x2985ae53 0xdf8fa4e 0x4aaa1c87 0x49e9f766 0x49e9c184 0x4b2f3c4f 0x4b2f36c7 0x4b31e509 0x42cbc0c7 0x42cc64a5 0x42cc8965 0x29bbf04d 0x29bcd1c3 0x7f521a455609 0x7f521a37a133
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.19 14:04:32.076647 [ 34513 ] {} <Fatal> BaseDaemon: 4. gsignal @ 0x7f521a29e00b in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.19 14:04:32.077126 [ 34513 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7f521a27d859 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.19 14:04:32.672242 [ 34513 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:41: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x2985a3e9 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.19 14:04:32.992354 [ 34513 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./build_docker/../src/Common/Exception.cpp:0: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*>> const&)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.19 14:04:32.994284 [ 34513 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Common/Exception.cpp:78: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0x2985ae53 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.19 14:07:10.077775 [ 1610 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

**Comment by alexey-milovidov** [comment]
I didn't see it recently.
