### ISSUE TITLE
`test_storage_rabbitmq` is broken

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#45160]
It's been broken for 2 months already: https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCAgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlICcyMDIyLTA2LTAxJyA8PSBjaGVja19zdGFydF90aW1lIGFuZCB0ZXN0X25hbWUgbGlrZSAnJXRlc3Rfc3RvcmFnZV9yYWJiaXRtcSUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==

**Comment by kssenii** [comment]
it was/is broken for different reasons, first was under ASAN, I fixed it here https://github.com/ClickHouse/ClickHouse/pull/44897. 
Now checked last failures and it is a data race in libuv (https://pastila.nl/?0085d30d/41f1f98e598dc46c6fa759faf13f1205) - found it is already fixed in libuv https://github.com/libuv/libuv/issues/2884 by this commit https://github.com/libuv/libuv/commit/c70dd705bc2adc488ddffcdc12f0c610d116e77b, which is not present in our version of libuv, need to update the library, will do right now, so please close the disabling pull request.

**Comment by kssenii** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/issues/45160.

**Comment by kssenii** [comment]
Will be fixing them today!

**Comment by tavplubix** [comment]
https://play.clickhouse.com/play?user=play#d2l0aCAKJyV0ZXN0X3N0b3JhZ2VfcmFiYml0bXElJyBhcyBuYW1lX3BhdHRlcm4sCiclJyBhcyBjb250ZXh0X3BhdHRlcm4sCicyMDIyLTA5LTAxJyBhcyBzdGFydF9kYXRlLAooJ1N0YXRlbGVzcyB0ZXN0cyAoYXNhbiknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MsIGFjdGlvbnMpJykgYXMgYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzCnNlbGVjdCAKdG9TdGFydE9mRGF5KGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlIHN0YXJ0X2RhdGUgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgcHVsbF9yZXF1ZXN0X251bWJlciBub3QgaW4gCihzZWxlY3QgcHVsbF9yZXF1ZXN0X251bWJlciBhcyBwcm4gZnJvbSBjaGVja3Mgd2hlcmUgcHJuIT0wIGFuZCBzdGFydF9kYXRlIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIGNoZWNrX25hbWUgaW4gYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzKSAKYW5kIHRlc3RfbmFtZSBsaWtlIG5hbWVfcGF0dGVybiBhbmQgdGVzdF9jb250ZXh0X3JhdyBpbGlrZSBjb250ZXh0X3BhdHRlcm4KYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScpIGdyb3VwIGJ5IGQgb3JkZXIgYnkgZCBkZXNj

**Comment by kssenii** [comment]
Ok, 

this link is easier for me to monitor, will save it here for myself
https://play.clickhouse.com/play?user=play#d2l0aCAKJyV0ZXN0X3N0b3JhZ2VfcmFiYml0bXElJyBhcyBuYW1lX3BhdHRlcm4sCiclJyBhcyBjb250ZXh0X3BhdHRlcm4sCicyMDIyLTA5LTAxJyBhcyBzdGFydF9kYXRlLAooJ1N0YXRlbGVzcyB0ZXN0cyAoYXNhbiknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MsIGFjdGlvbnMpJykgYXMgYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzCnNlbGVjdCB0ZXN0X25hbWUsIGNoZWNrX3N0YXJ0X3RpbWUgYXMgZCwgcHVsbF9yZXF1ZXN0X251bWJlciwgcmVwb3J0X3VybApmcm9tIGNoZWNrcyB3aGVyZSBzdGFydF9kYXRlIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHB1bGxfcmVxdWVzdF9udW1iZXIgbm90IGluIAooc2VsZWN0IHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHJuIGZyb20gY2hlY2tzIHdoZXJlIHBybiE9MCBhbmQgc3RhcnRfZGF0ZSA8PSBjaGVja19zdGFydF90aW1lIGFuZCBjaGVja19uYW1lIGluIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcykgCmFuZCB0ZXN0X25hbWUgbGlrZSBuYW1lX3BhdHRlcm4gYW5kIHRlc3RfY29udGV4dF9yYXcgaWxpa2UgY29udGV4dF9wYXR0ZXJuCmFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBvcmRlciBieSBkIGRlc2M=. 

Part of the failures were addressed by https://github.com/ClickHouse/ClickHouse/pull/46078 and https://github.com/ClickHouse/ClickHouse/pull/46107.

Will continue fixing... will try to fix today.

**Comment by tavplubix** [comment]
It's still flaky: https://s3.amazonaws.com/clickhouse-test-reports/0/dc8f38c0398f1caf58bdfcaa4723eb966c4f588b/integration_tests__tsan__[2/4].html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/5ab82cc019871c2d8690da319487c4e354c38779/integration_tests__asan__[4_6].html

**Comment by tavplubix** [comment]
still flaky https://s3.amazonaws.com/clickhouse-test-reports/0/54c5158291be706266f6bc4c6ce61d93e08af0ba/integration_tests__tsan__[5_6].html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/b314b8d4ac03869d3af2d8038a699cd9314ce47e/integration_tests__release__[2_4].html

**Comment by qoega** [comment]
May be fixed by https://github.com/ClickHouse/ClickHouse/pull/55424 or we will see more debug information when it will fail again

**Comment by antaljanosbenjamin** [comment]
Somehow the datarace in libuv is [back](https://s3.amazonaws.com/clickhouse-test-reports/58957/830b7aef916be8e03c07f17099825c0ece8d122c/integration_tests__tsan__[4_6].html):
```
Location is global 'uv__hrtime.fast_clock_id' of size 8 at 0x5557c3d03318 (clickhouse+0x216fe318)
SUMMARY: ThreadSanitizer: data race build_docker/./contrib/libuv/src/unix/linux-core.c:138:14 in uv__hrtime
```

**Comment by qoega** [comment]
With clang-18 asan again
https://s3.amazonaws.com/clickhouse-test-reports/60469/ee772aaf0f7a05fafb3fa286419148211362b0d6/integration_tests__asan__analyzer__[4_6].html
```
==8==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f79f772d024 at pc 0x5579c962df07 bp 0x7f79f816c070 sp 0x7f79f816c068
READ of size 4 at 0x7f79f772d024 thread T2 (TCPHandler)
    #0 0x5579c962df06 in uv__platform_invalidate_fd build_docker/./contrib/libuv/src/unix/epoll.c:69:26
    #1 0x5579c962299b in uv__poll_stop build_docker/./contrib/libuv/src/unix/poll.c:108:3
    #2 0x5579c962299b in uv_poll_stop build_docker/./contrib/libuv/src/unix/poll.c:114:3
    #3 0x5579bdd20043 in AMQP::LibUvHandler::Watcher::~Watcher() build_docker/./contrib/AMQP-CPP/include/amqpcpp/libuv.h:109:13
    #4 0x5579bdd20043 in AMQP::LibUvHandler::Watcher::~Watcher() build_docker/./contrib/AMQP-CPP/include/amqpcpp/libuv.h:107:9
    #5 0x5579bdd1fa07 in std::__1::default_delete<AMQP::LibUvHandler::Watcher>::operator()[abi:v15000](AMQP::LibUvHandler::Watcher*) const build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48:5
    #6 0x5579bdd1fa07 in std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>::reset[abi:v15000](AMQP::LibUvHandler::Watcher*) build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305:7
    #7 0x5579bdd1fa07 in std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>::~unique_ptr[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259:19
    #8 0x5579bdd1fa07 in std::__1::pair<int const, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>::~pair() build_docker/./contrib/llvm-project/libcxx/include/__utility/pair.h:40:29
    #9 0x5579bdd1fa07 in void std::__1::__destroy_at[abi:v15000]<std::__1::pair<int const, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>, 0>(std::__1::pair<int const, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>*) build_docker/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:63:13
    #10 0x5579bdd1fa07 in void std::__1::destroy_at[abi:v15000]<std::__1::pair<int const, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>, 0>(std::__1::pair<int const, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>*) build_docker/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:88:5
    #11 0x5579bdd1fa07 in void std::__1::allocator_traits<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<int, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>, void*>>>::destroy[abi:v15000]<std::__1::pair<int const, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>, void, void>(std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<int, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>, void*>>&, std::__1::pair<int const, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>*) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:317:9
    #12 0x5579bdd1fa07 in std::__1::__tree<std::__1::__value_type<int, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>, std::__1::__map_value_compare<int, std::__1::__value_type<int, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>, std::__1::less<int>, true>, std::__1::allocator<std::__1::__value_type<int, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>>>::erase(std::__1::__tree_const_iterator<std::__1::__value_type<int, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>, std::__1::__tree_node<std::__1::__value_type<int, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>, void*>*, long>) build_docker/./contrib/llvm-project/libcxx/include/__tree:2421:5
    #13 0x5579bdd1fa07 in std::__1::map<int, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>, std::__1::less<int>, std::__1::allocator<std::__1::pair<int const, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>>>::erase[abi:v15000](std::__1::__map_iterator<std::__1::__tree_iterator<std::__1::__value_type<int, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>, std::__1::__tree_node<std::__1::__value_type<int, std::__1::unique_ptr<AMQP::LibUvHandler::Watcher, std::__1::default_delete<AMQP::LibUvHandler::Watcher>>>, void*>*, long>>) build_docker/./contrib/llvm-project/libcxx/include/map:1374:56
    #14 0x5579bdd1fa07 in AMQP::LibUvHandler::monitor(AMQP::TcpConnection*, int, int) build_docker/./contrib/AMQP-CPP/include/amqpcpp/libuv.h:199:23
    #15 0x5579c95c89d2 in AMQP::TcpConnection::~TcpConnection() build_docker/./contrib/AMQP-CPP/src/linux_tcp/tcpconnection.cpp:45:34
    #16 0x5579c95c89d2 in AMQP::TcpConnection::~TcpConnection() build_docker/./contrib/AMQP-CPP/src/linux_tcp/tcpconnection.cpp:40:1
    #17 0x5579bdd1d695 in std::__1::default_delete<AMQP::TcpConnection>::operator()[abi:v15000](AMQP::TcpConnection*) const build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48:5
    #18 0x5579bdd1d695 in std::__1::unique_ptr<AMQP::TcpConnection, std::__1::default_delete<AMQP::TcpConnection>>::reset[abi:v15000](AMQP::TcpConnection*) build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305:7
    #19 0x5579bdd1d695 in std::__1::unique_ptr<AMQP::TcpConnection, std::__1::default_delete<AMQP::TcpConnection>>::~unique_ptr[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259:19
    #20 0x5579bdd1d695 in DB::RabbitMQConnection::~RabbitMQConnection() build_docker/./src/Storages/RabbitMQ/RabbitMQConnection.h:22:7
    #21 0x5579bdd17df5 in std::__1::default_delete<DB::RabbitMQConnection>::operator()[abi:v15000](DB::RabbitMQConnection*) const build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48:5
    #22 0x5579bdd17df5 in std::__1::unique_ptr<DB::RabbitMQConnection, std::__1::default_delete<DB::RabbitMQConnection>>::reset[abi:v15000](DB::RabbitMQConnection*) build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305:7
    #23 0x5579bdd17df5 in std::__1::unique_ptr<DB::RabbitMQConnection, std::__1::default_delete<DB::RabbitMQConnection>>::~unique_ptr[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259:19
    #24 0x5579bdcf288d in DB::StorageRabbitMQ::StorageRabbitMQ(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>, DB::LoadingStrictnessLevel) build_docker/./src/Storages/RabbitMQ/StorageRabbitMQ.cpp:192:1
    #25 0x5579bdd2acd8 in DB::StorageRabbitMQ* std::__1::construct_at[abi:v15000]<DB::StorageRabbitMQ, DB::StorageID const&, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>, DB::LoadingStrictnessLevel const&, DB::StorageRabbitMQ*>(DB::StorageRabbitMQ*, DB::StorageID const&, std::__1::shared_ptr<DB::Context>&&, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>&&, DB::LoadingStrictnessLevel const&) build_docker/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:35:48
    #26 0x5579bdd2acd8 in void std::__1::allocator_traits<std::__1::allocator<DB::StorageRabbitMQ>>::construct[abi:v15000]<DB::StorageRabbitMQ, DB::StorageID const&, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>, DB::LoadingStrictnessLevel const&, void, void>(std::__1::allocator<DB::StorageRabbitMQ>&, DB::StorageRabbitMQ*, DB::StorageID const&, std::__1::shared_ptr<DB::Context>&&, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>&&, DB::LoadingStrictnessLevel const&) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:298:9
    #27 0x5579bdd2acd8 in std::__1::__shared_ptr_emplace<DB::StorageRabbitMQ, std::__1::allocator<DB::StorageRabbitMQ>>::__shared_ptr_emplace[abi:v15000]<DB::StorageID const&, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>, DB::LoadingStrictnessLevel const&>(std::__1::allocator<DB::StorageRabbitMQ>, DB::StorageID const&, std::__1::shared_ptr<DB::Context>&&, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>&&, DB::LoadingStrictnessLevel const&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:292:9
    #28 0x5579bdd2acd8 in std::__1::shared_ptr<DB::StorageRabbitMQ> std::__1::allocate_shared[abi:v15000]<DB::StorageRabbitMQ, std::__1::allocator<DB::StorageRabbitMQ>, DB::StorageID const&, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>, DB::LoadingStrictnessLevel const&, void>(std::__1::allocator<DB::StorageRabbitMQ> const&, DB::StorageID const&, std::__1::shared_ptr<DB::Context>&&, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>&&, DB::LoadingStrictnessLevel const&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:953:55
    #29 0x5579bdd16938 in std::__1::shared_ptr<DB::StorageRabbitMQ> std::__1::make_shared[abi:v15000]<DB::StorageRabbitMQ, DB::StorageID const&, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>, DB::LoadingStrictnessLevel const&, void>(DB::StorageID const&, std::__1::shared_ptr<DB::Context>&&, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>&&, DB::LoadingStrictnessLevel const&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962:12
    #30 0x5579bdd16938 in DB::registerStorageRabbitMQ(DB::StorageFactory&)::$_0::operator()(DB::StorageFactory::Arguments const&) const build_docker/./src/Storages/RabbitMQ/StorageRabbitMQ.cpp:1210:16
    #31 0x5579bdd16938 in decltype(std::declval<DB::registerStorageRabbitMQ(DB::StorageFactory&)::$_0&>()(std::declval<DB::StorageFactory::Arguments const&>())) std::__1::__invoke[abi:v15000]<DB::registerStorageRabbitMQ(DB::StorageFactory&)::$_0&, DB::StorageFactory::Arguments const&>(DB::registerStorageRabbitMQ(DB::StorageFactory&)::$_0&, DB::StorageFactory::Arguments const&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #32 0x5579bdd16938 in std::__1::shared_ptr<DB::IStorage> std::__1::__invoke_void_return_wrapper<std::__1::shared_ptr<DB::IStorage>, false>::__call<DB::registerStorageRabbitMQ(DB::StorageFactory&)::$_0&, DB::StorageFactory::Arguments const&>(DB::registerStorageRabbitMQ(DB::StorageFactory&)::$_0&, DB::StorageFactory::Arguments const&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:470:16
    #33 0x5579bdd16938 in std::__1::__function::__default_alloc_func<DB::registerStorageRabbitMQ(DB::StorageFactory&)::$_0, std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::operator()[abi:v15000](DB::StorageFactory::Arguments const&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #34 0x5579bdd16938 in std::__1::shared_ptr<DB::IStorage> std::__1::__function::__policy_invoker<std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::registerStorageRabbitMQ(DB::StorageFactory&)::$_0, std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>>(std::__1::__function::__policy_storage const*, DB::StorageFactory::Arguments const&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #35 0x5579bd543c72 in std::__1::__function::__policy_func<std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::operator()[abi:v15000](DB::StorageFactory::Arguments const&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #36 0x5579bd543c72 in std::__1::function<std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::operator()(DB::StorageFactory::Arguments const&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #37 0x5579bd543c72 in DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, DB::LoadingStrictnessLevel) const build_docker/./src/Storages/StorageFactory.cpp:224:16
    #38 0x5579bb5c91f9 in DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::__1::unique_ptr<DB::DDLGuard, std::__1::default_delete<DB::DDLGuard>>&) build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:1491:42
    #39 0x5579bb5ba7be in DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:1311:20
    #40 0x5579bb5d2d87 in DB::InterpreterCreateQuery::execute() build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:1790:16
    #41 0x5579bc80a982 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/./src/Interpreters/executeQuery.cpp:1130:40
    #42 0x5579bc803b64 in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) build_docker/./src/Interpreters/executeQuery.cpp:1309:26
    #43 0x5579bed9e4fc in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:518:54
    #44 0x5579bedd20eb in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2312:9
    #45 0x5579c4ef85ae in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #46 0x5579c4ef91ba in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #47 0x5579c526bf6a in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #48 0x5579c52661e7 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #49 0x55799ac2f658 in asan_thread_start(void*) crtstuff.c
    #50 0x7f7ae14c7ac2  (/lib/x86_64-linux-gnu/libc.so.6+0x94ac2) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)
    #51 0x7f7ae155984f  (/lib/x86_64-linux-gnu/libc.so.6+0x12684f) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)

Address 0x7f79f772d024 is located in stack of thread T2 (TCPHandler) at offset 36 in frame
    #0 0x5579c962e3cf in uv__io_poll build_docker/./contrib/libuv/src/unix/epoll.c:109
```

**Comment by KochetovNicolai** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/14d0cc2bf33fc7080f65211cf4aaee742224d584/integration_tests__aarch64__[4_6].html

**Comment by kssenii** [comment]
> [https://s3.amazonaws.com/clickhouse-test-reports/0/14d0cc2bf33fc7080f65211cf4aaee742224d584/integration_tests__aarch64__[4_6].html](https://s3.amazonaws.com/clickhouse-test-reports/0/14d0cc2bf33fc7080f65211cf4aaee742224d584/integration_tests__aarch64__%5B4_6%5D.html)

It was fixed in https://github.com/ClickHouse/ClickHouse/pull/67743

**Comment by alexey-milovidov** [comment]
Not fixed: [https://s3.amazonaws.com/clickhouse-test-reports/0/8af682f7483f3651957200d0a9ef8bbb9b7a0141/integration_tests__tsan__[4_6].html](https://s3.amazonaws.com/clickhouse-test-reports/0/8af682f7483f3651957200d0a9ef8bbb9b7a0141/integration_tests__tsan__%5B4_6%5D.html)

**Comment by alexey-milovidov** [comment]
Not fixed: https://s3.amazonaws.com/clickhouse-test-reports/0/681014d99db245c0f6a61764f5c9735f84b9768c/integration_tests__aarch64__[4_6].html

**Comment by alexey-milovidov** [comment]
Not fixed: https://s3.amazonaws.com/clickhouse-test-reports/60197/77c8bbda4316ef5812e6f9e6457002b0bbc5a275/integration_tests__aarch64__[4_6].html

**Comment by alexey-milovidov** [comment]
It failed: https://s3.amazonaws.com/clickhouse-test-reports/68482/02ec4e2f92ac769f92aebdb714d0d8da1a924984/integration_tests__asan__old_analyzer__[4_6].html

**Comment by alexey-milovidov** [comment]
It failed one more time: https://s3.amazonaws.com/clickhouse-test-reports/68488/5d851d718af1dbc150ebf78dd026bf5f6d55071c/integration_tests__asan__old_analyzer__[4_6].html

**Comment by Algunenano** [comment]
Similar as the latest mentions (https://s3.amazonaws.com/clickhouse-test-reports/69780/6ba4f61df86c8edc864863ef52a0a237bc5805b8/integration_tests__tsan__[4_6].html)

```
>       raise Exception("Cannot wait RabbitMQ container")
E       Exception: Cannot wait RabbitMQ container
```
