### ISSUE TITLE
Try remove `delete-on-destroy.txt` and see what happen

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#45510]
Strange flag-file on disk which makes part's remove logic even more complex. We have a quite good test infrastructure so let's just try to remove it and see what will happen.

**Comment by bharatnc** [comment]
Already resolved by #49181?

**Comment by alesapin** [comment]
Yes, we still have some pieces in the codebase related to it, but we don't write it. So we can close this one.
