### ISSUE TITLE
version 22.3, sql can not be killed

### ISSUE THREAD

**Issue by WillMeng** [ClickHouse/ClickHouse#46806]
clickhouse version 22.3.18.37
The sql alaways running and can not be killed
sql like this
```
insert into pub_summary_db_1.temp_0_4_feed_intention_keyword (chan_pub_id,channel_id,publisher_id,pub_account_id,create_time) 
select chan_pub_id,channel_id,publisher_id,pub_account_id,create_time 
from remote('10.252.3.4', pub_summary_db_feed_baidu.rollup_intention_keyword, 'xxx', 'xxx') where ck_shard_index=0 and v_ck_db_id=4000 
```
full server log, and any more server log, and no error log
```
2023.02.24 07:04:47.314370 [ 31919 ] {23d0bc31-d504-4bd1-8cf5-cbd4ff60332d} <Debug> executeQuery: (from 10.252.2.108:33288, user: admin_user) insert into pub_summary_db_1.temp_0_4_feed_intention_keyword_intention_keyword_day_feed_baidu_20230222_f1e2a15ab3cd11ed9eb4fa163e676c73_1677193487 (chan_pub_id,channel_id,publisher_id,pub_account_id,subject,pub_intention_keyword_id,data_date,pub_account_name,pub_intention_keyword,pub_impression,pub_click,pub_cost,create_time) select chan_pub_id,channel_id,publisher_id,pub_account_id,subject,pub_intention_keyword_id,data_date,pub_account_name,pub_intention_keyword,pub_impression,pub_click,pub_cost,create_time from remote('10.252.3.4', pub_summary_db_feed_baidu.rollup_intention_keyword_day_2_1_intention_keyword_20230222_1_f1e2a0ceb3cd11ed9eb4fa163e676c73_20230224_070434_8124, 'xxx', 'xxx') where ck_shard_index=0 and v_ck_db_id=4000
2023.02.24 07:04:47.314501 [ 31919 ] {23d0bc31-d504-4bd1-8cf5-cbd4ff60332d} <Trace> ContextAccess (admin_user): Access granted: INSERT(chan_pub_id, channel_id, publisher_id, pub_account_id, subject, pub_intention_keyword_id, data_date, pub_account_name, pub_intention_keyword, pub_impression, pub_click, pub_cost, create_time) ON pub_summary_db_1.temp_0_4_feed_intention_keyword_intention_keyword_day_feed_baidu_20230222_f1e2a15ab3cd11ed9eb4fa163e676c73_1677193487
2023.02.24 07:04:47.314727 [ 31919 ] {23d0bc31-d504-4bd1-8cf5-cbd4ff60332d} <Trace> ContextAccess (admin_user): Access granted: CREATE TEMPORARY TABLE, REMOTE ON *.*
2023.02.24 07:04:47.314783 [ 31919 ] {23d0bc31-d504-4bd1-8cf5-cbd4ff60332d} <Trace> Connection (10.252.3.4:9000): Connecting. Database: (not specified). User: admin_user
2023.02.24 07:04:47.345118 [ 31919 ] {23d0bc31-d504-4bd1-8cf5-cbd4ff60332d} <Trace> Connection (10.252.3.4:9000): Connected to ClickHouse server version 22.3.9.
2023.02.24 07:04:47.347434 [ 31919 ] {23d0bc31-d504-4bd1-8cf5-cbd4ff60332d} <Trace> InterpreterSelectQuery: Complete -> Complete
```

setting:
```
Settings:                              {'max_threads':'16','max_query_size':'33554432','use_uncompressed_cache':'1','load_balancing':'random','distributed_aggregation_memory_efficient':'1','distributed_product_mode':'local','max_concurrent_queries_for_user':'5000','join_use_nulls':'1','max_bytes_before_external_group_by':'54975581388','max_bytes_before_external_sort':'54975581388','max_execution_time':'3600','max_ast_depth':'1000','max_ast_elements':'5000000','max_expanded_ast_elements':'5000000','join_algorithm':'auto','max_memory_usage':'109951162776'}
```

go client version: clickhouse-go/2.5.1 (lv:go/1.20; os:linux)

elapsed: 13019.421312424

If I run kill query where query_id='23d0bc31-d504-4bd1-8cf5-cbd4ff60332d', the killed sql alaways running. I can only restart the clickhouse-server.  
Please help me, thanks.

**Comment by UnamedRus** [comment]
KILL QUERY only set special flag, which checked between blocks of query execution.

If your query stuck within such block, it may never check flag and kill query

**Comment by Algunenano** [comment]
If you provide a simple way to reproduce the problem it might be possible to add better or more places where CH can stop specific queries.

**Comment by tavplubix** [comment]
Also stacktraces would be helpful. You can obtain the stacktraces using [this](https://github.com/ClickHouse/ClickHouse/blob/7122ebab4d696b45add7f3d40b066e31a4093b18/tests/clickhouse-test#L266-L283) query (it makes sense to run int multiple times to check if something is changing or it's completely stuck) or using a [query profiler](https://clickhouse.com/docs/en/operations/optimizing-performance/sampling-query-profiler/)

**Comment by WillMeng** [comment]
> 



> KILL QUERY only set special flag, which checked between blocks of query execution.
> 
> If your query 卡住了within such block, it may never check flag and kill query

Thanks. I don't quite understand what you mean. I have try kill query sync or async, that is both doesn't work.

**Comment by WillMeng** [comment]
> If you provide a simple way to reproduce the problem it might be possible to add better or more places where CH can stop specific queries.

Thanks. I can not reproduce the problem. For the past month, several SQLs have been unable to end within one or two days, and no pattern has been found yet.

**Comment by WillMeng** [comment]
One more thing, we used php client, python client, golang client, they all have experienced similar problems.

**Comment by WillMeng** [comment]
> Also stacktraces would be helpful. You can obtain the stacktraces using [this](https://github.com/ClickHouse/ClickHouse/blob/7122ebab4d696b45add7f3d40b066e31a4093b18/tests/clickhouse-test#L266-L283) query (it makes sense to run it multiple times to check if something is changing or it's completely stuck) or using a [query profiler](https://clickhouse.com/docs/en/operations/optimizing-performance/sampling-query-profiler/)

Thanks, first way stacktraces had invalid, because I had restart clickhouse-server. And I used second way, sql:
```
SELECT
    count(),
    arrayStringConcat(arrayMap(x -> concat(demangle(addressToSymbol(x)), '\n    ', addressToLine(x)), trace), '\n') AS sym
FROM system.trace_log
WHERE (query_id = '23d0bc31-d504-4bd1-8cf5-cbd4ff60332d') AND (event_date = today())
GROUP BY trace
ORDER BY count() DESC
LIMIT 10
SETTINGS allow_introspection_functions = 1
```

Output:
```
51008	
    
DB::TimerDescriptor::drain() const
    /usr/bin/clickhouse
DB::TimerDescriptor::reset() const
    /usr/bin/clickhouse
DB::HedgedConnectionsFactory::processEpollEvents(bool, DB::Connection*&)
    /usr/bin/clickhouse
DB::HedgedConnectionsFactory::getManyConnections(DB::PoolMode)
    /usr/bin/clickhouse
DB::HedgedConnections::HedgedConnections(std::__1::shared_ptr<DB::ConnectionPoolWithFailover> const&, std::__1::shared_ptr<DB::Context const>, DB::ConnectionTimeouts const&, std::__1::shared_ptr<DB::Throttler> const&, DB::PoolMode, std::__1::shared_ptr<DB::QualifiedTableName>)
    /usr/bin/clickhouse

    /usr/bin/clickhouse
DB::RemoteQueryExecutor::sendQuery(DB::ClientInfo::QueryKind)
    /usr/bin/clickhouse
DB::RemoteSource::tryGenerate()
    /usr/bin/clickhouse
DB::ISource::work()
    /usr/bin/clickhouse
DB::SourceWithProgress::work()
    /usr/bin/clickhouse
DB::ExecutionThreadContext::executeTask()
    /usr/bin/clickhouse
DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*)
    /usr/bin/clickhouse
DB::PipelineExecutor::executeImpl(unsigned long)
    /usr/bin/clickhouse
DB::PipelineExecutor::execute(unsigned long)
    /usr/bin/clickhouse

    /usr/bin/clickhouse
ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)
    /usr/bin/clickhouse

    /usr/bin/clickhouse

    

    
50708	
    
Poco::EventImpl::waitImpl()
    /usr/bin/clickhouse
DB::CompletedPipelineExecutor::Data::~Data()
    /usr/bin/clickhouse
DB::CompletedPipelineExecutor::~CompletedPipelineExecutor()
    /usr/bin/clickhouse
DB::TCPHandler::runImpl()
    /usr/bin/clickhouse
DB::TCPHandler::run()
    /usr/bin/clickhouse
Poco::Net::TCPServerConnection::start()
    /usr/bin/clickhouse
Poco::Net::TCPServerDispatcher::run()
    /usr/bin/clickhouse
Poco::PooledThread::run()
    /usr/bin/clickhouse
Poco::ThreadImpl::runnableEntry(void*)
    /usr/bin/clickhouse

    

    
300	
    
Poco::EventImpl::waitImpl(long)
    /usr/bin/clickhouse
DB::CompletedPipelineExecutor::execute()
    /usr/bin/clickhouse
DB::TCPHandler::runImpl()
    /usr/bin/clickhouse
DB::TCPHandler::run()
    /usr/bin/clickhouse
Poco::Net::TCPServerConnection::start()
    /usr/bin/clickhouse
Poco::Net::TCPServerDispatcher::run()
    /usr/bin/clickhouse
Poco::PooledThread::run()
    /usr/bin/clickhouse
Poco::ThreadImpl::runnableEntry(void*)
    /usr/bin/clickhouse

    

    
3	
    

    
unw_step
    
unw_backtrace
    

    /usr/bin/clickhouse

    

    
DB::TimerDescriptor::drain() const
    /usr/bin/clickhouse
DB::TimerDescriptor::reset() const
    /usr/bin/clickhouse
DB::HedgedConnectionsFactory::processEpollEvents(bool, DB::Connection*&)
    /usr/bin/clickhouse
DB::HedgedConnectionsFactory::getManyConnections(DB::PoolMode)
    /usr/bin/clickhouse
DB::HedgedConnections::HedgedConnections(std::__1::shared_ptr<DB::ConnectionPoolWithFailover> const&, std::__1::shared_ptr<DB::Context const>, DB::ConnectionTimeouts const&, std::__1::shared_ptr<DB::Throttler> const&, DB::PoolMode, std::__1::shared_ptr<DB::QualifiedTableName>)
    /usr/bin/clickhouse

    /usr/bin/clickhouse
DB::RemoteQueryExecutor::sendQuery(DB::ClientInfo::QueryKind)
    /usr/bin/clickhouse
DB::RemoteSource::tryGenerate()
    /usr/bin/clickhouse
DB::ISource::work()
    /usr/bin/clickhouse
DB::SourceWithProgress::work()
    /usr/bin/clickhouse
DB::ExecutionThreadContext::executeTask()
    /usr/bin/clickhouse
DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*)
    /usr/bin/clickhouse
DB::PipelineExecutor::executeImpl(unsigned long)
    /usr/bin/clickhouse
DB::PipelineExecutor::execute(unsigned long)
    /usr/bin/clickhouse

    /usr/bin/clickhouse
ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)
    /usr/bin/clickhouse

    /usr/bin/clickhouse

    

    
1	
    

    

    
unw_step
    
unw_backtrace
    

    /usr/bin/clickhouse

    

    
Poco::EventImpl::waitImpl()
    /usr/bin/clickhouse
DB::CompletedPipelineExecutor::Data::~Data()
    /usr/bin/clickhouse
DB::CompletedPipelineExecutor::~CompletedPipelineExecutor()
    /usr/bin/clickhouse
DB::TCPHandler::runImpl()
    /usr/bin/clickhouse
DB::TCPHandler::run()
    /usr/bin/clickhouse
Poco::Net::TCPServerConnection::start()
    /usr/bin/clickhouse
Poco::Net::TCPServerDispatcher::run()
    /usr/bin/clickhouse
Poco::PooledThread::run()
    /usr/bin/clickhouse
Poco::ThreadImpl::runnableEntry(void*)
    /usr/bin/clickhouse

    

    
1	MemoryTracker::allocImpl(long, bool, MemoryTracker*)
    /usr/bin/clickhouse
MemoryTracker::allocImpl(long, bool, MemoryTracker*)
    /usr/bin/clickhouse
DB::WriteBufferFromPocoSocket::WriteBufferFromPocoSocket(Poco::Net::Socket&, unsigned long)
    /usr/bin/clickhouse
DB::Connection::connect(DB::ConnectionTimeouts const&)
    /usr/bin/clickhouse
DB::Connection::getServerRevision(DB::ConnectionTimeouts const&)
    /usr/bin/clickhouse
DB::ConnectionEstablisher::run(PoolWithFailoverBase<DB::IConnectionPool>::TryResult&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)
    /usr/bin/clickhouse
DB::ConnectionEstablisherAsync::Routine::operator()(boost::context::fiber&&)
    /usr/bin/clickhouse
void boost::context::detail::fiber_entry<boost::context::detail::fiber_record<boost::context::fiber, FiberStack&, DB::ConnectionEstablisherAsync::Routine> >(boost::context::detail::transfer_t)
    /usr/bin/clickhouse
1	
    

    
unw_step
    
unw_backtrace
    

    /usr/bin/clickhouse

    

    
Poco::EventImpl::waitImpl()
    /usr/bin/clickhouse
DB::CompletedPipelineExecutor::Data::~Data()
    /usr/bin/clickhouse
DB::CompletedPipelineExecutor::~CompletedPipelineExecutor()
    /usr/bin/clickhouse
DB::TCPHandler::runImpl()
    /usr/bin/clickhouse
DB::TCPHandler::run()
    /usr/bin/clickhouse
Poco::Net::TCPServerConnection::start()
    /usr/bin/clickhouse
Poco::Net::TCPServerDispatcher::run()
    /usr/bin/clickhouse
Poco::PooledThread::run()
    /usr/bin/clickhouse
Poco::ThreadImpl::runnableEntry(void*)
    /usr/bin/clickhouse

    

    
1	DB::ReadBufferFromPocoSocket::poll(unsigned long) const
    /usr/bin/clickhouse
DB::TCPHandler::isQueryCancelled()
    /usr/bin/clickhouse

    /usr/bin/clickhouse
DB::CompletedPipelineExecutor::execute()
    /usr/bin/clickhouse
DB::TCPHandler::runImpl()
    /usr/bin/clickhouse
DB::TCPHandler::run()
    /usr/bin/clickhouse
Poco::Net::TCPServerConnection::start()
    /usr/bin/clickhouse
Poco::Net::TCPServerDispatcher::run()
    /usr/bin/clickhouse
Poco::PooledThread::run()
    /usr/bin/clickhouse
Poco::ThreadImpl::runnableEntry(void*)
    /usr/bin/clickhouse

    

    
1	
    

    
unw_step
    
unw_backtrace
    

    /usr/bin/clickhouse

    

    
DB::TimerDescriptor::drain() const
    /usr/bin/clickhouse
DB::TimerDescriptor::reset() const
    /usr/bin/clickhouse
DB::HedgedConnectionsFactory::processEpollEvents(bool, DB::Connection*&)
    /usr/bin/clickhouse
DB::HedgedConnectionsFactory::getManyConnections(DB::PoolMode)
    /usr/bin/clickhouse
DB::HedgedConnections::HedgedConnections(std::__1::shared_ptr<DB::ConnectionPoolWithFailover> const&, std::__1::shared_ptr<DB::Context const>, DB::ConnectionTimeouts const&, std::__1::shared_ptr<DB::Throttler> const&, DB::PoolMode, std::__1::shared_ptr<DB::QualifiedTableName>)
    /usr/bin/clickhouse

    /usr/bin/clickhouse
DB::RemoteQueryExecutor::sendQuery(DB::ClientInfo::QueryKind)
    /usr/bin/clickhouse
DB::RemoteSource::tryGenerate()
    /usr/bin/clickhouse
DB::ISource::work()
    /usr/bin/clickhouse
DB::SourceWithProgress::work()
    /usr/bin/clickhouse
DB::ExecutionThreadContext::executeTask()
    /usr/bin/clickhouse
DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*)
    /usr/bin/clickhouse
DB::PipelineExecutor::executeImpl(unsigned long)
    /usr/bin/clickhouse
DB::PipelineExecutor::execute(unsigned long)
    /usr/bin/clickhouse

    /usr/bin/clickhouse
ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)
    /usr/bin/clickhouse

    /usr/bin/clickhouse

    

    
1	
    /usr/bin/clickhouse

    
```

**Comment by WillMeng** [comment]
I estimate that there will be new SQLs tomorrow or the day after tomorrow, and I will send out the results of first way when that time comes.

**Comment by tavplubix** [comment]
Looks like https://github.com/ClickHouse/ClickHouse/issues/37686

cc: @KochetovNicolai

**Comment by alexey-milovidov** [comment]
The bug has been introduced here: https://github.com/ClickHouse/ClickHouse/pull/25674
This pull request has to be reverted.

**Comment by WillMeng** [comment]
```
Connected to ClickHouse server version 22.3.18 revision 54455.

ecs-ckdb01 :) SELECT
                  groupArray((s.thread_id, arrayStringConcat(arrayMap(
                      x -> concat(addressToLine(x), '::', demangle(addressToSymbol(x))),
                      s.trace), '\n') AS stacktrace
                  )) AS stacktraces,
                  p.*
              FROM system.processes p
              JOIN system.stack_trace s USING (query_id)
              WHERE query NOT LIKE '%system.processes%'
              GROUP BY p.*
              ORDER BY elapsed DESC
              SETTINGS allow_introspection_functions = 1\G

SELECT
    groupArray((s.thread_id, arrayStringConcat(arrayMap(x -> concat(addressToLine(x), '::', demangle(addressToSymbol(x))), s.trace), '\n') AS stacktrace)) AS stacktraces,
    p.*
FROM system.processes AS p
INNER JOIN system.stack_trace AS s USING (query_id)
WHERE query NOT LIKE '%system.processes%'
GROUP BY p.*
ORDER BY elapsed DESC
SETTINGS allow_introspection_functions = 1

Query id: 4cab3ba2-51a3-4a52-aeb4-1fd3b4c85b05

Row 1:
──────
stacktraces:          [(23964,'/usr/lib64/libpthread-2.17.so::\n/usr/bin/clickhouse::DB::TimerDescriptor::drain() const\n/usr/bin/clickhouse::DB::TimerDescriptor::reset() const\n/usr/bin/clickhouse::DB::HedgedConnectionsFactory::processEpollEvents(bool, DB::Connection*&)\n/usr/bin/clickhouse::DB::HedgedConnectionsFactory::getManyConnections(DB::PoolMode)\n/usr/bin/clickhouse::DB::HedgedConnections::HedgedConnections(std::__1::shared_ptr<DB::ConnectionPoolWithFailover> const&, std::__1::shared_ptr<DB::Context const>, DB::ConnectionTimeouts const&, std::__1::shared_ptr<DB::Throttler> const&, DB::PoolMode, std::__1::shared_ptr<DB::QualifiedTableName>)\n/usr/bin/clickhouse::\n/usr/bin/clickhouse::DB::RemoteQueryExecutor::sendQuery(DB::ClientInfo::QueryKind)\n/usr/bin/clickhouse::DB::RemoteSource::tryGenerate()\n/usr/bin/clickhouse::DB::ISource::work()\n/usr/bin/clickhouse::DB::SourceWithProgress::work()\n/usr/bin/clickhouse::DB::ExecutionThreadContext::executeTask()\n/usr/bin/clickhouse::DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*)\n/usr/bin/clickhouse::DB::PipelineExecutor::executeImpl(unsigned long)\n/usr/bin/clickhouse::DB::PipelineExecutor::execute(unsigned long)\n/usr/bin/clickhouse::\n/usr/bin/clickhouse::ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)\n/usr/bin/clickhouse::\n/usr/lib64/libpthread-2.17.so::start_thread\n/usr/lib64/libc-2.17.so::clone'),(28833,'/usr/lib64/libpthread-2.17.so::pthread_cond_timedwait@@GLIBC_2.3.2\n/usr/bin/clickhouse::Poco::EventImpl::waitImpl(long)\n/usr/bin/clickhouse::DB::CompletedPipelineExecutor::execute()\n/usr/bin/clickhouse::DB::TCPHandler::runImpl()\n/usr/bin/clickhouse::DB::TCPHandler::run()\n/usr/bin/clickhouse::Poco::Net::TCPServerConnection::start()\n/usr/bin/clickhouse::Poco::Net::TCPServerDispatcher::run()\n/usr/bin/clickhouse::Poco::PooledThread::run()\n/usr/bin/clickhouse::Poco::ThreadImpl::runnableEntry(void*)\n/usr/lib64/libpthread-2.17.so::start_thread\n/usr/lib64/libc-2.17.so::clone')]
is_initial_query:     1
user:                 admin_user
query_id:             0b734fa6-d7bd-4448-9e33-e094e0a59c1c
address:              ::ffff:10.252.2.108
port:                 21704
initial_user:         admin_user
initial_query_id:     0b734fa6-d7bd-4448-9e33-e094e0a59c1c
initial_address:      ::ffff:10.252.2.108
initial_port:         21704
interface:            1
os_user:              root
client_hostname:      ecs-job-loader
client_name:          clickhouse-go/2.5.1 (lv:go/1.20; os:linux)
client_revision:      0
client_version_major: 2
client_version_minor: 5
client_version_patch: 0
http_method:          0
http_user_agent:
http_referer:
forwarded_for:
quota_key:
distributed_depth:    0
elapsed:              17734.129488179
is_cancelled:         0
read_rows:            0
read_bytes:           0
total_rows_approx:    0
written_rows:         0
written_bytes:        0
memory_usage:         12938446
peak_memory_usage:    12938446
query:                insert into pub_summary_db_1.temp_0_4_account_audience_feed_uc_20230225_6bda502ab70711edb18efa163e676c73_1677548977 (chan_pub_id,channel_id,publisher_id,pub_account_id,jzl_country_id,province_id,city_id,data_date,biz_unit_01,biz_unit_02,biz_unit_03,biz_unit_04,pub_account_name,pub_province_id,pub_city_id,pub_impression,pub_click,pub_cost,`$uc_pub_conversion_count`,create_time,last_modify_time) select chan_pub_id,channel_id,publisher_id,pub_account_id,jzl_country_id,province_id,city_id,data_date,biz_unit_01,biz_unit_02,biz_unit_03,biz_unit_04,pub_account_name,pub_province_id,pub_city_id,pub_impression,pub_click,pub_cost,`$uc_pub_conversion_count`,create_time,last_modify_time from remote('10.252.3.4', pub_summary_db_feed_uc.rollup_audience_2_17_account_biz_unit_city_20230225_1_6bda4f3ab70711edb18efa163e676c73_20230228_094920_91882, 'xxx', 'xxx') where ck_shard_index=0 and v_ck_db_id=4
thread_ids:           [28833,23964]
ProfileEvents:        {'Query':1,'InsertQuery':1,'ReadCompressedBytes':643,'CompressedReadBufferBlocks':4,'CompressedReadBufferBytes':948,'IOBufferAllocs':5,'IOBufferAllocBytes':3146721,'FunctionExecute':6,'TableFunctionExecute':1,'NetworkReceiveElapsedMicroseconds':8147,'NetworkSendElapsedMicroseconds':53772,'NetworkReceiveBytes':1960,'NetworkSendBytes':1320271,'ContextLock':122,'RWLockAcquiredReadLocks':4,'QueryProfilerRuns':35475}
Settings:             {'max_threads':'16','max_query_size':'33554432','use_uncompressed_cache':'1','load_balancing':'random','distributed_aggregation_memory_efficient':'1','distributed_product_mode':'local','max_concurrent_queries_for_user':'5000','join_use_nulls':'1','max_bytes_before_external_group_by':'54975581388','max_bytes_before_external_sort':'54975581388','max_execution_time':'3600','max_ast_depth':'1000','max_ast_elements':'5000000','max_expanded_ast_elements':'5000000','join_algorithm':'auto','max_memory_usage':'109951162776'}
current_database:     default

1 rows in set. Elapsed: 0.066 sec.

```

**Comment by WillMeng** [comment]
@tavplubix @alexey-milovidov Please check above content.

**Comment by alexey-milovidov** [comment]
Fixed in master by https://github.com/ClickHouse/ClickHouse/issues/46843.

**Comment by amosbird** [comment]
According to the discussion in https://github.com/ClickHouse/ClickHouse/issues/37686 I guess this issue is not fixed by reverting asynchronous connection drain, but https://github.com/ClickHouse/ClickHouse/pull/67702.
