### ISSUE TITLE
Random Crashes - LOGICAL_ERROR String offsets has data inconsistent with chars array

### ISSUE THREAD

**Issue by DamienVicet** [ClickHouse/ClickHouse#50715]
**Describe what's wrong**

I have random crashes when selecting time series data from a buffer table engine.

**How to reproduce**

It seems a bit difficult to reproduce, many select queries are executed on this table and only a few random crashes sometimes happen.

* ClickHouse server version : **23.4.2.11**

* `CREATE TABLE` statements

```
CREATE TABLE test.calculus
(
  `value` Float64 CODEC(Delta, LZ4),
  `uuid` LowCardinality(String),
  `time` DateTime64(3) CODEC(DoubleDelta, LZ4)
)
ENGINE = MergeTree()
ORDER BY (uuid, time);
```

```
CREATE TABLE test.buffer_calculus AS test.calculus
ENGINE = Buffer(test, calculus, 16, 240, 600, 20000, 100000, 50000000, 250000000);
```

* Query to run that lead to unexpected result

The query tries to get the 3 last points before a date
```
SELECT
  value AS _value,
  toFloat64(time) * 1000 AS _time
FROM buffer_calculus
WHERE
  uuid='412db80d-0c3d-4194-a866-1f8f6d55a9a6'
  AND time >= fromUnixTimestamp64Milli(0)
  AND time < fromUnixTimestamp64Milli(1686227742361)
ORDER BY time DESC
LIMIT 1 BY _time
LIMIT 3
SETTINGS optimize_read_in_order=1
FORMAT RowBinary
```

**Error message and/or stacktrace**

Here is the stacktrace
```
2023.06.08 12:36:50.903117 [ 650503 ] {9c713fbb-2e28-4f2c-ab59-e4b9a96c9ad0} <Error> executeQuery: Code: 49. DB::Exception: String offsets has data inconsistent with chars array: While executing MergingSortedTransform. (LOGICAL_ERROR) (version 23.4.2.11 (official build)) (from 172.19.0.61:55248) (in query: SELECT value AS _value, toFloat64(time) * 1000 AS _time FROM buffer_calculus WHERE uuid='412db80d-0c3d-4194-a866-1f8f6d55a9a6' AND time >= fromUnixTimestamp64Milli(0) AND time < fromUnixTimestamp64Milli(1686227742361) ORDER BY time DESC LIMIT 1 BY _time LIMIT 3 SETTINGS optimize_read_in_order=1 FORMAT RowBinary ), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe3bb175 in /usr/bin/clickhouse
1. ? @ 0xccbce76 in /usr/bin/clickhouse
2. DB::ColumnString::ColumnString(DB::ColumnString const&) @ 0x140544aa in /usr/bin/clickhouse
3. ? @ 0x1405e183 in /usr/bin/clickhouse
4. ? @ 0x8f6c2e2 in /usr/bin/clickhouse
5. ? @ 0x8f6c403 in /usr/bin/clickhouse
6. ? @ 0x12d3fd9b in /usr/bin/clickhouse
7. ? @ 0x8f6c339 in /usr/bin/clickhouse
8. ? @ 0x8f6c403 in /usr/bin/clickhouse
9. ? @ 0x1402aafe in /usr/bin/clickhouse
10. DB::IColumn::forEachSubcolumn(std::function<void (COW<DB::IColumn>::chameleon_ptr<DB::IColumn>&)>) @ 0x141dc2e7 in /usr/bin/clickhouse
11. ? @ 0x8f6c339 in /usr/bin/clickhouse
12. DB::Chunk::mutateColumns() @ 0x14d13ffc in /usr/bin/clickhouse
13. ? @ 0x15050f56 in /usr/bin/clickhouse
14. ? @ 0x1505f287 in /usr/bin/clickhouse
15. ? @ 0x13d352b2 in /usr/bin/clickhouse
16. DB::ExecutionThreadContext::executeTask() @ 0x14d3aa6a in /usr/bin/clickhouse
17. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x14d3073b in /usr/bin/clickhouse
18. ? @ 0x14d3246f in /usr/bin/clickhouse
19. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xe490475 in /usr/bin/clickhouse
20. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0xe492cb5 in /usr/bin/clickhouse
21. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe48c2a1 in /usr/bin/clickhouse
22. ? @ 0xe491b21 in /usr/bin/clickhouse
23. ? @ 0x7f9db37c5b43 in ?
24. ? @ 0x7f9db3857a00 in ?

2023.06.08 12:36:50.904864 [ 650503 ] {9c713fbb-2e28-4f2c-ab59-e4b9a96c9ad0} <Error> DynamicQueryHandler: Code: 49. DB::Exception: String offsets has data inconsistent with chars array: While executing MergingSortedTransform. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe3bb175 in /usr/bin/clickhouse
1. ? @ 0xccbce76 in /usr/bin/clickhouse
2. DB::ColumnString::ColumnString(DB::ColumnString const&) @ 0x140544aa in /usr/bin/clickhouse
3. ? @ 0x1405e183 in /usr/bin/clickhouse
4. ? @ 0x8f6c2e2 in /usr/bin/clickhouse
5. ? @ 0x8f6c403 in /usr/bin/clickhouse
6. ? @ 0x12d3fd9b in /usr/bin/clickhouse
7. ? @ 0x8f6c339 in /usr/bin/clickhouse
8. ? @ 0x8f6c403 in /usr/bin/clickhouse
9. ? @ 0x1402aafe in /usr/bin/clickhouse
10. DB::IColumn::forEachSubcolumn(std::function<void (COW<DB::IColumn>::chameleon_ptr<DB::IColumn>&)>) @ 0x141dc2e7 in /usr/bin/clickhouse
11. ? @ 0x8f6c339 in /usr/bin/clickhouse
12. DB::Chunk::mutateColumns() @ 0x14d13ffc in /usr/bin/clickhouse
13. ? @ 0x15050f56 in /usr/bin/clickhouse
14. ? @ 0x1505f287 in /usr/bin/clickhouse
15. ? @ 0x13d352b2 in /usr/bin/clickhouse
16. DB::ExecutionThreadContext::executeTask() @ 0x14d3aa6a in /usr/bin/clickhouse
17. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x14d3073b in /usr/bin/clickhouse
18. ? @ 0x14d3246f in /usr/bin/clickhouse
19. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xe490475 in /usr/bin/clickhouse
20. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0xe492cb5 in /usr/bin/clickhouse
21. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe48c2a1 in /usr/bin/clickhouse
22. ? @ 0xe491b21 in /usr/bin/clickhouse
23. ? @ 0x7f9db37c5b43 in ?
24. ? @ 0x7f9db3857a00 in ?
 (version 23.4.2.11 (official build))

```

**Comment by den-crane** [comment]
> Float64 CODEC(Delta

I guess Float64 and Delta should be suspicious @rschu1ze ?

**Comment by rschu1ze** [comment]
> I guess Float64 and Delta should be suspicious @rschu1ze ?

Float\+Delta is IMO okay, lets allow it unless there are reproducible issues.
This crash seems related to String columns.

**Comment by JJCella** [comment]
Maybe related to https://github.com/ClickHouse/ClickHouse/issues/49013 ? 
LowCardinality ?

**Comment by al13n321** [comment]
Agree, most likely the same as https://github.com/ClickHouse/ClickHouse/issues/49013 , fixed in https://github.com/ClickHouse/ClickHouse/pull/49111 , will be in 23.5

**Comment by JJCella** [comment]
I'm also experiencing this issue ; still present in 23.5 (23.5.1.3174)

Same request as above :


```
2023.06.15 06:35:43.884691 [ 3364846 ] {8ac32115-ce1b-4f14-89fc-3ba1a1fe730d} <Error> DynamicQueryHandler: Code: 49. DB::Exception: String offsets has data inconsistent with chars array: While executing MergingSortedTransform. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e345675 in /usr/bin/clickhouse
1. ? @ 0x000000000c756578 in /usr/bin/clickhouse
2. DB::ColumnString::ColumnString(DB::ColumnString const&) @ 0x000000001402d7ca in /usr/bin/clickhouse
3. ? @ 0x0000000014036863 in /usr/bin/clickhouse
4. ? @ 0x0000000008c22300 in /usr/bin/clickhouse
5. ? @ 0x0000000008c22423 in /usr/bin/clickhouse
6. ? @ 0x0000000012d3581b in /usr/bin/clickhouse
7. ? @ 0x0000000008c22359 in /usr/bin/clickhouse
8. ? @ 0x0000000008c22423 in /usr/bin/clickhouse
9. ? @ 0x000000001400485d in /usr/bin/clickhouse
10. DB::IColumn::forEachSubcolumn(std::function<void (COW<DB::IColumn>::chameleon_ptr<DB::IColumn>&)>) @ 0x00000000141a7c87 in /usr/bin/clickhouse
11. ? @ 0x0000000008c22359 in /usr/bin/clickhouse
12. DB::Chunk::mutateColumns() @ 0x0000000014d105db in /usr/bin/clickhouse
13. ? @ 0x0000000015032714 in /usr/bin/clickhouse
14. ? @ 0x0000000015040e67 in /usr/bin/clickhouse
15. ? @ 0x0000000013d044cc in /usr/bin/clickhouse
16. DB::ExecutionThreadContext::executeTask() @ 0x0000000014d35ac9 in /usr/bin/clickhouse
17. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000014d2c750 in /usr/bin/clickhouse
18. ? @ 0x0000000014d2d8c3 in /usr/bin/clickhouse
19. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000e41d603 in /usr/bin/clickhouse
20. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000e41fdf5 in /usr/bin/clickhouse
21. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000e419494 in /usr/bin/clickhouse
22. ? @ 0x000000000e41ec81 in /usr/bin/clickhouse
23. ? @ 0x00007fd790c62b43 in ?
24. ? @ 0x00007fd790cf4a00 in ?
 (version 23.5.1.3174 (official build))
```

**Comment by den-crane** [comment]
@JJCella  do you use Engine=Buffer?

**Comment by den-crane** [comment]
though I reproduced it

```
An error occurred while processing the query 'SELECT  value AS _value,  toFloat64(time) * 1000 AS _time FROM test.buffer_calculus WHERE  uuid='412db80d-0c3d-4194-a866-1f8f6d55a9a6'  AND time >= fromUnixTimestamp64Milli(0)   ORDER BY time DESC LIMIT 1 BY _time LIMIT 3 SETTINGS optimize_read_in_order=1 FORMAT RowBinary': Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: String offsets has data inconsistent with chars array: While executing MergingSortedTransform. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e3453d5 in /usr/bin/clickhouse
1. ? @ 0x000000000c7562f8 in /usr/bin/clickhouse
2. DB::ColumnString::ColumnString(DB::ColumnString const&) @ 0x000000001402dfaa in /usr/bin/clickhouse
3. ? @ 0x0000000014037043 in /usr/bin/clickhouse
4. ? @ 0x0000000008c22080 in /usr/bin/clickhouse
5. ? @ 0x0000000008c221a3 in /usr/bin/clickhouse
6. ? @ 0x0000000012d354fb in /usr/bin/clickhouse
7. ? @ 0x0000000008c220d9 in /usr/bin/clickhouse
8. ? @ 0x0000000008c221a3 in /usr/bin/clickhouse
9. ? @ 0x000000001400503d in /usr/bin/clickhouse
10. DB::IColumn::forEachSubcolumn(std::function<void (COW<DB::IColumn>::chameleon_ptr<DB::IColumn>&)>) @ 0x00000000141a8467 in /usr/bin/clickhouse
11. ? @ 0x0000000008c220d9 in /usr/bin/clickhouse
12. DB::Chunk::mutateColumns() @ 0x0000000014d10d9b in /usr/bin/clickhouse
13. ? @ 0x0000000015032ed4 in /usr/bin/clickhouse
14. ? @ 0x0000000015041627 in /usr/bin/clickhouse
15. ? @ 0x0000000013d048ac in /usr/bin/clickhouse
16. DB::ExecutionThreadContext::executeTask() @ 0x0000000014d36289 in /usr/bin/clickhouse
17. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000014d2cf10 in /usr/bin/clickhouse
18. ? @ 0x0000000014d2e083 in /usr/bin/clickhouse
19. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000e41d363 in /usr/bin/clickhouse
20. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000e41fb55 in /usr/bin/clickhouse
21. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000e4191f4 in /usr/bin/clickhouse
22. ? @ 0x000000000e41e9e1 in /usr/bin/clickhouse
23. start_thread @ 0x0000000000007fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
24. clone @ 0x00000000000f94cf in /lib/x86_64-linux-gnu/libc-2.28.so
. (LOGICAL_ERROR) (version 23.5.2.7 (official build))
DB::Exception: Received from localhost:9000. DB::Exception: String offsets has data inconsistent with chars array: While executing MergingSortedTransform. Stack trace:
```

**Comment by den-crane** [comment]
```
# cat create.sql
drop database if exists test;
create database test;
use test;
CREATE TABLE calculus(
  `value` Float64 CODEC(Delta, LZ4),
  `uuid` LowCardinality(String),
  `time` DateTime64(3) CODEC(DoubleDelta, LZ4)
) ENGINE = MergeTree() ORDER BY (uuid, time);

CREATE TABLE buffer_calculus AS calculus
ENGINE = Buffer(currentDatabase(), calculus, 16, 240, 600, 20000, 100000, 50000000, 250000000);

# cat insert.sql
insert into test.buffer_calculus select 1/number, generateUUIDv4(), 1676227742361+number from numbers(1001);
insert into test.buffer_calculus select 1/number, '412db80d-0c3d-4194-a866-1f8f6d55a9a6', 1676227742361+number from numbers(101);
insert into test.buffer_calculus select 1/number, generateUUIDv4(), 1676227742361+number from numbers(101);

# cat select.sql
SELECT  value AS _value,  toFloat64(time) * 1000 AS _time FROM test.buffer_calculus WHERE  uuid='412db80d-0c3d-4194-a866-1f8f6d55a9a6'  AND time >= fromUnixTimestamp64Milli(0)   ORDER BY time DESC LIMIT 1 BY _time LIMIT 3 SETTINGS optimize_read_in_order=1 FORMAT Null
```

```
clickhouse-client -mn < create.sql

session1: for i in `seq 1 1500`; do clickhouse-client -mn < insert.sql; sleep .1; done
session2: for i in `seq 1 15000`; do clickhouse-client -mn < select.sql; done
```

**Comment by den-crane** [comment]
one more repro, one-liner
it seems it's related to race between insert and select

```
cat create.sql
drop database if exists test;

create database test;

use test;

CREATE TABLE calculus(
  `value` Float64 CODEC(Delta, LZ4),
  `uuid` LowCardinality(String),
  `time` DateTime64(3) CODEC(DoubleDelta, LZ4)
) ENGINE = MergeTree() ORDER BY (uuid, time);

CREATE TABLE buffer_calculus AS calculus
ENGINE = Buffer(currentDatabase(), calculus, 1, 10, 6000000, 100000, 100000, 10000, 2500000);

cat insert.sql
insert into test.buffer_calculus select 1/number, generateUUIDv4(), 1676227742361+number from numbers(1001);
insert into test.buffer_calculus select 1/number, '412db80d-0c3d-4194-a866-1f8f6d55a9a6', 1676227742361+number from numbers(101);
insert into test.buffer_calculus select 1/number, generateUUIDv4(), 1676227742361+number from numbers(101);

cat select.sql
SELECT  value AS _value,  toFloat64(time) * 1000 AS _time FROM test.buffer_calculus WHERE  uuid='412db80d-0c3d-4194-a866-1f8f6d55a9a6'  AND time >= fromUnixTimestamp64Milli(0)   ORDER BY time DESC LIMIT 1 BY _time LIMIT 3 SETTINGS optimize_read_in_order=1 FORMAT Null


clickhouse-client -mn <create.sql ; for i in `seq 1 1500`; do (clickhouse-client -mn < insert.sql &);  clickhouse-client -mn < select.sql;  sleep .01; done
Received exception from server (version 23.5.2):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: String offsets has data inconsistent with chars array: While executing MergingSortedTransform. (LOGICAL_ERROR)
(query: SELECT  value AS _value,  toFloat64(time) * 1000 AS _time FROM test.buffer_calculus WHERE  uuid='412db80d-0c3d-4194-a866-1f8f6d55a9a6'  AND time >= fromUnixTimestamp64Milli(0)   ORDER BY time DESC LIMIT 1 BY _time LIMIT 3 SETTINGS optimize_read_in_order=1 FORMAT Null

)
```

**Comment by al13n321** [comment]
Slightly reduced repro:
```
% cat create.sql 
drop database if exists test;
create database test;
use test;
CREATE TABLE calculus(
  `uuid` LowCardinality(String)
) ENGINE = Null;

CREATE TABLE buffer_calculus AS calculus
ENGINE = Buffer(currentDatabase(), calculus, 16, 240, 600, 2000000, 10000000, 5000000000, 25000000000);

% cat insert.sql 
insert into test.buffer_calculus select '' from numbers(1);
insert into test.buffer_calculus select randomString(1000) from numbers(1001);

% cat select.sql 
SELECT uuid FROM test.buffer_calculus WHERE uuid='' ORDER BY uuid DESC LIMIT 1 BY uuid SETTINGS optimize_read_in_order=1 FORMAT Null
```

With the same one-liner (replacing `sleep` with `wait` to go a little faster):
```
% clickhouse-client -mn <create.sql ; for i in `seq 1500`; do (clickhouse-client -mn < insert.sql & clickhouse-client -mn < select.sql; wait) done
```

Observations about the repro:
* MergeTree wasn't required, Null table works just as well.
* But Buffer, `optimize_read_in_order`, and LIMIT BY are required.
* Fails after ~2 seconds.
* Queries start failing long before the buffer is flushed for the first time.
* Increasing length of strings from 36 to 1000 made it fail much faster.

**Comment by den-crane** [comment]
Received exception from server (version 23.3.3):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: String offsets has data inconsistent with chars array: While executing MergingSortedTransform. (LOGICAL_ERROR)

Received exception from server (version 22.12.6):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: String offsets has data inconsistent with chars array: While executing MergingSortedTransform. (LOGICAL_ERROR)

It seems the issue was introduced in 22.12

**Comment by al13n321** [comment]
Alrighty, https://github.com/ClickHouse/ClickHouse/pull/51064 should be it, this was rough to debug, thanks for the repro!
