### ISSUE TITLE
Querying ReplicatedSummingMergeTree table through Distribution table with condition on `DateTime64` column with lesser/greater than subquery result returns results only from single shard

### ISSUE THREAD

**Issue by gliter** [ClickHouse/ClickHouse#50868]
**Describe what's wrong**

When querying a table using `ReplicatedSummingMergeTree` engine through Distributed table with condition on `DateTime64` column with lesser/greater than subquery results ClickHouse returns results only from single shard.

Example query:

`select * from gl_test.test_smt_d tsd where dt64 > (select toDateTime64(0, 3, 'UTC'));`

> Not reproducable in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/) as at least two shard are needed and ability to connect with specific one

**Does it reproduce on recent release?**

Unknown I have only access to version `22.8.17.17` 

**How to reproduce**

ClickHouse installation with at least 2 shards.

```sql
create database gl_test ON CLUSTER '{cluster}' ENGINE = Atomic();

-- drop table gl_test.test_smt ON CLUSTER '{cluster}' sync
CREATE TABLE gl_test.test_smt ON CLUSTER '{cluster}' (
    id String,
    dt DateTime('UTC'),
    dt64 DateTime64(3, 'UTC'),
    val Int32
    ) ENGINE ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/gl_test/test_smt', '{replica}', (val))
    PARTITION BY toYYYYMM(dt)
    ORDER BY (cityHash64(id), toDate(dt), val)
    PRIMARY KEY (cityHash64(id), toDate(dt));

-- drop table gl_test.test_smt_d ON CLUSTER '{cluster}' sync
CREATE TABLE gl_test.test_smt_d ON CLUSTER '{cluster}' AS gl_test.test_smt
    ENGINE = Distributed('{cluster}', 'gl_test', test_smt, cityHash64(id));

-- Insert directly to single shard (Alternatively insert using distributed table but then make sure to switch connection to a shard where row is not present)
INSERT INTO gl_test.test_smt
(id, dt, dt64, val)
VALUES('abc', toDateTime(1686036919, 'UTC'), toDateTime64(1686036919.123, 3, 'UTC'), 1);

-- Verify row was inserted
select * from gl_test.test_smt;
-- Expected: 1 row present / Actual: 1 row present

-- Connect to second shard

-- Verify row is not present
select * from gl_test.test_smt;
-- Expected: 0 row present / Actual: 0 row present

-- Verify row can be fetched using distributed table
select * from gl_test.test_smt_d;
-- Expected: 1 row present / Actual: 1 row present

-- Query with condition
select * from gl_test.test_smt_d tsd where dt64 > toDateTime64(0, 3, 'UTC');
-- Expected: 1 row present / Actual: 1 row present

-- Wrap condition in subquery
select * from gl_test.test_smt_d tsd where dt64 > (select toDateTime64(0, 3, 'UTC'));
-- [FAIL] Expected: 1 row present / Actual: 0 row present
```

**Expected behavior**

`select * from gl_test.test_smt_d tsd where dt64 > (select toDateTime64(0, 3, 'UTC'));` will return row from second shard

**Error message and/or stacktrace**

N/A

**Additional context**

I have also tested with different conditional operator and with different column types:

```sql
-- Query with = DateTime64
select * from gl_test.test_smt_d tsd where dt64 = (select toDateTime64(1686036919.123, 3, 'UTC'));
-- [PASS] Expected: 1 row present / Actual: 1 row present

-- Query with DateTime in subquery
select * from gl_test.test_smt_d tsd where dt64 > (select toDateTime(0, 'UTC'));
-- [PASS] Expected: 1 row present / Actual: 1 row present

-- Query with Int32 in subquery
select * from gl_test.test_smt_d tsd where val > (select 0);
-- [PASS] Expected: 1 row present / Actual: 1 row present
```

I have also tested with `ReplicatedMergeTree` engine:

```sql
-- drop table gl_test.test_smt_2 ON CLUSTER '{cluster}' sync
CREATE TABLE gl_test.test_smt_2 ON CLUSTER '{cluster}' (
    id String,
    dt DateTime('UTC'),
    dt64 DateTime64(3, 'UTC'),
    val Int32
    ) ENGINE ReplicatedMergeTree('/clickhouse/tables/{shard}/gl_test/test_smt_2', '{replica}')
    PARTITION BY toYYYYMM(dt)
    ORDER BY (cityHash64(id), toDate(dt), val)
    PRIMARY KEY (cityHash64(id), toDate(dt));

-- drop table gl_test.test_smt_2_d ON CLUSTER '{cluster}' sync
CREATE TABLE gl_test.test_smt_2_d ON CLUSTER '{cluster}' AS gl_test.test_smt_2
    ENGINE = Distributed('{cluster}', 'gl_test', test_smt, cityHash64(id));

INSERT INTO gl_test.test_smt_2
(id, dt, dt64, val)
VALUES('abc', toDateTime(1686036919, 'UTC'), toDateTime64(1686036919.123, 3, 'UTC'), 1);

-- Connect to second shard

-- Verify row is not present
select * from gl_test.test_smt_2;
-- Expected: 0 row present / Actual: 0 row present

-- Verify row can be fetched using distributed table
select * from gl_test.test_smt_2_d;
-- Expected: 1 row present / Actual: 1 row present

-- Query with subquery
select * from gl_test.test_smt_2_d tsd where dt64 > (select toDateTime64(0, 3, 'UTC'));
-- [PASS] Expected: 1 row present / Actual: 1 row present
```

**Comment by den-crane** [comment]
simpler:

```sql
CREATE TABLE t ( dt64 DateTime64(3, 'UTC') ) ENGINE Memory as select  '1686036919.123';

select * from remote('127.0.0.1', currentDatabase(), t)  where dt64 > (select toDateTime64(0, 3));
┌────────────────────dt64─┐
│ 2023-06-06 07:35:19.123 │
└─────────────────────────┘

set prefer_localhost_replica=0;

select * from remote('127.0.0.1', currentDatabase(), t)  where dt64 > (select toDateTime64(0, 3));
0 rows in set. Elapsed: 0.007 sec.
```

WA (assumeNotNull):

```sql
select * from remote('127.0.0.1', currentDatabase(), t) where dt64 > assumeNotNull((select toDateTime64(0, 3)));
┌────────────────────dt64─┐
│ 2023-06-06 07:35:19.123 │
└─────────────────────────┘
```

**Comment by den-crane** [comment]
> @den-crane any idea why it seems to be working fine with `ReplicatedMergeTree`?

it's not. Test better.

**Comment by zvonand** [comment]
Currently looking into this DateTime64 thing. And it looks more interesting:
```bash
stradnieks :) set prefer_localhost_replica = 0

stradnieks :) select *, (select toDateTime64(9999, 3)) from remote('127.0.0.1', system.one)

┌─dummy─┬─_subquery8─┐
│     0 │       ᴺᵁᴸᴸ │
└───────┴────────────┘

stradnieks :) select *, (select toDateTime64(10000, 3)) from remote('127.0.0.1', system.one)

┌─dummy─┬──────────────_subquery9─┐
│     0 │ 1970-01-01 03:46:40.000 │
└───────┴─────────────────────────┘

```

**Comment by shiyer7474** [comment]
I can reproduce the issue and it is well described in the above [comment](https://github.com/ClickHouse/ClickHouse/issues/50868#issuecomment-1587324935).

The wrong results will be seen if the `DateTime64 ` instance does not have a non-zero precision value(milliseconds etc) **AND** the seconds elapsed since 1970-01-01 is less then 10000. 

```
$ select toDateTime64(0, 3) from remote('127.0.0.1', system.one) settings prefer_localhost_replica=0

Received exception from server (version 24.8.1):
Code: 41. DB::Exception: Received from localhost:9000. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Cannot parse DateTime: In scope SELECT _CAST('0', 'DateTime64(3)') AS `toDateTime64(0, 3)` FROM system.one AS __table1. (CANNOT_PARSE_DATETIME)

$ select toDateTime64(9999, 3) from remote('127.0.0.1', system.one) settings prefer_localhost_replica=0

Received exception from server (version 24.8.1):
Code: 41. DB::Exception: Received from localhost:9000. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Cannot parse DateTime: In scope SELECT _CAST('9999', 'DateTime64(3)') AS `toDateTime64(9999, 3)` FROM system.one AS __table1. (CANNOT_PARSE_DATETIME)

$ select toDateTime64(10000, 3) from remote('127.0.0.1', system.one) settings prefer_localhost_replica=0

   ┌──toDateTime64(10000, 3)─┐
1. │ 1970-01-01 02:46:40.000 │
   └─────────────────────────┘
```

It may seem that the defect will not be commonly encountered, only if the input timestamp is <= `1970-01-01 02:46:40.000`. But Clickhouse is typically used as a time-series database and certainly a input timestamp value of  just "0" as a _catch all_ or _query all_ rows in a query is a good use case.

Workaround : [a bit of a hack] Specify a non-zero precision value if the input timestamp is less than `1970-01-01 02:46:40.000` and distributed query should succeed and return valid results. e.g 

```
$ select toDateTime64(0.001, 3) from remote('127.0.0.1', system.one) settings prefer_localhost_replica=0

   ┌──toDateTime64(0.001, 3)─┐
1. │ 1970-01-01 00:00:00.001 │
   └─────────────────────────┘
```

**Comment by shiyer7474** [comment]
Evaluating following options to fix this issue :

1. Enhance `Field `and `FieldVisitorToString ` to recognize Date/DateTime/DateTime64 data types and implement date/time specific serialization to string - This is a large impact change and potentially risky.

2. Try hacky code change in `ConstantNode::toASTImpl()` to some how serialize the DateTime64 constant value with trailing zeroes (i.e ".000") if fractional part of the timestamp is 0.

3. Remove explicit quoting of decimal & big-int values in `FieldVisitorToString `[code](https://github.com/ClickHouse/ClickHouse/blob/3319a5e6f82e07e69795821d92722879c811299b/src/Common/FieldVisitorToString.cpp#L22). - Tried this change, easily breaks _CAST of "large value" numeric literals (loss of exact scale semantics).

```
select toDecimal64('999999999999.821', 6) from remote('127.0.0.1', system.one) settings prefer_localhost_replica=0;
   ┌─toDecimal64('999999999999.821', 6)─┐
1. │                999999999999.821056 │ -- 1000.00 billion
   └────────────────────────────────────┘
select toDecimal64('999999999999.821', 6) from remote('127.0.0.1', system.one) settings prefer_localhost_replica=1
   ┌─toDecimal64('999999999999.821', 6)─┐
1. │                   999999999999.821 │ -- 1000.00 billion
   └────────────────────────────────────┘   
```

4. Practical fix is to print trailing zeroes for decimal field types in `FieldVisitorToString.formatQuoted().` This has can be done by passing true in the 4th parameter of `writeText()` call [here](https://github.com/ClickHouse/ClickHouse/blob/3319a5e6f82e07e69795821d92722879c811299b/src/Common/FieldVisitorToString.cpp#L25). This does not break external/human display of Decimal fields since that is done via `FunctionCast `class. `FieldVisitorToString()` is used only during AST serialization to String and trailing zeroes should not break stuff (testing that)

Background PRs : [Link](https://github.com/ClickHouse/ClickHouse/pull/27680), [Link](https://github.com/ClickHouse/ClickHouse/pull/58118)

**Comment by shiyer7474** [comment]
Option 4 has hit a dead end because it is dependent on the tolerance level of `readDateTimeText()` to "small" value strings :-

```
select toDateTime64('22.0', 3) -> 1970-01-01 00:00:22.000 (SUCCESS)
select toDateTime64('222.0',3) ->  1970-01-01 00:03:42.000 (SUCCESS)
select toDateTime64('2222.0',3); -> Exception CANNOT_PARSE_DATETIME
```
A cleaner version of option 2 that essentially emits 2 CAST's in the AST serialization looks to be good, trying that.

**Comment by shiyer7474** [comment]
Fixed using this issue : #66773 and PR : https://github.com/ClickHouse/ClickHouse/pull/67920

**Comment by den-crane** [comment]
it's not fixed 

https://fiddle.clickhouse.com/09f400b1-6939-482a-9279-be73d3b54521

**Comment by shiyer7474** [comment]
For reference, below is example of AST serialization of _nested subquery_ containing a `DateTime64 ` constant folded value

```
select *, (select toDateTime64(0, 3)) from remote('127.0.0.1', system.one) settings prefer_localhost_replica=0;
|
v
"SELECT `__table1`.`dummy` AS `dummy`, _CAST('0', 'Nullable(DateTime64(3))') AS `_subquery_1` FROM `system`.`one` AS `__table1`"
```

Hence check added for Nullable result type.
