### ISSUE TITLE
JIT compiler issue / Cannot convert column  because it is non constant in source stream but must be constant in result

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#51090]
https://fiddle.clickhouse.com/52b751b5-fa79-4865-bd9b-49aca042bc13

```sql
SELECT
    sum(c),
    toInt32((h - null::Nullable(DateTime)) / 3600) + 1 AS a
FROM
(
    SELECT count() AS c, h
    FROM ( SELECT now() AS h )
    WHERE toInt32((h - null::Nullable(DateTime)) / 3600) + 1 = 1
    GROUP BY h
)
GROUP BY a settings min_count_to_compile_expression=0;

DB::Exception: Cannot convert column 
`plus(toInt32(divide(minus(h, CAST(NULL, 'Nullable(DateTime)')), 3600)), 1)` 
because it is non constant in source stream but must be constant in result. (ILLEGAL_COLUMN)
```

WA: `compile_expressions=0`

**Comment by den-crane** [comment]
@Aaaaaaron it is fixed in 23.6
https://fiddle.clickhouse.com/8b3547ba-076f-4365-b104-823a1c078688
probably fixed here https://github.com/ClickHouse/ClickHouse/pull/50291

**Comment by Aaaaaaron** [comment]
@den-crane Hello, I cp the code and the problem still exists, can you please ask who is more familiar with this, We are very anxious to solve this problem, thanks  a lot

**Comment by Aaaaaaron** [comment]
@den-crane hello~

**Comment by Aaaaaaron** [comment]
Is anyone here😂?

**Comment by alexey-milovidov** [comment]
I checked with clickhouse-fiddle on the latest version and on a local installation and confirmed that the issue is fixed.

**Comment by Aaaaaaron** [comment]
@alexey-milovidov Hello, we currently met this problem and wanted to cherry-pick the fix, could you help to see which pr solves this problem😂(we are not able to upgrade to latest version)

**Comment by alexey-milovidov** [comment]
Just disable the `compile_expressions`, `compile_aggregate_expressions`, and it will solve the problem.

**Comment by Aaaaaaron** [comment]
> Just disable the `compile_expressions`, `compile_aggregate_expressions`, and it will solve the problem.

Currently we do this😂 but we still want to solve this bug

**Comment by den-crane** [comment]
@alexey-milovidov I believe it is worth to disable compile_expressions, compile_aggregate_expressions in 22.8 and 23.3 

https://fiddle.clickhouse.com/d609d0c7-298d-4e59-b101-a090b2863d16

**Comment by Aaaaaaron** [comment]
thanks
