### ISSUE TITLE
Error in create deltalake table in clickhouse

### ISSUE THREAD

**Issue by ArmanShakeri** [ClickHouse/ClickHouse#51134]
I want to create a clickhouse table with DeltaLake engine and I use this query:
`create table deltatable Engine=DeltaLake('http://10.19.129.78:9090/source/enrichedweblimited', aws_access_key_id, aws_secret_access_key)`

it can connect to delta table and I can see parquet files of table in trace log and it means clickhosue could connect to delta it understand structured of table and its partitions. but I got error 404
 my delta table is on ceph storage and I inserted record to the table by pyspark delta format.
Clickhouse installed stand alone on a vm and there is no sharding or clustering.
I also tried use deltalake function for select data but I got same error.
I tried S3 function and it can read parquet files.
here is the error:

[qm-nifi01] 2023.06.18 14:26:58.059152 [ 12465 ] {bfd78384-8729-4bb1-b828-21c370f010d4} <Trace> S3Client: Provider type: Unknown
[qm-nifi01] 2023.06.18 14:26:58.158064 [ 12465 ] {bfd78384-8729-4bb1-b828-21c370f010d4} <Information> AWSClient: Response status: 404, Not Found
[qm-nifi01] 2023.06.18 14:26:58.158263 [ 12465 ] {bfd78384-8729-4bb1-b828-21c370f010d4} <Information> AWSClient: AWSXmlClient: HTTP response code: 404
Resolved remote host IP address: 10.19.129.78:9090
Request ID:
Exception name:
Error message: No response body.
6 response headers:
accept-ranges : bytes
connection : close
content-length : 217
content-type : application/xml
date : Sun, 18 Jun 2023 10:56:58 GMT
x-amz-request-id : tx00000de4b56d7cf3b16f1-00648ee2fa-2d877e-default
[qm-nifi01] 2023.06.18 14:26:58.158414 [ 12465 ] {bfd78384-8729-4bb1-b828-21c370f010d4} <Information> AWSClient: If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
[qm-nifi01] 2023.06.18 14:26:58.211274 [ 12465 ] {bfd78384-8729-4bb1-b828-21c370f010d4} <Error> executeQuery: Code: 499. DB::Exception: Failed to get object info: No response body.. HTTP response code: 404. (S3_ERROR) (version 23.4.2.11 (official build)) (from 127.0.0.1:36222) (in query: create table deltatable Engine=DeltaLake('http://10.19.129.78:9090/source/enrichedweblimited','sqm_183','sqm_183')), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe3bb175 in /usr/bin/clickhouse
1. ? @ 0x9804b0d in /usr/bin/clickhouse
2. DB::S3::getObjectInfo(DB::S3::Client const&, String const&, String const&, String const&, DB::S3Settings::RequestSettings const&, bool, bool, bool) @ 0x126ad29e in /usr/bin/clickhouse
3. DB::StorageS3Source::KeysIterator::KeysIterator(DB::S3::Client const&, String const&, std::vector<String, std::allocator<String>> const&, String const&, DB::S3Settings::RequestSettings const&, std::shared_ptr<DB::IAST>, DB::Block const&, std::shared_ptr<DB::Context const>, std::vector<DB::StorageS3Source::KeyWithInfo, std::allocator<DB::StorageS3Source::KeyWithInfo>>*) @ 0x14480eb2 in /usr/bin/clickhouse
4. DB::StorageS3::createFileIterator(DB::StorageS3::Configuration const&, bool, std::shared_ptr<DB::Context const>, std::shared_ptr<DB::IAST>, DB::Block const&, std::vector<DB::StorageS3Source::KeyWithInfo, std::allocator<DB::StorageS3Source::KeyWithInfo>>*) @ 0x144899ab in /usr/bin/clickhouse
5. DB::StorageS3::getTableStructureFromDataImpl(DB::StorageS3::Configuration const&, std::optional<DB::FormatSettings> const&, std::shared_ptr<DB::Context const>) @ 0x14488f26 in /usr/bin/clickhouse
6. DB::StorageS3::StorageS3(DB::StorageS3::Configuration const&, std::shared_ptr<DB::Context const>, DB::StorageID const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, String const&, std::optional<DB::FormatSettings>, bool, std::shared_ptr<DB::IAST>) @ 0x14487a93 in /usr/bin/clickhouse
7. ? @ 0x1455c393 in /usr/bin/clickhouse
8. DB::StorageFactory::get(DB::ASTCreateQuery const&, String const&, std::shared_ptr<DB::Context>, std::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x14294dbb in /usr/bin/clickhouse
9. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::unique_ptr<DB::DDLGuard, std::default_delete<DB::DDLGuard>>&) @ 0x1397a531 in /usr/bin/clickhouse
10. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x139732a2 in /usr/bin/clickhouse
11. DB::InterpreterCreateQuery::execute() @ 0x1397fa14 in /usr/bin/clickhouse
12. ? @ 0x13f00be7 in /usr/bin/clickhouse
13. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13efe16d in /usr/bin/clickhouse
14. DB::TCPHandler::runImpl() @ 0x14cd4991 in /usr/bin/clickhouse
15. DB::TCPHandler::run() @ 0x14cea499 in /usr/bin/clickhouse
16. Poco::Net::TCPServerConnection::start() @ 0x17c5cab4 in /usr/bin/clickhouse
17. Poco::Net::TCPServerDispatcher::run() @ 0x17c5dcdb in /usr/bin/clickhouse
18. Poco::PooledThread::run() @ 0x17ddb087 in /usr/bin/clickhouse
19. Poco::ThreadImpl::runnableEntry(void*) @ 0x17dd8abd in /usr/bin/clickhouse
20. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
21. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so

0 rows in set. Elapsed: 31.693 sec.

Received exception from server (version 23.4.2):
Code: 499. DB::Exception: Received from localhost:9000. DB::Exception: Failed to get object info: No response body.. HTTP response code: 404. (S3_ERROR)

**Comment by kssenii** [comment]
please try the latest version, I assume this was fixed in https://github.com/ClickHouse/ClickHouse/pull/50232

**Comment by rjoelnorgren** [comment]
Encountered this issue in 23.6. Upgrading to 23.7.2 did not resolve:

```sql
CREATE TABLE my_db.delta
ENGINE = DeltaLake('https://my-s3-bucket.s3.us-east-1.amazonaws.com/path/to/delta/')

-- Query id: 28176727-7393-4039-bf54-a84c0f82606b


-- 0 rows in set. Elapsed: 0.155 sec. 

-- Received exception from server (version 23.7.2):
-- Code: 499. DB::Exception: Received from localhost:9000. DB::Exception: Failed to get object info: No response body.. HTTP response code: 404. (S3_ERROR)
```

**Comment by jkilpatrick-twilio** [comment]
@rjoelnorgren did you ever happen to resolve this problem?   I am getting an identical issue in 24.8.4 and I assume at this point I must just be doing something wrong. 😄

**Comment by kssenii** [comment]
Hi, we have new implementation based on delta-kernel-rs, which is available by default since 25.6 version, which also has now many issues solved, please give it a try.
