### ISSUE TITLE
Segfault in `test_storage_rabbitmq`

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#51840]
https://s3.amazonaws.com/clickhouse-test-reports/0/0fb6dd8f89800f3dcd2ca32bd20a5afc954d6978/integration_tests__release__[2_4].html

```
2023.07.05 12:37:25.795178 [ 10 ] {} <Trace> BaseDaemon: Received signal 11
2023.07.05 12:37:25.795394 [ 10 ] {} <Trace> BaseDaemon: Received signal 11
2023.07.05 12:37:25.795534 [ 291 ] {} <Fatal> BaseDaemon: ########################################
2023.07.05 12:37:25.795574 [ 291 ] {} <Fatal> BaseDaemon: (version 23.7.1.243 (official build), build id: FAC8DD0B813D4F7094FE36F868C7800F5C8066B0, git hash: 0fb6dd8f89800f3dcd2ca32bd20a5afc954d6978) (from thread 290) (no query) Received signal Segmentation fault (11)
2023.07.05 12:37:25.795591 [ 291 ] {} <Fatal> BaseDaemon: Address: 0x7f7a25ffb207. Access: read. Attempted access has violated the permissions assigned to the memory area.
2023.07.05 12:37:25.795596 [ 291 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000889cb3e 0x000000000e46d816 0x000000000e46d5f5 0x00007f7a26185b43 0x00007f7a26217a00
2023.07.05 12:37:25.795635 [ 291 ] {} <Fatal> BaseDaemon: 2. ? @ 0x000000000889cb3e in /usr/bin/clickhouse
2023.07.05 12:37:25.795641 [ 291 ] {} <Fatal> BaseDaemon: 3. ? @ 0x000000000e46d816 in /usr/bin/clickhouse
2023.07.05 12:37:25.795646 [ 291 ] {} <Fatal> BaseDaemon: 4. ? @ 0x000000000e46d5f5 in /usr/bin/clickhouse
2023.07.05 12:37:25.795652 [ 291 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00007f7a26185b43 in ?
2023.07.05 12:37:25.795657 [ 291 ] {} <Fatal> BaseDaemon: 6. ? @ 0x00007f7a26217a00 in ?
2023.07.05 12:37:25.944679 [ 291 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: CB9A8DE5BEB6590C6E386FEAE8947090)
2023.07.05 12:37:25.944787 [ 291 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
```

**Comment by alexey-milovidov** [comment]
Maybe related to https://github.com/ClickHouse/ClickHouse/issues/29315.

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/51774/759b8b9a7685f566a88e86f5db5ebccb0db34869/integration_tests__release__[2_4].html

**Comment by tavplubix** [comment]
#51932 will help to get a better stacktrace

**Comment by alexey-milovidov** [comment]
![Untitled7](https://github.com/ClickHouse/ClickHouse/assets/18581488/a8b27697-9041-48e6-9653-f0928448bf82)

**Comment by alexey-milovidov** [comment]
We fixed it.

**Comment by tavplubix** [comment]
> We fixed it.

Where? 

It still crashes sometimes: https://s3.amazonaws.com/clickhouse-test-reports/51796/9a295eca46fea2c88d1c1767fc4625b31c999572/integration_tests__release__[2_4].html

**Comment by alexey-milovidov** [comment]
Did we fix it?
