### ISSUE TITLE
Unable to create empty part due to an existing part with the same name

### ISSUE THREAD

**Issue by donatascn** [ClickHouse/ClickHouse#54079]
**Describe what's wrong**
ClickHouse version 22.8

Recently we our cluster logs started filling up with repeated warnings and errors, mentioning the same 3 parts.
I have tried deleting these parts, but clickhouse wouldn't allow it.
Also, attempted to detach/attach the table. After reattaching, the same records appeared in replication_queue and logs started to roll again.

My question would be - how could I get rid of these 3 stubborn parts?

```
2023.08.29 16:25:30.328119 [ 195 ] {} <Error> db.usage_by_user (ReplicatedMergeTreePartCheckThread): No replica has part covering 202308_0_116642_26635 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2023.08.29 16:25:30.329448 [ 195 ] {} <Warning> db.usage_by_user (fdd64ff0-b467-46d0-9f12-ea3c5c3cb2f4): Cannot commit empty part 202308_0_116642_26635 with error DB::Exception: Part 202308_0_116642_26635 (state Outdated) already exists, but it will be deleted soon
2023.08.29 16:25:30.336362 [ 195 ] {} <Warning> db.usage_by_user (ReplicatedMergeTreePartCheckThread): Cannot create empty part 202308_0_116642_26635 instead of lost. Will retry later
2023.08.29 16:25:30.826804 [ 131 ] {} <Warning> db.usage_by_user (ReplicatedMergeTreePartCheckThread): Checking part 202308_0_116606_26623
2023.08.29 16:25:30.842697 [ 131 ] {} <Warning> db.usage_by_user (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 202308_0_116606_26623 or covering part.
2023.08.29 16:25:30.858319 [ 131 ] {} <Error> db.usage_by_user (ReplicatedMergeTreePartCheckThread): No replica has part covering 202308_0_116606_26623 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2023.08.29 16:25:30.859720 [ 131 ] {} <Warning> db.usage_by_user (fdd64ff0-b467-46d0-9f12-ea3c5c3cb2f4): Cannot commit empty part 202308_0_116606_26623 with error DB::Exception: Part 202308_0_116606_26623 (state Outdated) already exists, but it will be deleted soon
2023.08.29 16:25:30.860451 [ 131 ] {} <Warning> db.usage_by_user (ReplicatedMergeTreePartCheckThread): Cannot create empty part 202308_0_116606_26623 instead of lost. Will retry later
2023.08.29 16:25:31.172425 [ 177 ] {} <Warning> db.usage_by_user (ReplicatedMergeTreePartCheckThread): Checking part 202308_0_116673_26642
2023.08.29 16:25:31.179990 [ 177 ] {} <Warning> db.usage_by_user (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 202308_0_116673_26642 or covering part.
2023.08.29 16:25:31.194484 [ 177 ] {} <Error> db.usage_by_user (ReplicatedMergeTreePartCheckThread): No replica has part covering 202308_0_116673_26642 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2023.08.29 16:25:31.195620 [ 177 ] {} <Warning> db.usage_by_user (fdd64ff0-b467-46d0-9f12-ea3c5c3cb2f4): Cannot commit empty part 202308_0_116673_26642 with error DB::Exception: Part 202308_0_116673_26642 (state Outdated) already exists, but it will be deleted soon
2023.08.29 16:25:31.196340 [ 177 ] {} <Warning> db.usage_by_user (ReplicatedMergeTreePartCheckThread): Cannot create empty part 202308_0_116673_26642 instead of lost. Will retry later
2023.08.29 16:25:31.595658 [ 166 ] {} <Warning> db.usage_by_user (ReplicatedMergeTreePartCheckThread): Checking part 202308_0_116642_26635
2023.08.29 16:25:31.602923 [ 166 ] {} <Warning> db.usage_by_user (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 202308_0_116642_26635 or covering part.
2023.08.29 16:25:31.613622 [ 166 ] {} <Error> db.usage_by_user (ReplicatedMergeTreePartCheckThread): No replica has part covering 202308_0_116642_26635 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2023.08.29 16:25:31.614766 [ 166 ] {} <Warning> db.usage_by_user (fdd64ff0-b467-46d0-9f12-ea3c5c3cb2f4): Cannot commit empty part 202308_0_116642_26635 with error DB::Exception: Part 202308_0_116642_26635 (state Outdated) already exists, but it will be deleted soon
2023.08.29 16:25:31.615407 [ 166 ] {} <Warning> db.usage_by_user (ReplicatedMergeTreePartCheckThread): Cannot create empty part 202308_0_116642_26635 instead of lost. Will retry later
2023.08.29 16:25:32.196667 [ 148 ] {} <Warning> db.usage_by_user (ReplicatedMergeTreePartCheckThread): Checking part 202308_0_116606_26623
```

```
SELECT *
FROM system.replication_queue
FORMAT Vertical

Row 1:
──────
database:               db
table:                  usage_by_user
replica_name:           node-3-0
position:               0
node_name:              queue-0000173166
type:                   GET_PART
create_time:            2023-08-16 13:48:33
required_quorum:        0
source_replica:
new_part_name:          202308_0_116673_26642
parts_to_merge:         []
is_detach:              0
is_currently_executing: 0
num_tries:              810
last_exception:         Code: 234. DB::Exception: No active replica has part 202308_0_116673_26642 or covering part. (NO_REPLICA_HAS_PART)
last_attempt_time:      2023-08-30 15:38:30
num_postponed:          1621
postpone_reason:        Not executing log entry queue-0000173166 for part 202308_0_116673_26642 because it is not disjoint with part 202308_0_116606_26623 that is currently executing.
last_postpone_time:     2023-08-30 15:38:31
merge_type:

Row 2:
──────
database:               db
table:                  usage_by_user
replica_name:           node-3-0
position:               1
node_name:              queue-0000173170
type:                   GET_PART
create_time:            2023-08-16 13:45:51
required_quorum:        0
source_replica:
new_part_name:          202308_0_116642_26635
parts_to_merge:         []
is_detach:              0
is_currently_executing: 0
num_tries:              810
last_exception:         Code: 234. DB::Exception: No active replica has part 202308_0_116642_26635 or covering part. (NO_REPLICA_HAS_PART)
last_attempt_time:      2023-08-30 15:38:30
num_postponed:          1620
postpone_reason:        Not executing log entry queue-0000173170 for part 202308_0_116642_26635 because it is not disjoint with part 202308_0_116606_26623 that is currently executing.
last_postpone_time:     2023-08-30 15:38:31
merge_type:

Row 3:
──────
database:               db
table:                  usage_by_user
replica_name:           node-3-0
position:               2
node_name:              queue-0000173171
type:                   GET_PART
create_time:            2023-08-16 13:42:13
required_quorum:        0
source_replica:
new_part_name:          202308_0_116606_26623
parts_to_merge:         []
is_detach:              0
is_currently_executing: 0
num_tries:              810
last_exception:         Code: 234. DB::Exception: No active replica has part 202308_0_116606_26623 or covering part. (NO_REPLICA_HAS_PART)
last_attempt_time:      2023-08-30 15:38:31
num_postponed:          1621
postpone_reason:        Not executing log entry queue-0000173171 for part 202308_0_116606_26623 because it is not disjoint with part 202308_0_116642_26635 that is currently executing.
last_postpone_time:     2023-08-30 15:38:30
merge_type:

3 rows in set. Elapsed: 0.006 sec.
```

```
ALTER TABLE usage_by_client_persistent_local
    DROP PART '202308_0_116642_26635'

0 rows in set. Elapsed: 0.253 sec.

Received exception from server (version 22.8.20):
Code: 232. DB::Exception: Received from clickhouse.stage.our_host.io:9000. DB::Exception: No part 202308_0_116642_26635 in committed state. (NO_SUCH_DATA_PART)
```

```
ALTER TABLE usage_by_client_persistent_local
    DROP DETACHED PART '202308_0_116642_26635'
SETTINGS allow_drop_detached = 1

0 rows in set. Elapsed: 0.212 sec.

Received exception from server (version 22.8.20):
Code: 233. DB::Exception: Received from clickhouse.stage.our_host.io:9000. DB::Exception: Detached part "202308_0_116642_26635" not found. (BAD_DATA_PART_NAME)
```

**Comment by tavplubix** [comment]
You don't need to do anything these errors are harmless, and they will disappear after a while (when the outdated part is deleted). This behavior was improved in recent releases: currently `ReplicatedMergeTreePartCheckThread` waits for outdated parts to be removed if necessary

**Comment by donatascn** [comment]
Amazing, thank you!

**Comment by donatascn** [comment]
@tavplubix from what I read in related github issues, this should have been resolved in 20.* or 21.* versions - https://github.com/ClickHouse/ClickHouse/pull/20335. Which version, in your opinion, should we use to get rid of the verbose logging?

**Comment by tavplubix** [comment]
https://github.com/ClickHouse/ClickHouse/pull/20335 is irrelevant to `ReplicatedMergeTreePartCheckThread`, I meant https://github.com/ClickHouse/ClickHouse/pull/51801, it's in 23.7

**Comment by monadbobo** [comment]
> You don't need to do anything. These errors are harmless, and they will disappear after a while (when the outdated part is deleted). This behavior was improved in recent releases: currently `ReplicatedMergeTreePartCheckThread` waits for outdated parts to be removed if necessary

Hello, I have encountered the same error as him, except that my data can never be deleted (2 clickhouses are distributed, TTL is set to 1 day, but after 10 days, one node data is still not deleted) Delete, the data of the other node is normal), and then print continuously: 
`2023.12.15 07:59:07.292696 [ 155 ] {} <Warning> logs.logs_local (8ef0aec8-df5f-4d23-b067-5e818cfe27e1): Cannot commit empty part 20231205_40708_40716_4 with error DB::Exception: Tried to create empty part 20231205_40708_40716_4, but it replaces existing parts 20231205_40708_40714_3, 20231205_40715_40715_0, 20231205_40716_40716_0.
2023.12.15 07:59:08.377118 [ 175 ] {} <Information> logs.logs_local (8ef0aec8-df5f-4d23-b067-5e818cfe27e1): Will drop empty part 20231205_40716_40716_0
2023.12.15 07:59:46.206163 [ 124 ] {} <Warning> logs.logs_local (8ef0aec8-df5f-4d23-b067-5e818cfe27e1): Cannot commit empty part 20231205_40708_40716_4 with error DB::Exception: Tried to create empty part 20231205_40708_40716_4, but it replaces existing parts 20231205_40708_40714_3, 20231205_40715_40715_0, 20231205_40716_40716_0.
2023.12.15 07:59:47.266288 [ 101 ] {} <Information> logs.logs_local (8ef0aec8-df5f-4d23-b067-5e818cfe27e1): Will drop empty part 20231205_40716_40716_0
2023.12.15 08:00:24.011263 [ 150 ] {} <Warning> logs.logs_local (8ef0aec8-df5f-4d23-b067-5e818cfe27e1): Cannot commit empty part 20231205_40708_40716_4 with error DB::Exception: Tried to create empty part 20231205_40708_40716_4, but it replaces existing parts 20231205_40708_40714_3, 20231205_40715_40715_0, 20231205_40716_40716_0.
2023.12.15 08:00:25.558117 [ 156 ] {} <Information> logs.logs_local (8ef0aec8-df5f-4d23-b067-5e818cfe27e1): Will drop empty part 20231205_40716_40716_0
2023.12.15 08:01:03.010302 [ 141 ] {} <Warning> logs.logs_local (8ef0aec8-df5f-4d23-b067-5e818cfe27e1): Cannot commit empty part 20231205_40708_40716_4 with error DB::Exception: Tried to create empty part 20231205_40708_40716_4, but it replaces existing parts 20231205_40708_40714_3, 20231205_40715_40715_0, 20231205_40716_40716_0.`
