### ISSUE TITLE
PostgreSQL connectivity broken after unclean shutdown of connections

### ISSUE THREAD

**Issue by jmaicher** [ClickHouse/ClickHouse#67069]
**Describe what's wrong**

We have a couple of PostgreSQL databases connected via the PostgreSQL engine:

```sql
CREATE DATABASE postgres_db ENGINE = PostgreSQL('<host>', '<database>', '<user>', '<password>', '<schema>', 1)
```

Since upgrading from `24.1.8.22` to `24.5.4.49`, we observe persistent connectivity issues, e.g. in case of temporary network issues, with the following logs:

```
2024.07.24 02:32:25.912095 [ 450706 ] {0acc93a5-baa5-467a-bf04-25a0c8f45a16} <Error> virtual DatabaseTablesIteratorPtr DB::DatabasePostgreSQL::getTablesIterator(ContextPtr, const FilterByNameFunction &, bool) const: std::exception. Code: 1001, type: pqxx::failure, e.what() = SSL SYSCALL error: Success
, Stack trace (when copying this message, always include the lines below):

0. pqxx::connection::make_result(pg_result*, std::shared_ptr<String> const&, std::basic_string_view<char, std::char_traits<char>>) @ 0x00000000168be978
1. pqxx::connection::exec(std::shared_ptr<String>, std::basic_string_view<char, std::char_traits<char>>) @ 0x00000000168c0298
2. pqxx::transaction_base::direct_exec(std::basic_string_view<char, std::char_traits<char>>, std::basic_string_view<char, std::char_traits<char>>) @ 0x00000000168ca0ce
3. pqxx::internal::basic_transaction::basic_transaction(pqxx::connection&, pqxx::zview) @ 0x00000000168c7c2e
4. DB::fetchPostgreSQLTablesList(pqxx::connection&, String const&) @ 0x000000000fe4f304
5. DB::DatabasePostgreSQL::getTablesIterator(std::shared_ptr<DB::Context const>, std::function<bool (String const&)> const&, bool) const @ 0x000000000fe34f2a
6. DB::ReadFromSystemTables::applyFilters(DB::ActionDAGNodes) @ 0x000000000f02130e
7. DB::QueryPlanOptimizations::optimizePrimaryKeyCondition(std::vector<DB::QueryPlanOptimizations::Frame, std::allocator<DB::QueryPlanOptimizations::Frame>> const&) @ 0x00000000123a3e48
8. DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&) @ 0x00000000123a2ac3
9. DB::QueryPlan::optimize(DB::QueryPlanOptimizationSettings const&) @ 0x0000000012309cf6
10. DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x0000000012308bae
11. DB::InterpreterSelectWithUnionQuery::execute() @ 0x0000000010abf0d7
12. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000010e35de3
13. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&, String const&, std::shared_ptr<DB::Context const> const&, std::optional<DB::FormatSettings> const&)>) @ 0x0000000010e3aa2e
14. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000011e2ffd4
15. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000011e35265
16. DB::HTTPServerConnection::run() @ 0x0000000011eb2a03
17. Poco::Net::TCPServerConnection::start() @ 0x0000000014776367
18. Poco::Net::TCPServerDispatcher::run() @ 0x00000000147767f9
19. Poco::PooledThread::run() @ 0x000000001486cc61
20. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001486b23d
21. ? @ 0x00007fd8d7694ac3
22. ? @ 0x00007fd8d7726850
 (version 24.5.4.49 (official build))

```

The problem was very likely introduced with the switch from boringssl to OpenSSL (https://github.com/ClickHouse/ClickHouse/pull/59870) with the root cause in libpq, where `SSL_ERROR_SYSCALL` was incorrectly handled up until recently (see [patch](https://github.com/postgres/postgres/commit/0a5c46a7a488f2f4260a90843bb9de6c584c7f4e)).

What happens is SSL_ERROR_SYSCALL is returned by OpenSSL without setting errno, libpq doesn't return ECONNRESET on read/write and does not reset the connection (remains open), libpqxx [doesn't raise `pqxx::broken_connection`](https://github.com/ClickHouse/libpqxx/blob/master/src/connection.cxx#L194-L198) and the connection pool in ClickHouse [doesn't update the connection](https://github.com/ClickHouse/ClickHouse/blob/2a327107b637ef4db2bd403e44ab953ec02595f9/src/Core/PostgreSQL/Connection.cpp#L71-L75). Since this usually happens for all connections at the same time, the connectivity to the PostgreSQL database is completely broken until the connection pool is reset (e.g. by re-creating the database in ClickHouse).   

The problem in libpq was fixed with https://github.com/postgres/postgres/commit/0a5c46a7a488f2f4260a90843bb9de6c584c7f4e.

I already prepared and tested the fix: https://github.com/ClickHouse/libpq/pull/10

**Does it reproduce on the most recent release?**

Yes, reproduces on master

**How to reproduce**

* Start postgres server
* Create ClickHouse database with PostgreSQL engine (see above)
* Simulate unclean shutdown of connections (e.g. kill postgres server)
* Start postgres server
* Query ClickHouse database (or `system.tables`)

**Expected behavior**

It is still possible to query the database in ClickHouse (connection pool recovers from this)

**Error message and/or stacktrace**

See above

**Comment by jmaicher** [comment]
Would be nice to get some eyes on this 🙏

**Comment by max-vostrikov** [comment]
@jmaicher I was not able to reproduce this neither on 24.5.4.49 or on head 24.8
Did i understood correctly that it meant be fixed with latest Postgres?
If if did, what version of Postgres were you using so we can try to reproduce it?

**Comment by jmaicher** [comment]
> Did i understood correctly that it meant be fixed with latest Postgres? If if did, what version of Postgres were you using so we can try to reproduce it?

Yes, it was [fixed](https://github.com/postgres/postgres/commit/0a5c46a7a488f2f4260a90843bb9de6c584c7f4e) in libpq, the client interface. The server version is irrelevant.

> I was not able to reproduce this neither on 24.5.4.49 or on head 24.8

Not sure if you tried, but you can only trigger the problematic code path in libpq ([fe-secure-openssl.c](https://github.com/ClickHouse/libpq/blob/master/fe-secure-openssl.c#L204)) when connecting via SSL.

The easiest local reproducer would be something like this:
```bash
# generate self-signed server certificate
openssl req -new -x509 -days 365 -nodes -text -out server.crt   -keyout server.key -subj "/CN=localhost"
# set permissions accordingly, otherwise postgres complains
chmod og-rwx server.key
chown 70:70 server.key
# start postgres with ssl on
docker run -d -p5432:5432 -e POSTGRES_HOST_AUTH_METHOD=trust -v "$(pwd)/server.crt:/var/lib/postgresql/server.crt:ro" -v "$(pwd)/server.key:/var/lib/postgresql/server.key:ro" postgres:16-alpine -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key

# start clickhouse server
./build/programs/clickhouse server

# start clickhouse client
./build/programs/clickhouse client
# create database with postgres engine
:) create database postgres ENGINE = PostgreSQL('localhost:5432', 'postgres', 'postgres', '');

# kill postgres process via SIGKILL (no graceful shutdown)
ps auxf|grep "postgres -c ssl"
kill -9 PID

# trigger postgres query from ClickHouse
:) select * from system.tables;

# check server logs for error
Code: 1001, type: pqxx::failure, e.what() = SSL SYSCALL error: Success

# restart postgres, trigger another postgres query, see that error persists
```
If you build against https://github.com/ClickHouse/libpq/pull/10, the connection is closed (different error logged) and it recovers when postgres comes up again.

We can certainly write an integration test for this, but since it's a bug in libpq, and it has been fixed upstream, I would just [cherry-pick the fix](https://github.com/ClickHouse/libpq/pull/10).

**Comment by jmaicher** [comment]
Any progress on this? We still see this issue regularly, and it's a hassle to fix manually.

@max-vostrikov I see we can reproduce the issue with https://github.com/ClickHouse/ClickHouse/pull/68033, can you verify that https://github.com/ClickHouse/libpq/pull/10 fixes it?

**Comment by rschu1ze** [comment]
Unfortunately, ClickHouse's libpq and libpqxx submodules are in an abhorrent state, they are a wild mix of custom patches on top of an outdated code state. Before we make it worse by adding more poop to the pile, let me please first try to clean these submodules up.

**Comment by rschu1ze** [comment]
I'll continue once above two PRs are in.

**Comment by jmaicher** [comment]
Any chance to get this back-ported into 24.8 LTS?

**Comment by rschu1ze** [comment]
The number of required PRs and their size would unfortunately go far beyond what is reasonable for an LTS release.
