### ISSUE TITLE
Not found column _row_exists in block during MATERIALIZE PROJECTION mutation

### ISSUE THREAD

**Issue by nikita-vanyasin** [ClickHouse/ClickHouse#67314]
> A clear and concise description of what works not as it is supposed to.
1) Have some table with many partitions (1m rows, 10 partitions)
2) Run few lightweight deletes
3) Create and materialize PROJECTION
4) Mutation fails with NOT_FOUND_COLUMN_IN_BLOCK error (Not found column _row_exists in block)

**Does it reproduce on the most recent release?**

Yes, tested on v24.6.3.70

**How to reproduce**

* Which ClickHouse server version to use
* v24.6.3.70
* Queries to run that lead to an unexpected result

Fiddle link: https://fiddle.clickhouse.com/92749ce5-4c90-429d-a885-afc788758991

```
CREATE TABLE mytable(    `id` UUID,    `date` Date,    `page` String,    `query` String,    `clicks` UInt32,    `ctr` Float32,    `impressions` UInt32,    `position` Float32) ENGINE = ReplacingMergeTree PARTITION BY id PRIMARY KEY (id, date, page, query) ORDER BY (id, date, page, query);

INSERT INTO mytable SELECT '40dc70cb-db67-4ae8-8cd8-b8f3c5592ccc', now()-randUniform(1, 1000000.), concat('page_', toString(number)), concat('query_', toString(number)), randUniform(0, 1000.), randUniform(0.0, 1.0), randUniform(0, 10000.), randUniform(0, 100.)  FROM numbers(100000);

INSERT INTO mytable SELECT '52542573-db67-4ae8-8cd8-b8f3c5592ccc', now()-randUniform(1, 1000000.), concat('page_', toString(number)), concat('query_', toString(number)), randUniform(0, 1000.), randUniform(0.0, 1.0), randUniform(0, 10000.), randUniform(0, 100.)  FROM numbers(100000);

INSERT INTO mytable SELECT '00000000-db67-4ae8-8cd8-b8f3c5592ccc', now()-randUniform(1, 1000000.), concat('page_', toString(number)), concat('query_', toString(number)), randUniform(0, 1000.), randUniform(0.0, 1.0), randUniform(0, 10000.), randUniform(0, 100.)  FROM numbers(700000);

SELECT count() from mytable;
DELETE FROM mytable WHERE impressions > 300 AND impressions < 900;
DELETE FROM mytable WHERE page LIKE '%000%';
DELETE FROM mytable WHERE page LIKE '%020%';
SELECT count() from mytable;
SELECT count() from system.parts WHERE table = 'mytable';

ALTER TABLE mytable ADD PROJECTION my_proj (SELECT id, date, page, query, clicks, ctr, impressions, position ORDER BY id, page, query);


ALTER TABLE mytable MATERIALIZE PROJECTION my_proj;
SELECT sleep(3);
SELECT * from system.mutations where is_done = 0 FORMAT VERTICAL;
```

**Expected behavior**

Expected the mutation to succeed. Lightweight delete is important step - without it mutation completes successfully. The problem does not seem to reproduce when there is only one part in table.

**Additional context**

Not sure if this is related to https://github.com/ClickHouse/ClickHouse/issues/50991

**Comment by jsc0218** [comment]
Would you mind to give a minimal reproducible example?

**Comment by nikita-vanyasin** [comment]
> Would you mind to give a minimal reproducible example?

Hi @jsc0218 
I was able to reproduce with randomly generated data. I've updated the issue description.
Also added a fiddle link: https://fiddle.clickhouse.com/92749ce5-4c90-429d-a885-afc788758991

**Comment by nikita-vanyasin** [comment]
Might be related too?
https://github.com/ClickHouse/ClickHouse/issues/49790

**Comment by nikita-vanyasin** [comment]
More links:
- https://github.com/ClickHouse/ClickHouse/issues/50613
- https://github.com/ClickHouse/ClickHouse/issues/50613
- https://github.com/ClickHouse/ClickHouse/issues/50991

**Comment by jsc0218** [comment]
@nikita-vanyasin sorry for replying late, the issue can been solved by following command in the fiddle before the materialize statement: `alter table mytable modify setting deduplicate_merge_projection_mode= 'drop';` The root cause is [here](https://github.com/ClickHouse/ClickHouse/issues/24778), which has been solved in the latest master since 24.8.

**Comment by gabrielmcg44** [comment]
I am still having this error after updating to 24.8.4.13
I am using ENGINE = MergeTree and without partitions

It does not raise an error on fiddle though

https://fiddle.clickhouse.com/c5ef6462-9a6f-4d43-838e-3b751274d446

On my server, I got

```
<img width="1114" alt="Screenshot 2024-09-20 at 11 02 38" src="https://github.com/user-attachments/assets/e577061e-c859-4a00-bdf5-aef495796dbf">
```

**Comment by jsc0218** [comment]
@gabrielmcg44 It is not an error. mutation is done asyncly. Your information shows it is still under progress. Wait a few more seconds until id_done = 1.
