### ISSUE TITLE
Another month, another data race in librdkafka

### ISSUE THREAD

**Issue by antaljanosbenjamin** [ClickHouse/ClickHouse#68327]
```
E           WARNING: ThreadSanitizer: data race (pid=1)
E             Write of size 8 at 0x727800238158 by thread T1073 (mutexes: read M0, write M1, write M2):
E               #0 __tsan_memset <null> (clickhouse+0x75490f9) (BuildId: 90366420cbcc5560ef2c130c027a47d72fa9f511)
E               #1 rd_avg_rollover build_docker/./contrib/librdkafka/src/rdavg.h:174:2 (clickhouse+0x1e101968) (BuildId: 90366420cbcc5560ef2c130c027a47d72fa9f511)
E               #2 rd_kafka_stats_emit_avg build_docker/./contrib/librdkafka/src/rdkafka.c:1354:9 (clickhouse+0x1e101968)
E               #3 rd_kafka_stats_emit_all build_docker/./contrib/librdkafka/src/rdkafka.c:1717:17 (clickhouse+0x1e100085) (BuildId: 90366420cbcc5560ef2c130c027a47d72fa9f511)
E               #4 rd_kafka_stats_emit_tmr_cb build_docker/./contrib/librdkafka/src/rdkafka.c:1898:2 (clickhouse+0x1e100085)
E               #5 rd_kafka_timers_run build_docker/./contrib/librdkafka/src/rdkafka_timer.c:288:4 (clickhouse+0x1e1ce5ef) (BuildId: 90366420cbcc5560ef2c130c027a47d72fa9f511)
E               #6 rd_kafka_thread_main build_docker/./contrib/librdkafka/src/rdkafka.c:2021:3 (clickhouse+0x1e0fbdc9) (BuildId: 90366420cbcc5560ef2c130c027a47d72fa9f511)
E               #7 _thrd_wrapper_function build_docker/./contrib/librdkafka/src/tinycthread.c:576:9 (clickhouse+0x1e1e42fb) (BuildId: 90366420cbcc5560ef2c130c027a47d72fa9f511)
E           
E             Previous read of size 8 at 0x727800238158 by thread T1072:
E               #0 rd_kafka_broker_timeout_scan build_docker/./contrib/librdkafka/src/rdkafka_broker.c:881:51 (clickhouse+0x1e0e7c62) (BuildId: 90366420cbcc5560ef2c130c027a47d72fa9f511)
E               #1 rd_kafka_broker_ops_io_serve build_docker/./contrib/librdkafka/src/rdkafka_broker.c:3416:17 (clickhouse+0x1e0e7c62)
E               #2 rd_kafka_broker_consumer_serve build_docker/./contrib/librdkafka/src/rdkafka_broker.c:4975:17 (clickhouse+0x1e0e353e) (BuildId: 90366420cbcc5560ef2c130c027a47d72fa9f511)
E               #3 rd_kafka_broker_serve build_docker/./contrib/librdkafka/src/rdkafka_broker.c:5080:17 (clickhouse+0x1e0e353e)
E               #4 rd_kafka_broker_thread_main build_docker/./contrib/librdkafka/src/rdkafka_broker.c:5237:25 (clickhouse+0x1e0dcfb9) (BuildId: 90366420cbcc5560ef2c130c027a47d72fa9f511)
E               #5 _thrd_wrapper_function build_docker/./contrib/librdkafka/src/tinycthread.c:576:9 (clickhouse+0x1e1e42fb) (BuildId: 90366420cbcc5560ef2c130c027a47d72fa9f511)
```

[Build report](https://s3.amazonaws.com/clickhouse-test-reports/68233/897b8d5a88a69b8831ab489c2bea9d32d0cf06dd/ci_running.html), [logs](https://s3.amazonaws.com/clickhouse-test-reports/68233/897b8d5a88a69b8831ab489c2bea9d32d0cf06dd/integration_tests__tsan__[6_6]//home/ubuntu/actions-runner/_work/_temp/test/output_dir/integration_run_test_storage_kafka_test_py_0.log).

**Comment by antaljanosbenjamin** [comment]
It is very similar to #60443, but I think that should have been fixed by #66311. Will take a look at it soon. The history of these data races is a bit messy, maybe @azat can answer it: the mentioned PR should have fixed issue too, right?

**Comment by CheSema** [comment]
It still happens at server shutdown

https://s3.amazonaws.com/clickhouse-test-reports/68800/21a39e6b50c6060a701f8fee8116685e9f211583/integration_tests__tsan__[6_6]//home/ubuntu/actions-runner/_work/_temp/test/output_dir/integration_run_test_storage_kafka_test_py_0.log

```
E           Exception: Sanitizer assert found for instance Local: Unknown group==================
E           WARNING: ThreadSanitizer: data race (pid=1)
E             Write of size 8 at 0x727800240558 by thread T1072 (mutexes: read M0, write M1, write M2):
E               #0 __tsan_memset <null> (clickhouse+0x774d0f9) (BuildId: 3917836043931f03ca6e377bdabf8a34f3fa6ee1)
E               #1 rd_avg_rollover build_docker/./contrib/librdkafka/src/rdavg.h:174:2 (clickhouse+0x1eaf0f48) (BuildId: 3917836043931f03ca6e377bdabf8a34f3fa6ee1)
E               #2 rd_kafka_stats_emit_avg build_docker/./contrib/librdkafka/src/rdkafka.c:1354:9 (clickhouse+0x1eaf0f48)
E               #3 rd_kafka_stats_emit_all build_docker/./contrib/librdkafka/src/rdkafka.c:1717:17 (clickhouse+0x1eaef665) (BuildId: 3917836043931f03ca6e377bdabf8a34f3fa6ee1)
E               #4 rd_kafka_stats_emit_tmr_cb build_docker/./contrib/librdkafka/src/rdkafka.c:1898:2 (clickhouse+0x1eaef665)
E               #5 rd_kafka_timers_run build_docker/./contrib/librdkafka/src/rdkafka_timer.c:288:4 (clickhouse+0x1ebbdbcf) (BuildId: 3917836043931f03ca6e377bdabf8a34f3fa6ee1)
E               #6 rd_kafka_thread_main build_docker/./contrib/librdkafka/src/rdkafka.c:2021:3 (clickhouse+0x1eaeb3a9) (BuildId: 3917836043931f03ca6e377bdabf8a34f3fa6ee1)
E               #7 _thrd_wrapper_function build_docker/./contrib/librdkafka/src/tinycthread.c:576:9 (clickhouse+0x1ebd38db) (BuildId: 3917836043931f03ca6e377bdabf8a34f3fa6ee1)
E           
E             Previous read of size 8 at 0x727800240558 by thread T1071:
E               #0 rd_kafka_broker_timeout_scan build_docker/./contrib/librdkafka/src/rdkafka_broker.c:881:51 (clickhouse+0x1ead7242) (BuildId: 3917836043931f03ca6e377bdabf8a34f3fa6ee1)
E               #1 rd_kafka_broker_ops_io_serve build_docker/./contrib/librdkafka/src/rdkafka_broker.c:3416:17 (clickhouse+0x1ead7242)
E               #2 rd_kafka_broker_consumer_serve build_docker/./contrib/librdkafka/src/rdkafka_broker.c:4975:17 (clickhouse+0x1ead2b1e) (BuildId: 3917836043931f03ca6e377bdabf8a34f3fa6ee1)
E               #3 rd_kafka_broker_serve build_docker/./contrib/librdkafka/src/rdkafka_broker.c:5080:17 (clickhouse+0x1ead2b1e)
E               #4 rd_kafka_broker_thread_main build_docker/./contrib/librdkafka/src/rdkafka_broker.c:5237:25 (clickhouse+0x1eacc599) (BuildId: 3917836043931f03ca6e377bdabf8a34f3fa6ee1)
E               #5 _thrd_wrapper_function build_docker/./contrib/librdkafka/src/tinycthread.c:576:9 (clickhouse+0x1ebd38db) (BuildId: 3917836043931f03ca6e377bdabf8a34f3fa6ee1)
```

**Comment by rschu1ze** [comment]
According to CI history, this one didn't occur in a long time.
Please re-open if there are new occurrences.
