### ISSUE TITLE
Small-valued DateTime parameters in distributed queries are sent to remote nodes in an unparseable format

### ISSUE THREAD

**Issue by michaelsmithxyz** [ClickHouse/ClickHouse#69079]
This issue affects versions 23.10 through the latest version when `allow_experimental_analyzer` is set to `0`. I think it was introduced by this change in 23.10: https://github.com/ClickHouse/ClickHouse/pull/55146

That PR disallows this expression, which I understand from the discussion to have never been intentionally allowed:
```
SELECT _CAST('0', 'DateTime64')

Elapsed: 0.005 sec.

Received exception from server (version 24.8.2):
Code: 41. DB::Exception: Received from localhost:9002. DB::Exception: Cannot parse DateTime: While processing _CAST('0', 'DateTime64'). (CANNOT_PARSE_DATETIME)
```

However, this bad `_CAST('0', 'DateTime64')` expression can be generated in the remote query sent to another node if `DateTime64` query parameters are used. For example, this fails when it shouldn't:

```
set allow_experimental_analyzer=0
set param_dt='1970-01-01T00:00:00.000'

SELECT hostname()
FROM remote('clickhouse-0,clickhouse-1', view(
    SELECT now() AS date
))
WHERE date > {dt:DateTime64}

Query id: 8d77c883-cc36-4133-9446-ada482043ef0

┌─hostname()───┐
│ clickhouse-0 │
└──────────────┘
→ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)
1 row in set. Elapsed: 0.017 sec.

Received exception from server (version 24.8.2):
Code: 41. DB::Exception: Received from localhost:9002. DB::Exception: Received from clickhouse-1:9000. DB::Exception: Cannot parse DateTime: While processing (now() AS date) > _CAST('0', 'DateTime64'). (CANNOT_PARSE_DATETIME)
```

In this example, `clickhouse-1` is sent a query that looks like this:
```sql
SELECT hostname() FROM view(SELECT now() AS `date` HAVING `date` > _CAST('0', 'DateTime64')) WHERE `date` > _CAST('0', 'DateTime64')
```

This can happen for any small `DateTime` value:
```
set allow_experimental_analyzer=0
set param_dt='1970-01-01T01:00:00.000'

SELECT hostname()
FROM remote('clickhouse-0,clickhouse-1', view(
    SELECT now() AS date
))
WHERE date > {dt:DateTime64}

Query id: 27ecbf3e-03af-4cb8-b7bb-5e8d8c386a0a

┌─hostname()───┐
│ clickhouse-0 │
└──────────────┘
↗ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)
1 row in set. Elapsed: 0.009 sec.

Received exception from server (version 24.8.2):
Code: 41. DB::Exception: Received from localhost:9002. DB::Exception: Received from clickhouse-1:9000. DB::Exception: Cannot parse DateTime: While processing (now() AS date) > _CAST('3600', 'DateTime64'). (CANNOT_PARSE_DATETIME)
```

Note that to reproduce the issue, it seems like you do need to have a real remote node. For example, this works: https://fiddle.clickhouse.com/bff60dd6-907b-427d-8721-94b06832ccde

**Comment by shiyer7474** [comment]
This should be same as issue : https://github.com/ClickHouse/ClickHouse/issues/50868 and fixed in https://github.com/ClickHouse/ClickHouse/pull/68323

**Comment by michaelsmithxyz** [comment]
@shiyer7474 I'm not sure that that PR fixes this issue. I tried the reproduction steps in v24.8.3.59, which I believe has the fix you linked, and the same issue still occurs

**Comment by shiyer7474** [comment]
Can you please check value of `allow_experimental_analyzer`? If it is 0 when the issue is seen, can you retry with setting it to 1?

https://fiddle.clickhouse.com/8397636f-5cd6-484a-8893-f0cc33a4c630

**Comment by michaelsmithxyz** [comment]
@shiyer7474 Yep, it does work when `allow_experimental_analyzer` is set to 1. I thought I'd tested the combination, but I guess not. We have it disabled in our environments due to other regressions (namely https://github.com/ClickHouse/ClickHouse/issues/69074)

**Comment by yariks5s** [comment]
> Yep, it does work when `allow_experimental_analyzer` is set to 1

If it works with a new analyzer, I think this is no longer a problem because the new analyzer is enabled by default.
