### ISSUE TITLE
Logical error: 'offsets[i] > offsets[i - 1]' with Wide MergeTree part + read_in_order_two_level_merge_threshold=1 + max_threads=1

### ISSUE THREAD

**Issue by fm4v** [ClickHouse/ClickHouse#69310]
When I was on duty I've found this case with Variant type:
```
CREATE OR REPLACE TABLE test(
    key String,
    val Map(String, Variant(String, Int32, DateTime64(3, 'UTC')))
) engine = ReplicatedMergeTree('/clickhouse/tables/{database}/table', '1')
order by key;

/* Some data should be inserted */
insert into test VALUES ('a', {'a':'a', 'b':1, 'c': '2020-01-01 10:10:10.11'});
insert into test VALUES ('', {'':'xx', '':4});
insert into test VALUES ('', {'x':'xx'});
insert into test VALUES ('', {});
insert into test VALUES ('a', {'a':'a', 'b':1, 'c': '2020-01-01 10:10:10'});
insert into test VALUES ('a', {'a':'b', 'b':1, 'c': '2020-01-01'});
insert into test VALUES ('z', {'a':'a'});

insert into test VALUES ('a', {'a': Null});
insert into test VALUES ('a', {'a': Null, 'a': Null});
insert into test VALUES ('a', {'a': Null, 'c': Null});

SELECT variantElement(arrayJoin(mapValues(val)), 'String') FROM test ORDER BY ALL;
```
I tried to reproduce it and have no luck, then i added this case as test and it finally fails in flaky check on 24.9:

https://s3.amazonaws.com/clickhouse-test-reports/68155/77a707e37a38cecdde7327c4ff00d0e67a0db852/stateless_tests_flaky_check__asan_.html

PR with test: https://github.com/ClickHouse/ClickHouse/pull/68155

```
2024-09-06 01:57:21 Reason: server died 32
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:55.492387 [ 2337 ] {c5a5439d-3740-4579-a58c-1fb57f0c7fb6} <Fatal> : Logical error: 'offsets[i] > offsets[i - 1]'.
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:55.582766 [ 2337 ] {c5a5439d-3740-4579-a58c-1fb57f0c7fb6} <Fatal> : Stack trace (when copying this message, always include the lines below):
2024-09-06 01:57:21 
2024-09-06 01:57:21 0. ./build_docker/./src/Common/StackTrace.cpp:372: StackTrace::tryCapture() @ 0x000000001aede5d7
2024-09-06 01:57:21 1. ./build_docker/./src/Common/Exception.cpp:53: DB::abortOnFailedAssertion(String const&) @ 0x000000001ae69b2e
2024-09-06 01:57:21 2. ./src/Columns/ColumnString.h:48: DB::ColumnString::doCompareAt(unsigned long, unsigned long, DB::IColumn const&, int) const @ 0x000000002afe8c64
2024-09-06 01:57:21 3. DB::IColumn::compareAt(unsigned long, unsigned long, DB::IColumn const&, int) const @ 0x000000000e8cb448
2024-09-06 01:57:21 4. ./src/Core/SortCursor.h:723: DB::FinishSortingTransform::consume(DB::Chunk) @ 0x000000002dfdb366
2024-09-06 01:57:21 5. ./build_docker/./src/Processors/Transforms/SortingTransform.cpp:350: DB::SortingTransform::work() @ 0x000000002daf714f
2024-09-06 01:57:21 6. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:47: DB::ExecutionThreadContext::executeTask() @ 0x000000002d3f1d4e
2024-09-06 01:57:21 7. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:283: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000002d3d6ed1
2024-09-06 01:57:21 8. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:249: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x000000002d3d581c
2024-09-06 01:57:21 9. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:120: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x000000002d3d5302
2024-09-06 01:57:21 10. ./build_docker/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000002d3faa57
2024-09-06 01:57:21 11. ./contrib/llvm-project/libcxx/include/__functional/function.h:848: ? @ 0x000000001b03103b
2024-09-06 01:57:21 12. ./build_docker/./src/Common/ThreadPool.cpp:252: void* std::__thread_proxy[abi:v15007]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000001b03b6ff
2024-09-06 01:57:21 13. asan_thread_start(void*) @ 0x000000000aa56059
2024-09-06 01:57:21 14. ? @ 0x00007faa2b49eac3
2024-09-06 01:57:21 15. ? @ 0x00007faa2b530850
2024-09-06 01:57:21 
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:55.668588 [ 2777 ] <Fatal> BaseDaemon: ########################################
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:55.671564 [ 2777 ] <Fatal> BaseDaemon: (version 24.9.1.78 (official build), build id: 595A9296B249ECBDE9A2B971B3BB65F308F87206, git hash: 27d81fd35744fd2d212181e21260772164174a33) (from thread 2337) (query_id: c5a5439d-3740-4579-a58c-1fb57f0c7fb6) (query: SELECT key, arrayJoin(mapValues(val)) FROM test ORDER BY ALL;) Received signal Aborted (6)
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:55.673812 [ 2777 ] <Fatal> BaseDaemon: 
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:55.676187 [ 2777 ] <Fatal> BaseDaemon: Stack trace: 0x000055af768354ad 0x000055af76e2ce03 0x00007faa2b44c520 0x00007faa2b4a09fd 0x00007faa2b44c476 0x00007faa2b4327f3 0x000055af767c06ab 0x000055af767c0b50 0x000055af8693fc64 0x000055af6a222448 0x000055af89932366 0x000055af8944e14f 0x000055af88d48d4e 0x000055af88d2ded1 0x000055af88d2c81c 0x000055af88d2c302 0x000055af88d51a57 0x000055af7698803b 0x000055af769926ff 0x000055af663ad059 0x00007faa2b49eac3 0x00007faa2b530850
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:55.795339 [ 2777 ] <Fatal> BaseDaemon: 0.0. inlined from ./build_docker/./src/Common/StackTrace.cpp:372: StackTrace::tryCapture()
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:55.796712 [ 2777 ] <Fatal> BaseDaemon: 0. ./build_docker/./src/Common/StackTrace.cpp:341: StackTrace::StackTrace(ucontext_t const&) @ 0x000000001aede4ad
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:56.011792 [ 2777 ] <Fatal> BaseDaemon: 1. ./build_docker/./src/Common/SignalHandlers.cpp:85: signalHandler(int, siginfo_t*, void*) @ 0x000000001b4d5e03
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:56.013703 [ 2777 ] <Fatal> BaseDaemon: 2. ? @ 0x00007faa2b44c520
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:56.015368 [ 2777 ] <Fatal> BaseDaemon: 3. ? @ 0x00007faa2b4a09fd
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:56.017074 [ 2777 ] <Fatal> BaseDaemon: 4. ? @ 0x00007faa2b44c476
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:56.019152 [ 2777 ] <Fatal> BaseDaemon: 5. ? @ 0x00007faa2b4327f3
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:56.251693 [ 2777 ] <Fatal> BaseDaemon: 6. ./build_docker/./src/Common/Exception.cpp:48: DB::abortOnFailedAssertion(String const&, void* const*, unsigned long, unsigned long) @ 0x000000001ae696ab
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:56.713669 [ 2777 ] <Fatal> BaseDaemon: 7. ./build_docker/./src/Common/Exception.cpp:54: ? @ 0x000000001ae69b50
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:57.254571 [ 2777 ] <Fatal> BaseDaemon: 8.0. inlined from ./src/Columns/ColumnString.h:48: DB::ColumnString::sizeAt(long) const
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:57.255780 [ 2777 ] <Fatal> BaseDaemon: 8. ./src/Columns/ColumnString.h:260: DB::ColumnString::doCompareAt(unsigned long, unsigned long, DB::IColumn const&, int) const @ 0x000000002afe8c64
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:57.641888 [ 2777 ] <Fatal> BaseDaemon: 9. DB::IColumn::compareAt(unsigned long, unsigned long, DB::IColumn const&, int) const @ 0x000000000e8cb448
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:58.004530 [ 2777 ] <Fatal> BaseDaemon: 10.0. inlined from ./src/Core/SortCursor.h:723: bool DB::less<std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>, std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>> const&, std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>> const&, unsigned long, unsigned long, std::vector<DB::SortColumnDescriptionWithColumnIndex, std::allocator<DB::SortColumnDescriptionWithColumnIndex>> const&)
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:58.005950 [ 2777 ] <Fatal> BaseDaemon: 10. ./build_docker/./src/Processors/Transforms/FinishSortingTransform.cpp:80: DB::FinishSortingTransform::consume(DB::Chunk) @ 0x000000002dfdb366
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:59.082351 [ 2777 ] <Fatal> BaseDaemon: 11. ./build_docker/./src/Processors/Transforms/SortingTransform.cpp:350: DB::SortingTransform::work() @ 0x000000002daf714f
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:59.244317 [ 2777 ] <Fatal> BaseDaemon: 12.0. inlined from ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:47: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:59.247406 [ 2777 ] <Fatal> BaseDaemon: 12. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:96: DB::ExecutionThreadContext::executeTask() @ 0x000000002d3f1d4e
2024-09-06 01:57:21 [6082bf7eab67] 2024.09.05 18:56:59.742859 [ 2777 ] <Fatal> BaseDaemon: 13. ./build_docker/./src/Processors/Executors/PipelineExecutor.cp

```

**Comment by Avogar** [comment]
Stable reproceable example:
```sql
set max_threads = 1, read_in_order_two_level_merge_threshold = 1;

CREATE OR REPLACE TABLE test(
    key String,
    val Map(String, String)
) engine = MergeTree
order by key settings min_bytes_for_wide_part = 0;

insert into test VALUES ('', {'x':'xx'});
insert into test VALUES ('', {});
SELECT key, arrayJoin(mapValues(val)) FROM test ORDER BY ALL;
DROP TABLE test;
```

Stacktrace:
```
[avogar-dev] 2024.09.05 20:43:04.261452 [ 2621783 ] <Fatal> BaseDaemon: ########################################
[avogar-dev] 2024.09.05 20:43:04.261568 [ 2621783 ] <Fatal> BaseDaemon: (version 24.9.1.1, build id: C66592BEBEC5ABAB4F45062A56E9AE0054FB7E94, git hash: a7d0a5991e5e0e0be9bce7bc7ac9e1de5f376903) (from thread 2621728) (query_id: f566c688-f3b1-4a9e-a3c1-2f34e585fe87) (query: SELECT key, arrayJoin(mapValues(val)) FROM test ORDER BY ALL;) Received signal Aborted (6)
[avogar-dev] 2024.09.05 20:43:04.261628 [ 2621783 ] <Fatal> BaseDaemon:
[avogar-dev] 2024.09.05 20:43:04.261680 [ 2621783 ] <Fatal> BaseDaemon: Stack trace: 0x000000000c4a4fe8 0x000000000c6fbe1e 0x000078adfbe42520 0x000078adfbe969fd 0x000078adfbe42476 0x000078adfbe287f3 0x000078adfbe2871b 0x000078adfbe39e96 0x0000000011dbb6b8 0x0000000013058f11 0x00000000130585ba 0x0000000012e53b78 0x0000000012bc38ab 0x0000000012bb8d51 0x0000000012bb782c 0x0000000012bb724f 0x0000000012bc679f 0x000000000c52b981 0x000000000c52fec5 0x000078adfbe94ac3 0x000078adfbf26850
[avogar-dev] 2024.09.05 20:43:04.281832 [ 2621783 ] <Fatal> BaseDaemon: 0.0. inlined from /home/avogar/ClickHouse/src/Common/StackTrace.cpp:372: StackTrace::tryCapture()
[avogar-dev] 2024.09.05 20:43:04.281893 [ 2621783 ] <Fatal> BaseDaemon: 0. /home/avogar/ClickHouse/src/Common/StackTrace.cpp:341: StackTrace::StackTrace(ucontext_t const&) @ 0x000000000c4a4fe8
[avogar-dev] 2024.09.05 20:43:04.309319 [ 2621783 ] <Fatal> BaseDaemon: 1. /home/avogar/ClickHouse/src/Common/SignalHandlers.cpp:85: signalHandler(int, siginfo_t*, void*) @ 0x000000000c6fbe1e
[avogar-dev] 2024.09.05 20:43:04.309374 [ 2621783 ] <Fatal> BaseDaemon: 2. ? @ 0x000078adfbe42520
[avogar-dev] 2024.09.05 20:43:04.309415 [ 2621783 ] <Fatal> BaseDaemon: 3. ? @ 0x000078adfbe969fd
[avogar-dev] 2024.09.05 20:43:04.309465 [ 2621783 ] <Fatal> BaseDaemon: 4. ? @ 0x000078adfbe42476
[avogar-dev] 2024.09.05 20:43:04.309506 [ 2621783 ] <Fatal> BaseDaemon: 5. ? @ 0x000078adfbe287f3
[avogar-dev] 2024.09.05 20:43:04.309541 [ 2621783 ] <Fatal> BaseDaemon: 6. ? @ 0x000078adfbe2871b
[avogar-dev] 2024.09.05 20:43:04.309568 [ 2621783 ] <Fatal> BaseDaemon: 7. ? @ 0x000078adfbe39e96
[avogar-dev] 2024.09.05 20:43:04.346880 [ 2621783 ] <Fatal> BaseDaemon: 8. /home/avogar/ClickHouse/src/Columns/ColumnString.h:260: DB::ColumnString::doCompareAt(unsigned long, unsigned long, DB::IColumn const&, int) const @ 0x0000000011dbb6b8
[avogar-dev] 2024.09.05 20:43:04.394070 [ 2621783 ] <Fatal> BaseDaemon: 9.0. inlined from /home/avogar/ClickHouse/src/Columns/IColumn.h:354: DB::IColumn::compareAt(unsigned long, unsigned long, DB::IColumn const&, int) const
[avogar-dev] 2024.09.05 20:43:04.394133 [ 2621783 ] <Fatal> BaseDaemon: 9. /home/avogar/ClickHouse/src/Core/SortCursor.h:723: bool DB::less<std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>, std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>> const&, std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>> const&, unsigned long, unsigned long, std::vector<DB::SortColumnDescriptionWithColumnIndex, std::allocator<DB::SortColumnDescriptionWithColumnIndex>> const&) @ 0x0000000013058f11
[avogar-dev] 2024.09.05 20:43:04.430106 [ 2621783 ] <Fatal> BaseDaemon: 10. /home/avogar/ClickHouse/src/Processors/Transforms/FinishSortingTransform.cpp:80: DB::FinishSortingTransform::consume(DB::Chunk) @ 0x00000000130585ba
[avogar-dev] 2024.09.05 20:43:04.508483 [ 2621783 ] <Fatal> BaseDaemon: 11. /home/avogar/ClickHouse/src/Processors/Transforms/SortingTransform.cpp:350: DB::SortingTransform::work() @ 0x0000000012e53b78
[avogar-dev] 2024.09.05 20:43:04.516537 [ 2621783 ] <Fatal> BaseDaemon: 12.0. inlined from /home/avogar/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:47: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
[avogar-dev] 2024.09.05 20:43:04.516595 [ 2621783 ] <Fatal> BaseDaemon: 12. /home/avogar/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:96: DB::ExecutionThreadContext::executeTask() @ 0x0000000012bc38ab
[avogar-dev] 2024.09.05 20:43:04.543028 [ 2621783 ] <Fatal> BaseDaemon: 13.0. inlined from /home/avogar/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:283: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*)
[avogar-dev] 2024.09.05 20:43:04.543087 [ 2621783 ] <Fatal> BaseDaemon: 13. /home/avogar/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:249: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x0000000012bb8d51
[avogar-dev] 2024.09.05 20:43:04.565355 [ 2621783 ] <Fatal> BaseDaemon: 14. /home/avogar/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:424: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x0000000012bb782c
[avogar-dev] 2024.09.05 20:43:04.590046 [ 2621783 ] <Fatal> BaseDaemon: 15. /home/avogar/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:120: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x0000000012bb724f
[avogar-dev] 2024.09.05 20:43:04.612398 [ 2621783 ] <Fatal> BaseDaemon: 16.0. inlined from /home/avogar/ClickHouse/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::shared_ptr<DB::ThreadGroup>, unsigned long, bool)
[avogar-dev] 2024.09.05 20:43:04.612445 [ 2621783 ] <Fatal> BaseDaemon: 16.1. inlined from /home/avogar/ClickHouse/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:109: operator()
[avogar-dev] 2024.09.05 20:43:04.612490 [ 2621783 ] <Fatal> BaseDaemon: 16.2. inlined from /home/avogar/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ?
[avogar-dev] 2024.09.05 20:43:04.612536 [ 2621783 ] <Fatal> BaseDaemon: 16.3. inlined from /home/avogar/ClickHouse/contrib/llvm-project/libcxx/include/tuple:1789: decltype(auto) std::__apply_tuple_impl[abi:v15007]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&, std::__tuple_indices<>)
[avogar-dev] 2024.09.05 20:43:04.612584 [ 2621783 ] <Fatal> BaseDaemon: 16.4. inlined from /home/avogar/ClickHouse/contrib/llvm-project/libcxx/include/tuple:1798: decltype(auto) std::apply[abi:v15007]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&)
[avogar-dev] 2024.09.05 20:43:04.612624 [ 2621783 ] <Fatal> BaseDaemon: 16.5. inlined from /home/avogar/ClickHouse/src/Common/ThreadPool.h:251: operator()
[avogar-dev] 2024.09.05 20:43:04.612657 [ 2621783 ] <Fatal> BaseDaemon: 16.6. inlined from /home/avogar/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ?
[avogar-dev] 2024.09.05 20:43:04.612696 [ 2621783 ] <Fatal> BaseDaemon: 16.7. inlined from /home/avogar/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:479: ?
[avogar-dev] 2024.09.05 20:43:04.612731 [ 2621783 ] <Fatal> BaseDaemon: 16.8. inlined from /home/avogar/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:235: ?
[avogar-dev] 2024.09.05 20:43:04.612773 [ 2621783 ] <Fatal> BaseDaemon: 16. /home/avogar/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000012bc679f
[avogar-dev] 2024.09.05 20:43:04.631229 [ 2621783 ] <Fatal> BaseDaemon: 17.0. inlined from /home/avogar/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:848: ?
[avogar-dev] 2024.09.05 20:43:04.631270 [ 2621783 ] <Fatal> BaseDaemon: 17.1. inlined from /home/avogar/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:1197: ?
[avogar-dev] 2024.09.05 20:43:04.631316 [ 2621783 ] <Fatal> BaseDaemon: 17. /home/avogar/ClickHouse/src/Common/ThreadPool.cpp:462: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000c52b981
[avogar-dev] 2024.09.05 20:43:04.661544 [ 2621783 ] <Fatal> BaseDaemon: 18.0. inlined from /home/avogar/ClickHouse/src/Common/ThreadPool.cpp:219: operator()
[avogar-dev] 2024.09.05 20:43:04.661592 [ 2621783 ] <Fatal> BaseDaemon: 18.1. inlined from /home/avogar/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ?
[avogar-dev] 2024.09.05 20:43:04.661630 [ 2621783 ] <Fatal> BaseDaemon: 18.2. inlined from /home/avogar/ClickHouse/contrib/llvm-project/libcxx/include/thread:284: void std::__thread_execute[abi:v15007]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(std::tuple<void, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>&, std::__tuple_indices<>)
[avogar-dev] 2024.09.05 20:43:04.661658 [ 2621783 ] <Fatal> BaseDaemon: 18. /home/avogar/ClickHouse/contrib/llvm-project/libcxx/include/thread:295: void* std::__thread_proxy[abi:v15007]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c52fec5
[avogar-dev] 2024.09.05 20:43:04.661686 [ 2621783 ] <Fatal> BaseDaemon: 19. ? @ 0x000078adfbe94ac3
[avogar-dev] 2024.09.05 20:43:04.661709 [ 2621783 ] <Fatal> BaseDaemon: 20. ? @ 0x000078adfbf26850
[avogar-dev] 2024.09.05 20:43:04.661731 [ 2621783 ] <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
[avogar-dev] 2024.09.05 20:43:05.046488 [ 2621783 ] <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
[avogar-dev] 2024.09.05 20:43:05.046631 [ 2621783 ] <Fatal> BaseDaemon: Changed settings: max_threads = 1, connect_timeout_with_failover_ms = 2000, connect_timeout_with_failover_secure_ms = 3000, idle_connection_timeout = 36000, stream_like_engine_allow_direct_select = true, replication_wait_for_inactive_replica_timeout = 30, log_queries = true, insert_quorum_timeout = 60000, fsync_metadata = false, http_send_timeout = 60., http_receive_timeout = 60., opentelemetry_start_trace_probability = 0.10000000149011612, max_untracked_memory = 1048576, memory_profiler_step = 1048576, read_in_order_two_level_merge_threshold = 1, allow_introspection_functions = true, database_atomic_wait_for_drop_and_detach_synchronously = true, async_insert_busy_timeout_max_ms = 5000, 
```

It's not related to Variant, it's something else

**Comment by Avogar** [comment]
@fm4v we can try to find the version when it became broken

**Comment by fm4v** [comment]
Fixed by some change, test is added here: https://github.com/ClickHouse/ClickHouse/pull/68155

**Comment by SmitaRKulkarni** [comment]
Looks like issue is still seen
https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsY2hlY2tfbmFtZSx0ZXN0X3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19uYW1lIExJS0UgJ1N0YXRlJScKICAgIEFORCBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMSBtb250aAogICAgQU5EIChzdGFydHNXaXRoKGhlYWRfcmVwbywgJ0NsaWNrSG91c2UvJykpCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgKHRlc3Rfc3RhdHVzIExJS0UgJ0YlJyBPUiB0ZXN0X3N0YXR1cyBMSUtFICdFJScgb3IgdGVzdF9zdGF0dXM9J1NFUlZFUl9ESUVEJykgCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJyBhbmQgdGVzdF9uYW1lIGxpa2UgJyUwMzIyMV92YXJpYW50X2xvZ2ljYWxfZXJyb3IlJwpPUkRFUiBCWSBjaGVja19zdGFydF90aW1lLCBjaGVja19uYW1lLCB0ZXN0X25hbWU=

**Comment by Avogar** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/76919, merged today
