### ISSUE TITLE
test_memory_limit/test.py::test_multiple_queries flakes

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#72458]
Example: https://s3.amazonaws.com/clickhouse-test-reports/71997/7773873e726708a96857a4c3f9e5d91c84840826/integration_tests__aarch64__[2_6].html

```
test_memory_limit/test.py:55: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
helpers/cluster.py:3631: in query
    return self.client.query(
helpers/client.py:36: in wrap
    return func(self, *args, **kwargs)
helpers/client.py:74: in query
    ).get_answer()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <helpers.client.CommandRequest object at 0xffaa0361aa10>

    def get_answer(self):
        self.process.wait(timeout=DEFAULT_QUERY_TIMEOUT)
        self.stdout_file.seek(0)
        self.stderr_file.seek(0)
    
        stdout = self.stdout_file.read().decode("utf-8", errors="replace")
        stderr = self.stderr_file.read().decode("utf-8", errors="replace")
    
        if (
            self.timer is not None
            and not self.process_finished_before_timeout
            and not self.ignore_error
        ):
            logging.debug(f"Timed out. Last stdout:{stdout}, stderr:{stderr}")
            raise QueryTimeoutExceedException("Client timed out!")
    
        if (
            self.process.returncode != 0 or self.remove_trash_from_stderr(stderr)
        ) and not self.ignore_error:
>           raise QueryRuntimeException(
                "Client failed! Return code: {}, stderr: {}".format(
                    self.process.returncode, stderr
                ),
                self.process.returncode,
                stderr,
            )
E           helpers.client.QueryRuntimeException: Client failed! Return code: 210, stderr: Code: 210. DB::NetException: Net Exception: No route to host (172.16.1.2:9000). (NETWORK_ERROR)

helpers/client.py:238: QueryRuntimeException
```

**Comment by antonio2368** [comment]
Should be fixed with https://github.com/ClickHouse/ClickHouse/pull/74258

**Comment by nickitat** [comment]
It still fails occasionally [link](https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCAgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlIHRvZGF5KCkgLSBJTlRFUlZBTCAnMyBtb250aHMnIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHRlc3RfbmFtZSBsaWtlICcldGVzdF9tZW1vcnlfbGltaXQvdGVzdC5weTo6dGVzdF9tdWx0aXBsZV9xdWVyaWVzJScgYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScpIGdyb3VwIGJ5IGQgb3JkZXIgYnkgZCBkZXNj)

Don't see anything useful in the logs. Any better ideas than reducing parallelism and increasing mem limit slightly?

**Comment by Algunenano** [comment]
Still fails occasionally: https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=1c359f3cca831e1298b33fa96fdcc2a4c818d798&name_0=MasterCI&name_1=Integration%20tests%20%28aarch64%2C%20distributed%20plan%2C%203%2F4%29

**Comment by antonio2368** [comment]
Yeah, it's relatively rare and for some reason only for `distributed plan` runs.

**Comment by shankar-iyer** [comment]
Analyzed this failure in my PR : [link](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=85557&sha=465a43b7b1d738b1b59199781bf6bf7519f7e44a&name_0=PR&name_1=Integration%20tests%20%28arm_binary%2C%20distributed%20plan%2C%204%2F4%29)
```
[Thu Aug 14 12:36:04 2025] Memory cgroup out of memory: Killed process 1048414 (clickhouse) total-vm:31444140kB, 
anon-rss:4121776kB, file-rss:220800kB, shmem-rss:0kB, UID:0 pgtables:14244kB oom_score_adj:0
```
Process VM reached 29.9GB and RSS crossed 4GB. 

Test runs on a _small_ VM - 4GB RAM -

```
2025.08.14 12:36:03.083601 [ 1 ] {} <Debug> CrashWriter: Sending crash reports is initialized with https://crash.clickhouse.com/ endpoint (anonymized)
2025.08.14 12:36:03.083615 [ 1 ] {} <Debug> Application: Sending logical errors is enabled
2025.08.14 12:36:03.134224 [ 1 ] {} <Information> Application: Starting ClickHouse 25.8.1.1 (revision: 54501, git hash: 89ff22c682e5d58b9ff7523a785084a706f5a537, build id: AC14AAA2D81B7E188E38163CB715918F3E19CEC8), PID 1
2025.08.14 12:36:03.134306 [ 1 ] {} <Information> Application: starting up
2025.08.14 12:36:03.134317 [ 1 ] {} <Information> Application: OS name: Linux, version: 6.8.0-1031-aws, architecture: aarch64
2025.08.14 12:36:03.134440 [ 1 ] {} <Information> Jemalloc: Value for background_thread set to true (from true)
2025.08.14 12:36:03.139361 [ 1 ] {} <Information> Application: Available RAM: 4.00 GiB; logical cores: 16; used cores: 16.
```

More from dmesg log -
```
[Thu Aug 14 12:36:04 2025] QueryPipelineEx invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=0
[Thu Aug 14 12:36:04 2025] CPU: 11 PID: 1049197 Comm: QueryPipelineEx Not tainted 6.8.0-1031-aws #33~22.04.1-Ubuntu
[Thu Aug 14 12:36:04 2025] Hardware name: Amazon EC2 m8g.4xlarge/, BIOS 1.0 11/1/2018
[Thu Aug 14 12:36:04 2025] Call trace:
[Thu Aug 14 12:36:04 2025]  dump_backtrace+0xa8/0x158
[Thu Aug 14 12:36:04 2025]  show_stack+0x24/0x50
[Thu Aug 14 12:36:04 2025]  dump_stack_lvl+0xd0/0x140
[Thu Aug 14 12:36:04 2025]  dump_stack+0x1c/0x38
[Thu Aug 14 12:36:04 2025]  dump_header+0x48/0x230
[Thu Aug 14 12:36:04 2025]  oom_kill_process+0x1d4/0x3f0
[Thu Aug 14 12:36:04 2025]  out_of_memory+0xe8/0x390
[Thu Aug 14 12:36:04 2025]  mem_cgroup_out_of_memory+0x15c/0x1b8
[Thu Aug 14 12:36:04 2025]  try_charge_memcg+0x594/0x680
[Thu Aug 14 12:36:04 2025]  __mem_cgroup_charge+0x64/0xf0
[Thu Aug 14 12:36:04 2025]  do_anonymous_page+0xa4/0x3f8
[Thu Aug 14 12:36:04 2025]  do_pte_missing+0xe4/0x378
[Thu Aug 14 12:36:04 2025]  handle_pte_fault+0x6c/0x1d0
[Thu Aug 14 12:36:04 2025]  __handle_mm_fault+0x234/0x3e8
[Thu Aug 14 12:36:04 2025]  handle_mm_fault+0xac/0x2a0
[Thu Aug 14 12:36:04 2025]  do_page_fault+0x124/0x520
[Thu Aug 14 12:36:04 2025]  do_translation_fault+0x7c/0xd0
[Thu Aug 14 12:36:04 2025]  do_mem_abort+0x50/0xd0
[Thu Aug 14 12:36:04 2025]  el0_da+0x4c/0x150
[Thu Aug 14 12:36:04 2025]  el0t_64_sync_handler+0xe0/0x158
[Thu Aug 14 12:36:04 2025]  el0t_64_sync+0x1b0/0x1b8
[Thu Aug 14 12:36:04 2025] memory: usage 4194272kB, limit 4194304kB, failcnt 397
[Thu Aug 14 12:36:04 2025] memory+swap: usage 4194272kB, limit 8388608kB, failcnt 0
[Thu Aug 14 12:36:04 2025] kmem: usage 32760kB, limit 9007199254740988kB, failcnt 0
[Thu Aug 14 12:36:04 2025] Memory cgroup stats for /docker/7f743053c35baea29cf7e173af376dda0754d25274d88868f3e32b734ae2b9d1/docker/dafe9034f6f2404f901e25ebc57cc3a05b70b4971982b83d2d9b3e083b31382d:
[Thu Aug 14 12:36:04 2025] cache 94208
[Thu Aug 14 12:36:04 2025] rss 4221603840
[Thu Aug 14 12:36:04 2025] rss_huge 0
[Thu Aug 14 12:36:04 2025] shmem 0
[Thu Aug 14 12:36:04 2025] mapped_file 0
[Thu Aug 14 12:36:04 2025] dirty 28672
[Thu Aug 14 12:36:04 2025] writeback 0
[Thu Aug 14 12:36:04 2025] workingset_refault_anon 0
[Thu Aug 14 12:36:04 2025] workingset_refault_file 0
[Thu Aug 14 12:36:04 2025] swap 0
[Thu Aug 14 12:36:04 2025] swapcached 0
[Thu Aug 14 12:36:04 2025] pgpgin 1217755
[Thu Aug 14 12:36:04 2025] pgpgout 177887
[Thu Aug 14 12:36:04 2025] pgfault 1221527
[Thu Aug 14 12:36:04 2025] pgmajfault 0
[Thu Aug 14 12:36:04 2025] inactive_anon 36671488
[Thu Aug 14 12:36:04 2025] active_anon 4222443520
[Thu Aug 14 12:36:04 2025] inactive_file 0
[Thu Aug 14 12:36:04 2025] active_file 86016
[Thu Aug 14 12:36:04 2025] unevictable 0
[Thu Aug 14 12:36:04 2025] hierarchical_memory_limit 4294967296
[Thu Aug 14 12:36:04 2025] hierarchical_memsw_limit 8589934592
[Thu Aug 14 12:36:04 2025] total_cache 94208
[Thu Aug 14 12:36:04 2025] total_rss 4221603840
[Thu Aug 14 12:36:04 2025] total_rss_huge 0
[Thu Aug 14 12:36:04 2025] total_shmem 0
[Thu Aug 14 12:36:04 2025] total_mapped_file 0
[Thu Aug 14 12:36:04 2025] total_dirty 28672
[Thu Aug 14 12:36:04 2025] total_writeback 0
[Thu Aug 14 12:36:04 2025] total_workingset_refault_anon 0
[Thu Aug 14 12:36:04 2025] total_workingset_refault_file 0
[Thu Aug 14 12:36:04 2025] total_swap 0
[Thu Aug 14 12:36:04 2025] total_swapcached 0
[Thu Aug 14 12:36:04 2025] total_pgpgin 1217755
[Thu Aug 14 12:36:04 2025] total_pgpgout 177887
[Thu Aug 14 12:36:04 2025] total_pgfault 1221527
[Thu Aug 14 12:36:04 2025] total_pgmajfault 0
[Thu Aug 14 12:36:04 2025] total_inactive_anon 36671488
[Thu Aug 14 12:36:04 2025] total_active_anon 4222443520
[Thu Aug 14 12:36:04 2025] total_inactive_file 0
[Thu Aug 14 12:36:04 2025] total_active_file 86016
[Thu Aug 14 12:36:04 2025] total_unevictable 0
[Thu Aug 14 12:36:04 2025] Tasks state (memory values in pages):
[Thu Aug 14 12:36:04 2025] [  pid  ]   uid  tgid total_vm      rss rss_anon rss_file rss_shmem pgtables_bytes swapents oom_score_adj name
[Thu Aug 14 12:36:04 2025] [1048414]     0 1048414  7861035  1085644  1030444    55200         0 14585856        0             0 clickhouse
[Thu Aug 14 12:36:04 2025] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=dafe9034f6f2404f901e25ebc57cc3a05b70b4971982b83d2d9b3e083b31382d,mems_allowed=0,oom_memcg=/docker/7f743053c35baea29cf7e173af376dda0754d25274d88868f3e32b734ae2b9d1/docker/dafe9034f6f2404f901e25ebc57cc3a05b70b4971982b83d2d9b3e083b31382d,task_memcg=/docker/7f743053c35baea29cf7e173af376dda0754d25274d88868f3e32b734ae2b9d1/docker/dafe9034f6f2404f901e25ebc57cc3a05b70b4971982b83d2d9b3e083b31382d,task=clickhouse,pid=1048414,uid=0
[Thu Aug 14 12:36:04 2025] Memory cgroup out of memory: Killed process 1048414 (clickhouse) total-vm:31444140kB, anon-rss:4121776kB, file-rss:220800kB, shmem-rss:0kB, UID:0 pgtables:14244kB oom_score_adj:0
[Thu Aug 14 12:36:04 2025] br-9ceafa98e463: port 1(vetha540f9f) entered disabled state
[Thu Aug 14 12:36:04 2025] veth5ea6810: renamed from eth0
[Thu Aug 14 12:36:04 2025] br-9ceafa98e463: port 1(vetha540f9f) entered disabled state
[Thu Aug 14 12:36:04 2025] vetha540f9f (unregistering): left allmulticast mode
[Thu Aug 14 12:36:04 2025] vetha540f9f (unregistering): left promiscuous mode
[Thu Aug 14 12:36:04 2025] br-9ceafa98e463: port 1(vetha540f9f) entered disabled state
[Thu Aug 14 12:36:51 2025] docker0: port 1(veth833ffb3) entered disabled state
[Thu Aug 14 12:36:51 2025] veth3510f31: renamed from eth0
[Thu Aug 14 12:36:51 2025] docker0: port 1(veth833ffb3) entered disabled state
[Thu Aug 14 12:36:51 2025] veth833ffb3 (unregistering): left allmulticast mode
[Thu Aug 14 12:36:51 2025] veth833ffb3 (unregistering): left promiscuous mode
[Thu Aug 14 12:36:51 2025] docker0: port 1(veth833ffb3) entered disabled state
INFO:root:Result written
INFO:root:Found check_status.tsv
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
failure [Integration tests (arm_binary, distributed plan, 4/4)]
  | fail: 1, passed: 751
  | To run locally: python -m ci.praktika run "Integration tests (arm_binary, distributed plan, 4/4)" [ --test TEST_NAME (if supported by the job)]
  FAIL [test_memory_limit/test.py::test_multiple_queries]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

ERROR: Run failed with exit code [1]
=== Run script finished ===
```
Last message from clickhouse log
```
2025.08.14 12:36:05.149415 [ 13 ] {} <Error> TCPHandler: Code: 241. DB::Exception: (total) memory limit exceeded: would use 3.29 GiB (attempt to allocate chunk of 0.00 B bytes), current RSS: 3.67 GiB, maximum: 3.60 GiB. OvercommitTracker decision: Memory overcommit has not freed enough memory: While executing AggregatingTransform. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):

0. ./ci/tmp/build/./base/poco/Foundation/src/Exception.cpp:28: Poco::Exception::Exception(String const&, int) @ 0x000000001c230778
1. ./ci/tmp/build/./src/Common/Exception.cpp:128: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e31946c
2. DB::Exception::Exception(String&&, int, String, bool) @ 0x0000000008db0658
3. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000008daffa8
4. ./src/Common/Exception.h:141: DB::Exception::Exception<char const*, char const*, String, String, String, String, String, char const*, std::basic_string_view<char, std::char_traits<char>>>(int, FormatStringHelperImpl<std::type_identity<char const*>::type, std::type_identity<char const*>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<char const*>::type, std::type_identity<std::basic_string_view<char, std::char_traits<char>>>::type>, char const*&&, char const*&&, String&&, String&&, String&&, String&&, String&&, char const*&&, std::basic_string_view<char, std::char_traits<char>>&&) @ 0x000000000e389d5c
5. ./ci/tmp/build/./src/Common/MemoryTracker.cpp:379: MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000e387e3c
6. ./ci/tmp/build/./src/Common/MemoryTracker.cpp:0: MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000e387988
7. ./ci/tmp/build/./src/Common/MemoryTracker.cpp:0: MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000e387988
8. ./ci/tmp/build/./src/Common/MemoryTracker.cpp:0: MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000e387988
9. ./ci/tmp/build/./src/Interpreters/Aggregator.cpp:1966: DB::Aggregator::checkLimits(unsigned long, bool&) const @ 0x0000000013406e20
10. ./ci/tmp/build/./src/Interpreters/Aggregator.cpp:1737: DB::Aggregator::executeOnBlock(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>, unsigned long, unsigned long, DB::AggregatedDataVariants&, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*>>&, std::vector<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*>>, std::allocator<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*>>>>&, bool&) const @ 0x000000001340f1d4
11. ./ci/tmp/build/./src/Processors/Transforms/AggregatingTransform.cpp:757: DB::AggregatingTransform::consume(DB::Chunk) @ 0x0000000017085404
12. ./ci/tmp/build/./src/Processors/Transforms/AggregatingTransform.cpp:715: DB::AggregatingTransform::work() @ 0x0000000017083084
13. ./ci/tmp/build/./src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x0000000016e61d9c
14. ./ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:350: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x0000000016e57388
15. ./ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:278: void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x0000000016e58054
16. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000000e4411a8
17. ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x000000000e445920
18. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000000e43f0ec
19. ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000e4442c8
20. ? @ 0x000000000007d5b8
21. ? @ 0x00000000000e5edc

2025.08.14 12:36:05.150177 [ 13 ] {} <Test> TCPHandler: Closing connection (open: true, cancelled: false, eof: true)
```

Testcase -

```
def test_multiple_queries():
    if node.is_built_with_sanitizer():
        return

    p = Pool(15)

    def run_query(node):
        try:
            node.query("SELECT * FROM system.numbers GROUP BY number")
        except Exception as ex:
            print("Exception", ex)
            raise ex

    tasks = []
    for i in range(30):
        tasks.append(p.apply_async(run_query, (node,)))
        time.sleep(i * 0.1)

    for task in tasks:
        try:
            task.get()
        except Exception as ex:
            print("Exception", ex)

    # test that we didn't kill the server
    node.query("SELECT 1")
```

**Comment by azat** [comment]
This should help with debugging - https://github.com/ClickHouse/ClickHouse/pull/85539

**Comment by azat** [comment]
>Yeah, it's relatively rare and for some reason only for distributed plan runs.

I think it is about `arm`, not `distributed plan`, which has:
- 16K pages in jemalloc
- _and also 64K guard pages (though those should be empty) - https://github.com/clickhouse/clickhouse/issues/83967_

I've looked at jemalloc profiles and they looks sane

<details>

![Image](https://github.com/user-attachments/assets/f4206554-5a41-4f25-bf1e-67954a584d9e)

</details>

Maybe with 16K pages 10% is slightly not enough for allocator metadata, let's enable metrics (https://github.com/ClickHouse/ClickHouse/pull/86047) and if this will be confirmed tune `max_server_memory_usage_to_ram_ratio`

**Comment by al13n321** [comment]
Same problem in https://github.com/ClickHouse/ClickHouse/issues/87244 : the test expects clickhouse server to use less than 3 GB of memory, flaky on `arm_binary, distributed plan`.

In [1] jeprof failed like this:
```
node_smol-1  | === jemalloc reports:
node_smol-1  | -rw-r----- 1 root root 107862 Sep  5 17:13 /tmp/jemalloc_profiles/clickhouse.jemalloc.8.0.m0.heap
node_smol-1  | Using /tmp/jemalloc_profiles/clickhouse.jemalloc.8.0.m0.heap
node_smol-1  | Using local file /usr/bin/clickhouse.
node_smol-1  | Using local file /tmp/jemalloc_profiles/clickhouse.jemalloc.8.0.m0.heap.
node1-1 exited with code 0
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x23
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x23
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x22
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x22
node_smol-1  | /usr/bin/objdump: Warning: Bogus end-of-siblings marker detected at offset 883 in .debug_info section
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x23
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x23
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x22
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x23
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x23
node_smol-1  | /usr/bin/objdump: Warning: Bogus end-of-siblings marker detected at offset 9db in .debug_info section
node_smol-1  | /usr/bin/objdump: Warning: Bogus end-of-siblings marker detected at offset 9dc in .debug_info section
node_smol-1  | /usr/bin/objdump: Warning: Further warnings about bogus end-of-sibling markers suppressed
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x22
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x22
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x22
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x22
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x22
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x23
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x23
node_smol-1  | /usr/bin/objdump: Warning: DIE at offset 0xca76 refers to abbreviation number 8443 which does not exist
node_smol-1  | Using local file /usr/bin/clickhouse.
node_smol-1  | Using local file /tmp/jemalloc_profiles/clickhouse.jemalloc.8.0.m0.heap.
resolver-1 exited with code 137
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x23
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x23
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x22
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x22
node_smol-1  | /usr/bin/objdump: Warning: Bogus end-of-siblings marker detected at offset 883 in .debug_info section
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x23
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x23
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x22
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x23
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x23
node_smol-1  | /usr/bin/objdump: Warning: Bogus end-of-siblings marker detected at offset 9db in .debug_info section
node_smol-1  | /usr/bin/objdump: Warning: Bogus end-of-siblings marker detected at offset 9dc in .debug_info section
node_smol-1  | /usr/bin/objdump: Warning: Further warnings about bogus end-of-sibling markers suppressed
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x22
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x22
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x22
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x22
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x22
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x23
node_smol-1  | /usr/bin/objdump: Warning: Unrecognized form: 0x23
node_smol-1  | /usr/bin/objdump: Warning: DIE at offset 0xca76 refers to abbreviation number 8443 which does not exist
node_smol-1  | Stack count is low (0). Did something go wrong?
node_smol-1  | ERROR: No stack counts found
node_smol-1 exited with code 0
```

I think this means objdump version is too old (0x22 and 0x23 are perfectly normal forms added in DWARF 5 a few years ago).

[1] https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=86166&sha=9b264df3c0b122f4353cb8ed2f4e0dc4cd5ec8ef&name_0=PR&name_1=Integration%20tests%20%28arm_binary%2C%20distributed%20plan%2C%202%2F4%29&name_1=Integration%20tests%20%28arm_binary%2C%20distributed%20plan%2C%202%2F4%29

**Comment by azat** [comment]
>I think this means objdump version is too old (0x22 and 0x23 are perfectly normal forms added in DWARF 5 a few years ago).

Let's upgrade?

BTW maybe you have ideas why `llvm-objdump` does not work (in docker)? (it does not resolve function names properly, maybe related to PIC)

**Comment by al13n321** [comment]
> Let's upgrade?

(Don't look at me, I have no idea how any of this works and am allergic to containers, sorry.)

On second look, maybe the objdump warnings are red herring: (1) in `jeprof` script it's not obvious that objdump is used for anything critical, the important one is addr2line as you would expect, (2) if I run objdump locally it spews the same warnings but then outputs the list of sections just fine (idk why it's even parsing dwarf).

> BTW maybe you have ideas why llvm-objdump does not work (in docker)? (it does not resolve function names properly, maybe related to PIC)

(Nope, other then the obvious idea that maybe the version is older than the clang we're building with, which you probably already checked. All I know is that IME llvm-addr2line and llvm-dwarfdump are faster and more likely to work than their non-llvm- counterparts. Also, are we building as PIC? is it an arm thing?)

**Comment by azat** [comment]
> Also, are we building as PIC? is it an arm thing?

Not really, only release builds do not have PIC, everything else does. And in integration tests we use `amd_binary`/`arm_binary`, which are not `amd_release`/`arm_release`

https://github.com/ClickHouse/ClickHouse/blob/57287763254fa937717b563f3febe8eafae93676/CMakeLists.txt#L438-L440

**Comment by azat** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=87094&sha=4f085d3dc22250ddac75e375db5abf0668fbf830&name_0=PR&name_1=Integration%20tests%20%28arm_binary%2C%20distributed%20plan%2C%204%2F4%29&name_1=Integration%20tests%20%28arm_binary%2C%20distributed%20plan%2C%204%2F4%29

**Comment by azat** [comment]
Maybe https://github.com/ClickHouse/ClickHouse/pull/87035 will also help (I've made some allocations throwable there)

**Comment by alexey-milovidov** [comment]
All good now.
