### ISSUE TITLE
Build fails on Mac OS, on assembly files from contrib/openssl, error: unknown directive

### ISSUE THREAD

**Issue by kolen** [ClickHouse/ClickHouse#8300]
- `git diff` and all submodules are clean
- I have installed [all dependencies listed here](https://clickhouse.yandex/docs/en/development/build_osx/#install-required-compilers-tools-and-libraries)

**Operating system**
Mac OS 10.13.6 "High Sierra"

**Cmake version**
3.15.5

**Ninja version**
1.9.0

**Compiler name and version**
clang 10.0.0 from "XCode command line tools" (full XCode is not installed)

```
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Full cmake and/or ninja output**

<details>

```
~/items/ClickHouse % mkdir build
~/items/ClickHouse % cd build
~/items/ClickHouse/build % cmake .. -DCMAKE_CXX_COMPILER=`which clang++` -DCMAKE_C_COMPILER=`which clang`
-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IPO/LTO not enabled.
-- CMAKE_BUILD_TYPE is not set, set to default = RELWITHDEBINFO
-- CMAKE_BUILD_TYPE: RELWITHDEBINFO
-- Disabling compiler -pipe option (have only 5528 mb of memory)
-- Performing Test HAVE_SSE41
-- Performing Test HAVE_SSE41 - Success
-- Performing Test HAVE_SSE42
-- Performing Test HAVE_SSE42 - Success
-- Performing Test HAVE_SSSE3
-- Performing Test HAVE_SSSE3 - Success
-- Performing Test HAVE_AVX
-- Performing Test HAVE_AVX - Success
-- Performing Test HAVE_AVX2
-- Performing Test HAVE_AVX2 - Success
-- Performing Test HAVE_PCLMULQDQ
-- Performing Test HAVE_PCLMULQDQ - Success
-- Performing Test HAVE_POPCNT
-- Performing Test HAVE_POPCNT - Success
-- Default libraries: -nodefaultlibs  -lc -lm -lpthread -ldl
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Performing Test HAVE_WARNING_RESERVED_ID_MACRO
-- Performing Test HAVE_WARNING_RESERVED_ID_MACRO - Success
-- Performing Test HAVE_WARNING_CTAD_MAYBE_UNSUPPORTED
-- Performing Test HAVE_WARNING_CTAD_MAYBE_UNSUPPORTED - Failed
-- Using libcxx: cxx
-- Using libcxxfs:
-- Using libcxxabi: cxxabi
-- Tests are enabled
-- Building for: Darwin-17.7.0 x86_64  ; USE_STATIC_LIBRARIES=ON MAKE_STATIC_LIBRARIES=ON SPLIT_SHARED= UNBUNDLED=OFF CCACHE=CCACHE_FOUND-NOTFOUND
-- Using double-conversion: /Users/kolen/items/ClickHouse/contrib/double-conversion : double-conversion
-- Using ssl=1: /Users/kolen/items/ClickHouse/contrib/openssl/include;/Users/kolen/items/ClickHouse/contrib/openssl-cmake/linux_x86_64/include : ssl;crypto
-- Using icu=1:  : icui18n;icuuc;icudata
-- Using Boost: /Users/kolen/items/ClickHouse/contrib/boost : boost_program_options_internal,boost_system_internal,boost_filesystem_internal;boost_system_internal,boost_regex_internal
-- Using zlib-ng: /Users/kolen/items/ClickHouse/contrib/zlib-ng;/Users/kolen/items/ClickHouse/build/contrib/zlib-ng : zlibstatic
-- Using zstd: /Users/kolen/items/ClickHouse/contrib/zstd/lib : zstd
-- Using termcap: /usr/lib/libncurses.dylib
-- Using Poco: /Users/kolen/items/ClickHouse/contrib/poco/Foundation/include/;/Users/kolen/items/ClickHouse/contrib/poco/Util/include/;/Users/kolen/items/ClickHouse/contrib/zlib-ng/;/Users/kolen/items/ClickHouse/build/contrib/zlib-ng/ : PocoFoundation,PocoUtil,PocoNet,PocoNetSSL;ssl;crypto,PocoCrypto;ssl;crypto,PocoXML,PocoData,,,,PocoMongoDB,PocoRedis; MongoDB=1, Redis=1, DataODBC=, NetSSL=1
-- Using lz4: /Users/kolen/items/ClickHouse/contrib/lz4/lib : lz4
-- Using xxhash=1: /Users/kolen/items/ClickHouse/contrib/lz4/lib : lz4
-- Using sparsehash: /Users/kolen/items/ClickHouse/contrib/sparsehash-c11
-- Using rt: apple_rt
-- Using line editing libraries (readline): /usr/local/opt/readline/include : /usr/local/opt/readline/lib/libreadline.a;/usr/lib/libncurses.dylib
-- Performing Test HAVE_READLINE_HISTORY
-- Performing Test HAVE_READLINE_HISTORY - Success
-- Using re2: /Users/kolen/items/ClickHouse/contrib/re2 : re2;  : re2_st
-- Using libgsasl=: LIBGSASL_INCLUDE_DIR-NOTFOUND : LIBGSASL_LIBRARY-NOTFOUND
-- Using librdkafka=:  :
-- Using capnp=1: capnpc
-- Using h3=1: /Users/kolen/items/ClickHouse/contrib/h3/src/h3lib/include : h3
-- Using cpuid=1: /Users/kolen/items/ClickHouse/contrib/libcpuid/include : cpuid
-- Using libxml2: /Users/kolen/items/ClickHouse/contrib/libxml2/include;/Users/kolen/items/ClickHouse/contrib/libxml2-cmake/linux_x86_64/include : libxml2
-- Using brotli=1: /Users/kolen/items/ClickHouse/contrib/brotli/c/include : brotli
-- Using protobuf=1: /Users/kolen/items/ClickHouse/contrib/protobuf/src : libprotobuf : /Users/kolen/items/ClickHouse/build/contrib/protobuf/cmake/protoc
-- Using pdqsort: /Users/kolen/items/ClickHouse/contrib/pdqsort
-- Using hdfs3=:  :
-- Using aws_s3=:  :
-- Using consistent-hashing:  : consistent-hashing
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Checking for module 'arrow'
--   No package 'arrow' found
-- Could not find the Arrow library. Looked for headers in , and for libs in
-- Checking for module 'parquet'
--   No package 'parquet' found
--  Could not find the parquet library. Looked in  system search paths.
-- Using snappy: snappy
-- Using Parquet: arrow_static: ; parquet_static:PARQUET_INCLUDE_DIR-NOTFOUND ; thrift_static
-- Using hyperscan=1: /Users/kolen/items/ClickHouse/contrib/hyperscan/src : hs
-- Using simdjson=ON: simdjson
-- Using rapidjson=1: /Users/kolen/items/ClickHouse/contrib/rapidjson/include
-- Using fastops=0:  :
-- Using snappy: snappy
-- Using internal=ON orc=1: /Users/kolen/items/ClickHouse/contrib/orc/c++/include : orc
-- Using cityhash:  : cityhash
-- Using farmhash:  : farmhash
-- Using metrohash: /Users/kolen/items/ClickHouse/contrib/libmetrohash/src : metrohash
-- Using btrie:  : btrie
-- Using gtest=1: /Users/kolen/items/ClickHouse/contrib/googletest/googletest : gtest_main;gtest :
-- Using cctz: /Users/kolen/items/ClickHouse/contrib/cctz/include : cctz
-- Build without mysqlclient (support for MYSQL dictionary source will be disabled)
-- compiler C   = /usr/bin/clang  -fdiagnostics-color=always  -gdwarf-aranges -msse4.1 -msse4.2 -mpopcnt  -Wall -Wno-unused-command-line-argument  -fno-omit-frame-pointer -mmacosx-version-min=10.14 -O2 -g -DNDEBUG -O3
-- compiler CXX = /usr/bin/clang++  -fdiagnostics-color=always -fsized-deallocation  -gdwarf-aranges -msse4.1 -msse4.2 -mpopcnt   -Wall -Wno-unused-command-line-argument  -Wnon-virtual-dtor -fno-omit-frame-pointer -mmacosx-version-min=10.14 -O2 -g -DNDEBUG -O3
-- LINKER_FLAGS =  -rdynamic -mmacosx-version-min=10.14
-- ZSTD VERSION 1.3.17
-- Using CMake version 3.15.5
-- ZLIB_HEADER_VERSION: 1.2.11
-- ZLIBNG_HEADER_VERSION: 1.9.9
-- Arch detected: 'x86_64'
-- Basearch of 'x86_64' has been detected as: 'x86'
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Looking for sys/sdt.h
-- Looking for sys/sdt.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Check size of _off64_t
-- Check size of _off64_t - failed
-- Check size of __off64_t
-- Check size of __off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Performing Test HAVE_ATTRIBUTE_VISIBILITY_HIDDEN
-- Performing Test HAVE_ATTRIBUTE_VISIBILITY_HIDDEN - Success
-- Performing Test HAVE_ATTRIBUTE_VISIBILITY_INTERNAL
-- Performing Test HAVE_ATTRIBUTE_VISIBILITY_INTERNAL - Success
-- Performing Test HAVE_BUILTIN_CTZL
-- Performing Test HAVE_BUILTIN_CTZL - Success
-- Performing Test HAVE_PTRDIFF_T
-- Performing Test HAVE_PTRDIFF_T - Success
-- Performing Test HAVE_SSE2_INTRIN
-- Performing Test HAVE_SSE2_INTRIN - Success
-- Performing Test HAVE_SSE42CRC_INLINE_ASM
-- Performing Test HAVE_SSE42CRC_INLINE_ASM - Success
-- Performing Test HAVE_SSE42CRC_INTRIN
-- Performing Test HAVE_SSE42CRC_INTRIN - Success
-- Performing Test HAVE_PCLMULQDQ_INTRIN
-- Performing Test HAVE_PCLMULQDQ_INTRIN - Success
-- Architecture-specific source files: arch/x86/x86.c;arch/x86/insert_string_sse.c;arch/x86/deflate_quick.c;arch/x86/fill_window_sse.c;arch/x86/slide_sse.c;arch/x86/crc_folding.c
-- The following features have been enabled:

 * CMAKE_BUILD_TYPE, Build type: RELWITHDEBINFO (selected)
 * ZLIB_COMPAT, Provide a zlib-compatible API
 * WITH_OPTIM, Build with optimisation
 * WITH_NEW_STRATEGIES, Use new strategies
 * SSE42_CRC, Support CRC hash generation using the SSE4.2 instruction set, using "-msse4"
 * SSE42_DEFLATE_QUICK, Support SSE4.2-accelerated quick compression
 * PCLMUL_CRC, Support CRC hash generation using PCLMULQDQ, using "-mpclmul"

-- The following REQUIRED packages have been found:

 * Threads

-- The following features have been disabled:

 * WITH_GZFILEOP, Compile with support for gzFile-related functions
 * WITH_SANITIZERS, Build with address sanitizer and all supported sanitizers other than memory sanitizer
 * WITH_MSAN, Build with memory sanitizer
 * WITH_FUZZERS, Build test/fuzz
 * MAINTAINER, Build with maintainer warnings and tests enabled

-- The following OPTIONAL packages have not been found:

 * Arrow
 * Parquet

-- The ASM compiler identification is AppleClang
-- Found assembler: /Library/Developer/CommandLineTools/usr/bin/clang
-- Check if the system is big endian
-- Searching 16 bit integer
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for byteswap.h
-- Looking for byteswap.h - not found
-- Looking for sys/endian.h
-- Looking for sys/endian.h - not found
-- Looking for sys/mman.h
-- Looking for sys/mman.h - found
-- Looking for sys/resource.h
-- Looking for sys/resource.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for sys/uio.h
-- Looking for sys/uio.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for windows.h
-- Looking for windows.h - not found
-- Looking for zlibVersion in z
-- Looking for zlibVersion in z - found
-- Looking for lzo1x_1_15_compress in lzo2
-- Looking for lzo1x_1_15_compress in lzo2 - found
-- Performing Test HAVE_VISUAL_STUDIO_ARCH_AVX
-- Performing Test HAVE_VISUAL_STUDIO_ARCH_AVX - Failed
-- Performing Test HAVE_VISUAL_STUDIO_ARCH_AVX2
-- Performing Test HAVE_VISUAL_STUDIO_ARCH_AVX2 - Failed
-- Performing Test HAVE_CLANG_MAVX
-- Performing Test HAVE_CLANG_MAVX - Success
-- Performing Test HAVE_CLANG_MBMI2
-- Performing Test HAVE_CLANG_MBMI2 - Success
-- Performing Test HAVE_BUILTIN_EXPECT
-- Performing Test HAVE_BUILTIN_EXPECT - Success
-- Performing Test HAVE_BUILTIN_CTZ
-- Performing Test HAVE_BUILTIN_CTZ - Success
-- Performing Test SNAPPY_HAVE_SSSE3
-- Performing Test SNAPPY_HAVE_SSSE3 - Success
-- Performing Test SNAPPY_HAVE_BMI2
-- Performing Test SNAPPY_HAVE_BMI2 - Failed
-- Looking for mmap
-- Looking for mmap - found
-- Looking for sysconf
-- Looking for sysconf - found
-- Performing Test ORC_CXX_HAS_INITIALIZER_LIST
-- Performing Test ORC_CXX_HAS_INITIALIZER_LIST - Success
-- Performing Test ORC_CXX_HAS_NOEXCEPT
-- Performing Test ORC_CXX_HAS_NOEXCEPT - Success
-- Performing Test ORC_CXX_HAS_NULLPTR
-- Performing Test ORC_CXX_HAS_NULLPTR - Success
-- Performing Test ORC_CXX_HAS_OVERRIDE
-- Performing Test ORC_CXX_HAS_OVERRIDE - Success
-- Performing Test ORC_CXX_HAS_UNIQUE_PTR
-- Performing Test ORC_CXX_HAS_UNIQUE_PTR - Success
-- Performing Test ORC_CXX_HAS_CSTDINT
-- Performing Test ORC_CXX_HAS_CSTDINT - Success
-- Performing Test ORC_CXX_HAS_THREAD_LOCAL
-- Performing Test ORC_CXX_HAS_THREAD_LOCAL - Success
-- Performing Test HAS_PREAD
-- Performing Test HAS_PREAD - Success
-- Performing Test HAS_STRPTIME
-- Performing Test HAS_STRPTIME - Success
-- Performing Test HAS_STOLL
-- Performing Test HAS_STOLL - Success
-- Performing Test INT64_IS_LL
-- Performing Test INT64_IS_LL - Success
-- Performing Test HAS_DIAGNOSTIC_PUSH
-- Performing Test HAS_DIAGNOSTIC_PUSH - Success
-- Performing Test HAS_STD_ISNAN
-- Performing Test HAS_STD_ISNAN - Success
-- Performing Test HAS_STD_MUTEX
-- Performing Test HAS_STD_MUTEX - Success
-- Performing Test NEEDS_REDUNDANT_MOVE
-- Performing Test NEEDS_REDUNDANT_MOVE - Success
-- Performing Test HAS_PRE_1970
-- Performing Test HAS_PRE_1970 - Success
-- Performing Test HAS_POST_2038
-- Performing Test HAS_POST_2038 - Failed
-- Performing Test NEEDS_Z_PREFIX
-- Performing Test NEEDS_Z_PREFIX - Failed
-- Looking for arpa/inet.h
-- Looking for arpa/inet.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for getopt.h
-- Looking for getopt.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for netdb.h
-- Looking for netdb.h - found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - found
-- Looking for signal.h
-- Looking for signal.h - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for sys/ioctl.h
-- Looking for sys/ioctl.h - found
-- Looking for sys/param.h
-- Looking for sys/param.h - found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/un.h
-- Looking for sys/un.h - found
-- Looking for poll.h
-- Looking for poll.h - found
-- Looking for sys/poll.h
-- Looking for sys/poll.h - found
-- Looking for sys/select.h
-- Looking for sys/select.h - found
-- Looking for sched.h
-- Looking for sched.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for gethostbyname_r
-- Looking for gethostbyname_r - not found
-- Looking for strerror_r
-- Looking for strerror_r - found
-- Looking for sched_get_priority_max
-- Looking for sched_get_priority_max - found
-- Looking for sched_get_priority_min
-- Looking for sched_get_priority_min - found
-- Performing Test STRERROR_R_CHAR_P
-- Performing Test STRERROR_R_CHAR_P - Failed
-- Using OpenSSL from /Users/kolen/items/ClickHouse/contrib/openssl
-- Found APR: /usr/lib/libapr-1.dylib
-- Found APRUTIL: /usr/lib/libaprutil-1.dylib
-- Found APACHE: /usr/include/apache2
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.17")
-- Performing Test ARCH_64_BIT
-- Performing Test ARCH_64_BIT - Success
-- Performing Test ARCH_32_BIT
-- Performing Test ARCH_32_BIT - Failed
-- Build type RELWITHDEBINFO
-- Boost version: 1.71.0
-- Build date: 2000-01-01
-- Looking for include file intrin.h
-- Looking for include file intrin.h - not found
-- Looking for C++ include intrin.h
-- Looking for C++ include intrin.h - not found
-- Looking for include file x86intrin.h
-- Looking for include file x86intrin.h - found
-- Looking for C++ include x86intrin.h
-- Looking for C++ include x86intrin.h - found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Looking for _aligned_malloc
-- Looking for _aligned_malloc - not found
-- Performing Test HAS_C_HIDDEN
-- Performing Test HAS_C_HIDDEN - Success
-- Performing Test HAS_CXX_HIDDEN
-- Performing Test HAS_CXX_HIDDEN - Success
-- Looking for _LIBCPP_VERSION
-- Looking for _LIBCPP_VERSION - found
-- Performing Test HAVE_AVX512
-- Performing Test HAVE_AVX512 - Failed
-- Building without AVX512 support
-- Performing Test HAVE_CC_BUILTIN_ASSUME_ALIGNED
-- Performing Test HAVE_CC_BUILTIN_ASSUME_ALIGNED - Success
-- Performing Test HAVE_CXX_BUILTIN_ASSUME_ALIGNED
-- Performing Test HAVE_CXX_BUILTIN_ASSUME_ALIGNED - Success
-- Performing Test HAVE__BUILTIN_CONSTANT_P
-- Performing Test HAVE__BUILTIN_CONSTANT_P - Success
-- Performing Test C_FLAG_Wvla
-- Performing Test C_FLAG_Wvla - Success
-- Performing Test C_FLAG_Wpointer_arith
-- Performing Test C_FLAG_Wpointer_arith - Success
-- Performing Test C_FLAG_Wstrict_prototypes
-- Performing Test C_FLAG_Wstrict_prototypes - Success
-- Performing Test C_FLAG_Wmissing_prototypes
-- Performing Test C_FLAG_Wmissing_prototypes - Success
-- Performing Test CXX_FLAG_Wvla
-- Performing Test CXX_FLAG_Wvla - Success
-- Performing Test CXX_FLAG_Wpointer_arith
-- Performing Test CXX_FLAG_Wpointer_arith - Success
-- Performing Test CC_SELF_ASSIGN
-- Performing Test CC_SELF_ASSIGN - Success
-- Performing Test CXX_SELF_ASSIGN
-- Performing Test CXX_SELF_ASSIGN - Success
-- Performing Test CC_PAREN_EQUALITY
-- Performing Test CC_PAREN_EQUALITY - Success
-- Performing Test CXX_UNUSED_CONST_VAR
-- Performing Test CXX_UNUSED_CONST_VAR - Success
-- Performing Test CXX_IGNORED_ATTR
-- Performing Test CXX_IGNORED_ATTR - Success
-- Performing Test CXX_WEAK_VTABLES
-- Performing Test CXX_WEAK_VTABLES - Success
-- Performing Test CXX_MISSING_DECLARATIONS
-- Performing Test CXX_MISSING_DECLARATIONS - Success
-- Performing Test CXX_UNUSED_LOCAL_TYPEDEFS
-- Performing Test CXX_UNUSED_LOCAL_TYPEDEFS - Success
-- Performing Test CXX_WUNUSED_VARIABLE
-- Performing Test CXX_WUNUSED_VARIABLE - Success
-- Building for current host CPU:
-- Looking for mmap
-- Looking for mmap - found
-- Doxygen not found, unable to generate API reference
-- Sphinx not found, unable to generate developer reference
-- Checking for module 'libpcre>=8.41'
--   Found libpcre, version 8.43
-- PCRE version 8.41 or above
-- /Users/kolen/items/ClickHouse/utils: Have 5530 megabytes of memory. Limiting concurrent linkers jobs to 1 and compiler jobs to OFF
-- /Users/kolen/items/ClickHouse/dbms: Have 5528 megabytes of memory. Limiting concurrent linkers jobs to 1 and compiler jobs to 3
-- Will build ClickHouse 19.19.1.1 revision 54430
-- Looking for readpassphrase
-- Looking for readpassphrase - found
-- Target check already exists
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/kolen/items/ClickHouse/build
~/items/ClickHouse/build % ninja
[0/2] Re-checking globbed directories...
[49/4433] Linking CXX static library contrib/libcxxabi-cmake/libcxxabi.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/libcxxabi-cmake/libcxxabi.a(cxa_unexpected.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/libcxxabi-cmake/libcxxabi.a(cxa_unexpected.cpp.o) has no symbols
[74/4433] Linking CXX static library contrib/libcxx-cmake/libcxx.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/libcxx-cmake/libcxx.a(functional.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/libcxx-cmake/libcxx.a(typeinfo.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/libcxx-cmake/libcxx.a(functional.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/libcxx-cmake/libcxx.a(typeinfo.cpp.o) has no symbols
[110/4433] Linking CXX static library contrib/capnproto-cmake/libkj.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/capnproto-cmake/libkj.a(filesystem-disk-win32.c++.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/capnproto-cmake/libkj.a(filesystem-disk-win32.c++.o) has no symbols
[111/4433] Linking CXX static library contrib/capnproto-cmake/libcapnp.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/capnproto-cmake/libcapnp.a(list.c++.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/capnproto-cmake/libcapnp.a(list.c++.o) has no symbols
[120/4433] Building CXX object contrib/boost-cmake/CMakeFiles/boost_filesystem_internal.dir/__/boost/libs/filesystem/src/codecvt_error_category.cpp.o
../contrib/boost/libs/filesystem/src/codecvt_error_category.cpp:34:9: warning: '(anonymous namespace)::codecvt_error_cat' has virtual functions but non-virtual destructor [-Wnon-virtual-dtor]
  class codecvt_error_cat : public boost::system::error_category
        ^
1 warning generated.
[140/4433] Linking CXX static library contrib/boost-cmake/libboost_filesystem_internal.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/libboost_filesystem_internal.a(windows_file_codecvt.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/libboost_filesystem_internal.a(windows_file_codecvt.cpp.o) has no symbols
[144/4433] Linking CXX static library contrib/boost-cmake/libboost_regex_internal.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/libboost_regex_internal.a(icu.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/libboost_regex_internal.a(instances.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/libboost_regex_internal.a(regex_debug.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/libboost_regex_internal.a(usinstances.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/libboost_regex_internal.a(w32_regex_traits.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/libboost_regex_internal.a(winstances.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/libboost_regex_internal.a(icu.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/libboost_regex_internal.a(instances.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/libboost_regex_internal.a(regex_debug.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/libboost_regex_internal.a(usinstances.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/libboost_regex_internal.a(w32_regex_traits.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/libboost_regex_internal.a(winstances.cpp.o) has no symbols
[156/4433] Linking CXX static library contrib/boost-cmake/libboost_program_options_internal.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/libboost_program_options_internal.a(winmain.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: contrib/boost-cmake/libboost_program_options_internal.a(winmain.cpp.o) has no symbols
[480/4433] Building CXX object contrib/poco/XML/CMakeFiles/XML.dir/src/xmlparse.cpp.o
In file included from ../contrib/poco/XML/src/xmlparse.cpp:43:
../contrib/poco/XML/src/siphash.h:156:14: warning: unused function 'sip_tobin' [-Wunused-function]
static void *sip_tobin(void *dst, uint64_t u64) {
             ^
../contrib/poco/XML/src/siphash.h:271:12: warning: unused function 'sip24_valid' [-Wunused-function]
static int sip24_valid(void) {
           ^
2 warnings generated.
[1456/4433] Building ASM object contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aesni-mb-x86_64.s.o
FAILED: contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aesni-mb-x86_64.s.o
/Library/Developer/CommandLineTools/usr/bin/clang -DAES_ASM -DBSAES_ASM -DECP_NISTZ256_ASM -DENGINESDIR=\"/usr/lib/engines-3\" -DGHASH_ASM -DKECCAK1600_ASM -DL_ENDIAN -DMD5_ASM -DMODULESDIR=\"/usr/local/lib/ossl-modules\" -DOPENSSLDIR=\"/etc/ssl\" -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_NODELETE -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -isystem ../contrib/openssl-cmake/linux_x86_64/include -isystem ../contrib/openssl-cmake/linux_x86_64/include_private -isystem ../contrib/openssl/include -isystem ../contrib/openssl/providers/common/include -isystem ../contrib/openssl/providers/implementations/include -isystem ../contrib/openssl/crypto -isystem ../contrib/openssl/crypto/include -isystem ../contrib/openssl/crypto/ec/curve448 -isystem ../contrib/openssl/crypto/ec/curve448/arch_32 -isystem ../contrib/openssl -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -O2 -g -DNDEBUG   -D OS_DARWIN -Wno-unused-command-line-argument -Wno-reserved-id-macro -MD -MT contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aesni-mb-x86_64.s.o -MF contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aesni-mb-x86_64.s.o.d -o contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aesni-mb-x86_64.s.o -c contrib/openssl/crypto/aes/aesni-mb-x86_64.s
contrib/openssl/crypto/aes/aesni-mb-x86_64.s:6:1: error: unknown directive
.type aesni_multi_cbc_encrypt,@function
^
contrib/openssl/crypto/aes/aesni-mb-x86_64.s:7:8: error: invalid alignment value
.align 32
       ^
contrib/openssl/crypto/aes/aesni-mb-x86_64.s:92:8: error: invalid alignment value
.align 32
       ^
contrib/openssl/crypto/aes/aesni-mb-x86_64.s:199:8: error: invalid alignment value
.align 32
       ^
contrib/openssl/crypto/aes/aesni-mb-x86_64.s:259:1: error: unknown directive
.size aesni_multi_cbc_encrypt,.-aesni_multi_cbc_encrypt
^
contrib/openssl/crypto/aes/aesni-mb-x86_64.s:262:1: error: unknown directive
.type aesni_multi_cbc_decrypt,@function
^
contrib/openssl/crypto/aes/aesni-mb-x86_64.s:263:8: error: invalid alignment value
.align 32
       ^
contrib/openssl/crypto/aes/aesni-mb-x86_64.s:344:8: error: invalid alignment value
.align 32
       ^
contrib/openssl/crypto/aes/aesni-mb-x86_64.s:451:8: error: invalid alignment value
.align 32
       ^
contrib/openssl/crypto/aes/aesni-mb-x86_64.s:506:1: error: unknown directive
.size aesni_multi_cbc_decrypt,.-aesni_multi_cbc_decrypt
^
[1458/4433] Building ASM object contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aes-x86_64.s.o
FAILED: contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aes-x86_64.s.o
/Library/Developer/CommandLineTools/usr/bin/clang -DAES_ASM -DBSAES_ASM -DECP_NISTZ256_ASM -DENGINESDIR=\"/usr/lib/engines-3\" -DGHASH_ASM -DKECCAK1600_ASM -DL_ENDIAN -DMD5_ASM -DMODULESDIR=\"/usr/local/lib/ossl-modules\" -DOPENSSLDIR=\"/etc/ssl\" -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_NODELETE -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -isystem ../contrib/openssl-cmake/linux_x86_64/include -isystem ../contrib/openssl-cmake/linux_x86_64/include_private -isystem ../contrib/openssl/include -isystem ../contrib/openssl/providers/common/include -isystem ../contrib/openssl/providers/implementations/include -isystem ../contrib/openssl/crypto -isystem ../contrib/openssl/crypto/include -isystem ../contrib/openssl/crypto/ec/curve448 -isystem ../contrib/openssl/crypto/ec/curve448/arch_32 -isystem ../contrib/openssl -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -O2 -g -DNDEBUG   -D OS_DARWIN -Wno-unused-command-line-argument -Wno-reserved-id-macro -MD -MT contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aes-x86_64.s.o -MF contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aes-x86_64.s.o.d -o contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aes-x86_64.s.o -c contrib/openssl/crypto/aes/aes-x86_64.s
contrib/openssl/crypto/aes/aes-x86_64.s:2:1: error: unknown directive
.type _x86_64_AES_encrypt,@function
^
contrib/openssl/crypto/aes/aes-x86_64.s:154:1: error: unknown directive
.size _x86_64_AES_encrypt,.-_x86_64_AES_encrypt
^
contrib/openssl/crypto/aes/aes-x86_64.s:155:1: error: unknown directive
.type _x86_64_AES_encrypt_compact,@function
^
contrib/openssl/crypto/aes/aes-x86_64.s:327:1: error: unknown directive
.size _x86_64_AES_encrypt_compact,.-_x86_64_AES_encrypt_compact
^
contrib/openssl/crypto/aes/aes-x86_64.s:329:1: error: unknown directive
.type AES_encrypt,@function
^
contrib/openssl/crypto/aes/aes-x86_64.s:332:1: error: unknown directive
.hidden asm_AES_encrypt
^
contrib/openssl/crypto/aes/aes-x86_64.s:394:1: error: unknown directive
.size AES_encrypt,.-AES_encrypt
^
contrib/openssl/crypto/aes/aes-x86_64.s:395:1: error: unknown directive
.type _x86_64_AES_decrypt,@function
^
contrib/openssl/crypto/aes/aes-x86_64.s:549:1: error: unknown directive
.size _x86_64_AES_decrypt,.-_x86_64_AES_decrypt
^
contrib/openssl/crypto/aes/aes-x86_64.s:550:1: error: unknown directive
.type _x86_64_AES_decrypt_compact,@function
^
contrib/openssl/crypto/aes/aes-x86_64.s:774:1: error: unknown directive
.size _x86_64_AES_decrypt_compact,.-_x86_64_AES_decrypt_compact
^
contrib/openssl/crypto/aes/aes-x86_64.s:776:1: error: unknown directive
.type AES_decrypt,@function
^
contrib/openssl/crypto/aes/aes-x86_64.s:779:1: error: unknown directive
.hidden asm_AES_decrypt
^
contrib/openssl/crypto/aes/aes-x86_64.s:843:1: error: unknown directive
.size AES_decrypt,.-AES_decrypt
^
contrib/openssl/crypto/aes/aes-x86_64.s:845:1: error: unknown directive
.type AES_set_encrypt_key,@function
^
contrib/openssl/crypto/aes/aes-x86_64.s:864:1: error: unknown directive
.size AES_set_encrypt_key,.-AES_set_encrypt_key
^
contrib/openssl/crypto/aes/aes-x86_64.s:866:1: error: unknown directive
.type _x86_64_AES_set_encrypt_key,@function
^
contrib/openssl/crypto/aes/aes-x86_64.s:1104:1: error: unknown directive
.size _x86_64_AES_set_encrypt_key,.-_x86_64_AES_set_encrypt_key
^
contrib/openssl/crypto/aes/aes-x86_64.s:1106:1: error: unknown directive
.type AES_set_decrypt_key,@function
^
contrib/openssl/crypto/aes/aes-x86_64.s:1291:1: error: unknown directive
.size AES_set_decrypt_key,.-AES_set_decrypt_key
^
contrib/openssl/crypto/aes/aes-x86_64.s:1293:1: error: unknown directive
.type AES_cbc_encrypt,@function
^
contrib/openssl/crypto/aes/aes-x86_64.s:1297:1: error: unknown directive
.hidden asm_AES_cbc_encrypt
^
contrib/openssl/crypto/aes/aes-x86_64.s:1751:1: error: unknown directive
.size AES_cbc_encrypt,.-AES_cbc_encrypt
^
contrib/openssl/crypto/aes/aes-x86_64.s:1752:8: error: invalid alignment value
.align 64
       ^
contrib/openssl/crypto/aes/aes-x86_64.s:2142:8: error: invalid alignment value
.align 64
       ^
contrib/openssl/crypto/aes/aes-x86_64.s:2537:8: error: invalid alignment value
.align 64
       ^
[1461/4433] Building C object contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/bn/asm/x86_64-gcc.c.o
ninja: build stopped: subcommand failed.
```
</details>

```
~/items/ClickHouse/build % git diff
~/items/ClickHouse/build % git describe --always
v19.19.1.1929-testing-81-gcea2903e72
```

**Comment by alexey-milovidov** [comment]
`unknown warning option '-Wno-ctad-maybe-unsupported'`
Fixed in https://github.com/ClickHouse/ClickHouse/commit/cea2903e72d4378b382f9b8ae616c01f512483dc#diff-eabb2b894359aa83d33168e3117959dcR55

**Comment by kolen** [comment]
This issue is not about `-Wno-ctad-maybe-unsupported`, that error just interfered to reproduce described problem cleanly. I updated output in this issue with build log from current master (cea2903e72d4378b382f9b8ae616c01f512483dc).

This issue is about `error: unknown directive`, `error: invalid alignment value`, ... in `.S` assembly files in contrib/openssl.

**Comment by qoega** [comment]
Should be fixed in #8297

**Comment by kolen** [comment]
While it fixes problem with `contrib/openssl`, this problem persists with ICU, in `contrib/icu-cmake`

```
[1681/4437] Building ASM object contrib/icu-cmake/CMakeFiles/icudata.dir/__/icudata/icudt66l_dat.S.o
FAILED: contrib/icu-cmake/CMakeFiles/icudata.dir/__/icudata/icudt66l_dat.S.o
/Library/Developer/CommandLineTools/usr/bin/clang -DDEFAULT_ICU_PLUGINS=\"/dev/null\" -DU_HAVE_ELF_H=1 -DU_HAVE_STRTOD_L=1 -DU_HAVE_XLOCALE_H=0 -D_REENTRANT -isystem ../contrib/libcxx/include -isystem ../contrib/libcxxabi/include -mmacosx-version-min=10.14 -O2 -g -DNDEBUG   -D OS_DARWIN -Wno-unused-command-line-argument -Wno-reserved-id-macro -MD -MT contrib/icu-cmake/CMakeFiles/icudata.dir/__/icudata/icudt66l_dat.S.o -MF contrib/icu-cmake/CMakeFiles/icudata.dir/__/icudata/icudt66l_dat.S.o.d -o contrib/icu-cmake/CMakeFiles/icudata.dir/__/icudata/icudt66l_dat.S.o -c ../contrib/icudata/icudt66l_dat.S
../contrib/icudata/icudt66l_dat.S:2:20: error: unexpected token in '.section' directive
 .section .note.GNU-stack,"",%progbits
                   ^
../contrib/icudata/icudt66l_dat.S:3:18: error: unexpected token in '.section' directive
 .section .rodata
                 ^
../contrib/icudata/icudt66l_dat.S:8:2: error: unknown directive
 .type icudt66_dat,%object
 ^
../contrib/icudata/icudt66l_dat.S:218688:1: error: unknown directive
.size icudt66_dat, .-icudt66_dat
^
[1686/4437] Building CXX object contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/server/TThreadedServer.cpp.o
ninja: build stopped: subcommand failed.
```

(I checked on that PR applied as patch on current master 297a5fd6278cffa4ef16e4fd891c2b541effec28)

**Comment by TisonKun** [comment]
Similar problem reported.

[output.txt](https://github.com/ClickHouse/ClickHouse/files/3997517/output.txt)

**Comment by kolen** [comment]
The problem was fixed in #8297. No longer occurs for me (although similar problem occurs, #8530).
