### ISSUE TITLE
CREATE MV ON CLUSTER trying to find source tables in default database

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#8445]
Execute all on test database after it is created.

```sql
CREATE DATABASE test ON CLUSTER '{cluster}';

CREATE TABLE test ON CLUSTER '{cluster}'
(
    date     Date,
    used_key Int16
)
    ENGINE Memory;

CREATE TABLE test2 ON CLUSTER '{cluster}'
(
    date     Date,
    used_key Int16
)
    ENGINE Memory;
```

Calling this query is trying to find `default.test`

```sql
CREATE MATERIALIZED VIEW IF NOT EXISTS mv ON CLUSTER '{cluster}' TO test2
AS
SELECT *
FROM test;
```

This query is correctly looking for `test.test` (in the database it's executed)

```sql
CREATE MATERIALIZED VIEW IF NOT EXISTS mv TO test2
AS
SELECT *
FROM test;
```

For some reason adding `ON CLUSTER` clause to CREATE MV changes default table lookup db to `default` but should stay set to db the query is being executed on.

v19.17.4.11

**Comment by den-crane** [comment]
related https://github.com/ClickHouse/ClickHouse/issues/6104

**Comment by simPod** [comment]
Definitely, can close, IMO it will get resolved with those.

**Comment by filimonov** [comment]
Should be fixed in #14211 (clickhouse versions 20.10 and newer).

**Comment by simPod** [comment]
@filimonov I'm running 20.12 now and the issue is still there.

Issuing http query to `database=__tests_1609349250_d5a96f5b`

```sql
CREATE MATERIALIZED VIEW IF NOT EXISTS ab
    ON CLUSTER '{cluster}'
    TO b
AS
SELECT toStartOfMinute(fetched_at) AS fetched_at,
    sumState(x) as xx
FROM a
GROUP BY fetched_at, device_id, port_id
```

And the error is

```
clickhouse-01	9000	60	Code: 60, e.displayText() = DB::Exception: Table default.a doesn\'t exist. (version 20.12.4.5 (official build))	0	0
Code: 60, e.displayText() = DB::Exception: There was an error on [clickhouse-01:9000]: Code: 60, e.displayText() = DB::Exception: Table default.a doesn't exist. (version 20.12.4.5 (official build)) (version 20.12.4.5 (official build))
```

**Comment by simPod** [comment]
This works

```
CREATE MATERIALIZED VIEW IF NOT EXISTS ab
    ON CLUSTER '{cluster}'
    TO b
AS
SELECT toStartOfMinute(fetched_at) AS fetched_at,
    sumState(x) as xx
FROM __tests_1609372372_f5c48348.a
GROUP BY fetched_at
```

so I don't have to write ```TO __tests_1609372372_f5c48348.b``` now

**Comment by den-crane** [comment]
still not working 22.3.4.20

**Comment by Walenogg** [comment]
@den-crane checked now

Version with error:
```
22.3.20.29
```

Versions without (22.8+):
```
22.8.13.20
22.8.21.38
22.11.6.44
23.8.16.16
24.10.1.2812
24.11.3.66
```
So, may be it's time to close issue
