### ISSUE TITLE
JOINs with FINAL keyword

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#8655]
When joining with a table, the keyword final does not function as should.
Woraround: when you create a view with the FINAL and in the SQL you join to that view, the join works fine, however, this is not ideal since we are adding another step (i.e. View)

**Comment by 4ertus2** [comment]
Could you attach a sample and expected result, please? It's not clear for which of joining tables FINAL should be applyed.

**Comment by alex-zaitsev** [comment]
Right side does not respect the FINAL, I guess.

**Comment by 4ertus2** [comment]
I.e. we have multiple or comma join with FINAL. Which table we should to aply FINAL? What if the query is big? It's very easy to make a mistake changing table orders.

I think the solution is to make special syntax: `FINAL table2, table2` and forbid FINAL without table specification for JOINs.

**Comment by filimonov** [comment]
I think the most natural is to parse FINAL as a part of table name.

The query in original request was like:
```sql
select cols from from kafka_table inner join customer_data final using (customer_id, tenant_id) where tenant_id != 0;
```

So if we have comma join i would expect repeating final for every table which should be 'finalized'.

i.e.
```
 select * from tableX final; -- no joins
 select * from tableX final, tableY final; -- comma join, both 'final'
 select * from tableX, tableY final; -- comma join, right-hand with final
 select * from tableX left join tableY final; -- right-hand with final, left-hand w/o
 select * from tableX final left join tableY; -- left-hand with final, right-hand w/o
```
 
etc.

**Comment by alexey-milovidov** [comment]
That's reasonable, let's do that. @chertus?

**Comment by acelemore** [comment]
Looks like the right table doesnt respect FINAL
can use sub select to do that 
eg.

SELECT * FROM A a FINAL LEFT JOIN (SELECT * FROM B FINAL) b ON a.k = b.k

**Comment by alexey-milovidov** [comment]
@vdimir What do you think about supporting this feature?

**Comment by k3rnL** [comment]
Hello, is this fixed ? Seems the issue is still present in 21.3.15.4

**Comment by wenyuanLv** [comment]
Hello, is this fixed ? Seems the issue is still present in  21.8.4.51

**Comment by alexey-milovidov** [comment]
#31796

**Comment by alex-zaitsev** [comment]
Fixed by #40945

**Comment by kitaisreal** [comment]
@alex-zaitsev this is not fix, it is setting that forces final to all tables in query. In new infrastructure client can decide to which table in JOIN he wants to apply FINAL.

**Comment by AnatoliyYakimov** [comment]
Any updates on this? Right table in joins still doesn't respect final?

**Comment by alexey-milovidov** [comment]
@AnatoliyYakimov The feature is in active development. It is not ready, but available for preview.
This is how to enable it for preview:
```
SET allow_experimental_analyzer = 1;
```

**Comment by pavelgur** [comment]
Issue is present in ClickHouse Cloud production v23.8.

**Comment by MathiasGr** [comment]
On my side (ClickHouse Cloud), I still see the `FINAL` table name suffix not working on joins, but what has worked for me is the query-global `FINAL` setting:

```
SETTINGS final = 1
```
