### ISSUE TITLE
Keeper operations are slow

### ISSUE THREAD

**Issue by sigxcpu76** [ClickHouse/ClickHouse#87223]
### Describe the situation

In ClickHouse `25.8.x` all the `ON CLUSTER` DDL operations are slow. This behavior does not occur in `25.7.x` and below.

Creating or dropping a database usually takes less than 100ms. In `25.8.x` takes many seconds. Downgrading to `25.7` restores the fast operations.

See below for `25.8`:

```
Row 1:
──────
hostname:                               chi-analytics-analytics-0-0-0.chi-analytics-analytics-0-0.analytics.svc.cluster.local
type:                                   QueryFinish
event_date:                             2025-09-16
event_time:                             2025-09-16 15:51:55
event_time_microseconds:                2025-09-16 15:51:55.464647
query_start_time:                       2025-09-16 15:50:36
query_start_time_microseconds:          2025-09-16 15:50:36.833929
query_duration_ms:                      78630
read_rows:                              2
read_bytes:                             138
written_rows:                           0
written_bytes:                          0
result_rows:                            2
result_bytes:                           49918
memory_usage:                           86672
current_database:                       default
query:                                  drop database cici on cluster '{cluster}';
formatted_query:
normalized_query_hash:                  9588658805668712464
query_kind:                             Drop
databases:                              ['cici']
tables:                                 []
columns:                                []
partitions:                             []
projections:                            []
views:                                  []
exception_code:                         0
exception:
stack_trace:
is_initial_query:                       1
user:                                   default
query_id:                               156793f9-d9d1-46be-8274-0b290d43e15e
address:                                ::ffff:127.0.0.1
port:                                   51628
initial_user:                           default
initial_query_id:                       156793f9-d9d1-46be-8274-0b290d43e15e
initial_address:                        ::ffff:127.0.0.1
initial_port:                           51628
initial_query_start_time:               2025-09-16 15:50:36
initial_query_start_time_microseconds:  2025-09-16 15:50:36.833929
interface:                              1
is_secure:                              0
os_user:
client_hostname:                        chi-analytics-analytics-0-0-0.chi-analytics-analytics-0-0.analytics.svc.cluster.local
client_name:                            ClickHouse client
client_revision:                        54479
client_version_major:                   25
client_version_minor:                   8
client_version_patch:                   3
script_query_number:                    1
script_line_number:                     1
http_method:                            0
http_user_agent:
http_referer:
forwarded_for:
quota_key:
distributed_depth:                      0
revision:                               54503
log_comment:
thread_ids:                             [1372,1438]
peak_threads_usage:                     2
ProfileEvents:                          {'Query':1,'InitialQuery':1,'QueriesWithSubqueries':1,'NetworkReceiveElapsedMicroseconds':1281,'NetworkSendElapsedMicroseconds':36573,'NetworkSendBytes':785033,'GlobalThreadPoolJobs':1,'ZooKeeperTransactions':98,'ZooKeeperCreate':1,'ZooKeeperGet':2,'ZooKeeperMulti':95,'ZooKeeperMultiRead':91,'ZooKeeperMultiWrite':4,'SelectedRows':2,'SelectedBytes':138,'ContextLock':206,'RealTimeMicroseconds':157254456,'UserTimeMicroseconds':98750,'SystemTimeMicroseconds':38268,'OSCPUWaitMicroseconds':1491,'OSCPUVirtualTimeMicroseconds':137017,'OSReadChars':1769,'OSWriteChars':8,'InterfaceNativeSendBytes':785033,'ConcurrencyControlSlotsGranted':1,'ConcurrencyControlSlotsAcquiredNonCompeting':1}
Settings:                               {'connect_timeout_with_failover_ms':'1000','use_uncompressed_cache':'0','load_balancing':'nearest_hostname','distributed_aggregation_memory_efficient':'1','parallel_distributed_insert_select':'0','do_not_merge_across_partitions_select_final':'1','os_thread_priority':'2','log_queries':'1','join_use_nulls':'1','prefer_localhost_replica':'0','parallel_view_processing':'1','input_format_parquet_use_native_reader_v3':'1','date_time_input_format':'best_effort','output_format_json_quote_64bit_integers':'1'}
used_aggregate_functions:               []
used_aggregate_function_combinators:    []
used_database_engines:                  []
used_data_type_families:                []
used_dictionaries:                      []
used_formats:                           []
used_functions:                         []
used_storages:                          []
used_table_functions:                   []
used_executable_user_defined_functions: []
used_sql_user_defined_functions:        []
used_row_policies:                      []
used_privileges:                        ['DROP DATABASE ON cici.*','CLUSTER ON *.*']
missing_privileges:                     []
transaction_id:                         (0,0,'00000000-0000-0000-0000-000000000000')
query_cache_usage:                      None
asynchronous_read_counters:             {}
```

and `25.7`

```
hostname:                               chi-analytics-analytics-0-0-0.chi-analytics-analytics-0-0.analytics.svc.cluster.local
type:                                   QueryFinish
event_date:                             2025-09-16
event_time:                             2025-09-16 19:10:58
event_time_microseconds:                2025-09-16 19:10:58.969408
query_start_time:                       2025-09-16 19:10:58
query_start_time_microseconds:          2025-09-16 19:10:58.909348
query_duration_ms:                      60
read_rows:                              2
read_bytes:                             142
written_rows:                           0
written_bytes:                          0
result_rows:                            2
result_bytes:                           25088
memory_usage:                           35800
current_database:                       default
query:                                  drop database cici on cluster '{cluster}';
formatted_query:
normalized_query_hash:                  9588658805668712464
query_kind:                             Drop
databases:                              ['cici']
tables:                                 []
columns:                                []
partitions:                             []
projections:                            []
views:                                  []
exception_code:                         0
exception:
stack_trace:
is_initial_query:                       1
user:                                   default
query_id:                               7fc0ba56-54bc-4370-ac2c-e19ef587e011
address:                                ::ffff:127.0.0.1
port:                                   58970
initial_user:                           default
initial_query_id:                       7fc0ba56-54bc-4370-ac2c-e19ef587e011
initial_address:                        ::ffff:127.0.0.1
initial_port:                           58970
initial_query_start_time:               2025-09-16 19:10:58
initial_query_start_time_microseconds:  2025-09-16 19:10:58.909348
interface:                              1
is_secure:                              0
os_user:
client_hostname:                        chi-analytics-analytics-0-0-0.chi-analytics-analytics-0-0.analytics.svc.cluster.local
client_name:                            ClickHouse client
client_revision:                        54479
client_version_major:                   25
client_version_minor:                   7
client_version_patch:                   6
script_query_number:                    1
script_line_number:                     1
http_method:                            0
http_user_agent:
http_referer:
forwarded_for:
quota_key:
distributed_depth:                      0
revision:                               54505
log_comment:
thread_ids:                             [1168,1254]
peak_threads_usage:                     2
ProfileEvents:                          {'Query':1,'InitialQuery':1,'QueriesWithSubqueries':1,'NetworkSendElapsedMicroseconds':140,'NetworkSendBytes':3829,'GlobalThreadPoolJobs':1,'ZooKeeperTransactions':9,'ZooKeeperCreate':1,'ZooKeeperGet':2,'ZooKeeperMulti':6,'ZooKeeperMultiRead':2,'ZooKeeperMultiWrite':4,'SelectedRows':2,'SelectedBytes':142,'ContextLock':27,'RealTimeMicroseconds':112349,'UserTimeMicroseconds':893,'SystemTimeMicroseconds':98,'OSCPUVirtualTimeMicroseconds':990,'OSReadChars':1322,'OSWriteChars':8,'InterfaceNativeSendBytes':3829,'ConcurrencyControlSlotsGranted':1,'ConcurrencyControlSlotsAcquiredNonCompeting':1}
Settings:                               {'connect_timeout_with_failover_ms':'1000','use_uncompressed_cache':'0','load_balancing':'nearest_hostname','distributed_aggregation_memory_efficient':'1','parallel_distributed_insert_select':'0','do_not_merge_across_partitions_select_final':'1','os_thread_priority':'2','log_queries':'1','join_use_nulls':'1','prefer_localhost_replica':'0','parallel_view_processing':'1','date_time_input_format':'best_effort','output_format_json_quote_64bit_integers':'1'}
used_aggregate_functions:               []
used_aggregate_function_combinators:    []
used_database_engines:                  []
used_data_type_families:                []
used_dictionaries:                      []
used_formats:                           []
used_functions:                         []
used_storages:                          []
used_table_functions:                   []
used_executable_user_defined_functions: []
used_sql_user_defined_functions:        []
used_row_policies:                      []
used_privileges:                        ['DROP DATABASE ON cici.*','CLUSTER ON *.*']
missing_privileges:                     []
transaction_id:                         (0,0,'00000000-0000-0000-0000-000000000000')
query_cache_usage:                      None
asynchronous_read_counters:             {}
```

### Which ClickHouse versions are affected?

`25.8.x`

### How to reproduce

Have a replicated (1+1) cluster with Keeper.

Create or drop a database with the `ON CLUSTER` clause like this:

`CREATE DATABASE cici ON CLUSTER '{cluster}';` or
`DROP DATABASE cici ON CLUSTER '{cluster}';`

**Comment by den-crane** [comment]
* https://github.com/ClickHouse/ClickHouse/issues/86434

* https://github.com/ClickHouse/ClickHouse/pull/86479

Fixed but not released in 25.8 branch.

**Comment by den-crane** [comment]
Workarounds are

```
<clickhouse>
  <remote_servers replace="1">
        ...
```

or 

```
<clickhouse>
   <remote_servers>
        <default remove="1"></default>
        ...
```

**Comment by sigxcpu76** [comment]
Actually this does not solve the issue.

On a working 25.7 node I do get the `default` cluster:

```
:) select count() from system.clusters where cluster='default';

SELECT count()
FROM system.clusters
WHERE cluster = 'default'

Query id: be9736e1-6666-4dbb-915a-32b21fb0e6f0

   ┌─count()─┐
1. │       1 │
   └─────────┘

```

On a "fixed" 25.8 node I don't get it:

```
:) select count() from system.clusters where cluster='default';

SELECT count()
FROM system.clusters
WHERE cluster = 'default'

Query id: cab504bf-30b9-44ea-a2c2-82edfda254c2

   ┌─count()─┐
1. │       0 │
   └─────────┘

```

Still, the above queries take a lot of time. 

If it matters, 25.7 with the fix applied is still fast.

**Comment by den-crane** [comment]
>Still, the above queries take a lot of time.

Check `select * from system.clusters` do you see `localhost` or `127.0.01` in the output ?

**Comment by sigxcpu76** [comment]
Yes, all the `all-*` cluster entries have one of the `host_address` fields (this is a replicated 2 node cluster) as `127.0.0.1`.

```
    ┌─cluster────────┬─host_address─┬─host_name─────────────────────────────────────────────────────────────────────────────┐
 1. │ all-clusters   │ 127.0.0.1    │ chi-analytics-analytics-0-0                                                           │
 2. │ all-clusters   │ 10.76.59.79  │ chi-analytics-analytics-0-1                                                           │
 3. │ all-replicated │ 127.0.0.1    │ chi-analytics-analytics-0-0                                                           │
 4. │ all-replicated │ 10.76.59.79  │ chi-analytics-analytics-0-1                                                           │
 5. │ all-sharded    │ 127.0.0.1    │ chi-analytics-analytics-0-0                                                           │
 6. │ all-sharded    │ 10.76.59.79  │ chi-analytics-analytics-0-1                                                           │
 7. │ analytics      │ 127.0.0.1    │ chi-analytics-analytics-0-0                                                           │
 8. │ analytics      │ 10.76.59.79  │ chi-analytics-analytics-0-1                                                           │
 ```

**Comment by den-crane** [comment]
It should not be like this `analytics      │ 127.0.0.1 `  , it should be normal `10.76...` address.
Your chi installation is misconfigured. You should address this question to https://github.com/Altinity/clickhouse-operator/issues

**Comment by sigxcpu76** [comment]
Yes, I was suspecting that. I am looking for ways to get rid of it. Funny that 25.7 has no issues with this, regardless of the Keeper version. It is 25.8 specific.

**Comment by den-crane** [comment]
> Funny that 25.7 has no issues with thi

Yes, it's well known problem. It's 25.8's regression introduced recently in the https://github.com/ClickHouse/ClickHouse/pull/81395 .

**Comment by den-crane** [comment]
BTW it should be fixed in 25.8.4

v25.8.4.13-lts.md:* Backported in [#87222](https://github.com/ClickHouse/ClickHouse/issues/87222): Handling loopback host ID properly to avoid collision when processing DDL tasks:. [#86479](https://github.com/ClickHouse/ClickHouse/pull/86479) ([Tuan Pham Anh](https://github.com/tuanpach)).

**Comment by filimonov** [comment]
> It should not be like this `analytics │ 127.0.0.1 ` , it should be normal `10.76...` address. Your chi installation is misconfigured. You should address this question to https://github.com/Altinity/clickhouse-operator/issues

Operator does not put any ips into the config. It put's there the domain names (in general in k8 you should not rely on any ips normally). 

'self' domain name get resolved as 127.0.0.1 by clickhouse
